<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Modul 10 Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA | Modul Praktik Statistika Untuk Perencanaan</title>
<meta name="author" content="Team Teaching Statistika Untuk Perencanaan, PWK ITERA">
<meta name="generator" content="bookdown 0.46 with bs4_book()">
<meta property="og:title" content="Modul 10 Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA | Modul Praktik Statistika Untuk Perencanaan">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Modul 10 Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA | Modul Praktik Statistika Untuk Perencanaan">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="libs/tabwid-1.1.3/tabwid.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
<meta name="description" content="Setelah mempelajari modul ini, Anda diharapkan dapat menghasilkan komponen prinsip menggunakan perangkat lunak komputer STP-14.3  10.1 Pendahuluan Analisis Komponen Prinsip (Principal Component...">
<meta property="og:description" content="Setelah mempelajari modul ini, Anda diharapkan dapat menghasilkan komponen prinsip menggunakan perangkat lunak komputer STP-14.3  10.1 Pendahuluan Analisis Komponen Prinsip (Principal Component...">
<meta name="twitter:description" content="Setelah mempelajari modul ini, Anda diharapkan dapat menghasilkan komponen prinsip menggunakan perangkat lunak komputer STP-14.3  10.1 Pendahuluan Analisis Komponen Prinsip (Principal Component...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Penggunaan R dalam Pengolahan Data Kuantitatif">Modul Praktik Statistika Untuk Perencanaan</a>:
        <small class="text-muted">Penggunaan R dalam Pengolahan Data Kuantitatif</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Pengantar</a></li>
<li><a class="" href="pengenalan-r-dan-rstudio.html">Pengenalan R dan RStudio</a></li>
<li><a class="" href="pengenalan-teknis-r.html">Pengenalan Teknis R</a></li>
<li><a class="" href="modul-1.html"><span class="header-section-number">1</span> Pengolahan Data Terstruktur</a></li>
<li><a class="" href="analisis-statistika-deskriptif.html"><span class="header-section-number">2</span> Analisis Statistika Deskriptif</a></li>
<li><a class="" href="visualisasi-data-kuantitatif.html"><span class="header-section-number">3</span> Visualisasi Data Kuantitatif</a></li>
<li><a class="" href="distribusi-sampling-dan-interval-kepercayaan.html"><span class="header-section-number">4</span> Distribusi Sampling dan Interval Kepercayaan</a></li>
<li><a class="" href="uji-hipotesis-satu-populasi.html"><span class="header-section-number">5</span> Uji Hipotesis Satu Populasi</a></li>
<li><a class="" href="uji-hipotesis-dua-populasi.html"><span class="header-section-number">6</span> Uji Hipotesis Dua Populasi</a></li>
<li><a class="" href="analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><span class="header-section-number">7</span> Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal</a></li>
<li><a class="" href="analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><span class="header-section-number">8</span> Analisis Hubungan Korelatif: Korelasi Variabel Metrik</a></li>
<li><a class="" href="analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><span class="header-section-number">9</span> Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda</a></li>
<li><a class="active" href="analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><span class="header-section-number">10</span> Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA</a></li>
<li><a class="" href="referensi.html"><span class="header-section-number">11</span> Referensi</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca" class="section level1" number="10">
<h1>
<span class="header-section-number">Modul 10</span> Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA<a class="anchor" aria-label="anchor" href="#analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca"><i class="fas fa-link"></i></a>
</h1>
<p>Setelah mempelajari modul ini, Anda diharapkan dapat menghasilkan komponen prinsip menggunakan perangkat lunak komputer <span class="capaian">STP-14.3</span></p>
<hr>
<div id="pendahuluan-5" class="section level2" number="10.1">
<h2>
<span class="header-section-number">10.1</span> Pendahuluan<a class="anchor" aria-label="anchor" href="#pendahuluan-5"><i class="fas fa-link"></i></a>
</h2>
<p>Analisis Komponen Prinsip (<em>Principal Component Analysis</em>, PCA) dan Analisis Faktor (<em>Common Factor Analysis</em>) adalah metode analisis multivariat yang digunakan untuk meringkas atau mereduksi jumlah variabel yang banyak menjadi beberapa dimensi baru (disebut komponen atau faktor) yang lebih sedikit, namun tetap merepresentasikan informasi dari variabel asli.</p>
<p>Kedua metode ini termasuk dalam analisis interdependensi, di mana seluruh variabel dianggap setara dan saling berhubungan satu sama lain, tanpa ada pembagian variabel independen dan dependen.</p>
</div>
<div id="studi-kasus" class="section level2" number="10.2">
<h2>
<span class="header-section-number">10.2</span> Studi Kasus<a class="anchor" aria-label="anchor" href="#studi-kasus"><i class="fas fa-link"></i></a>
</h2>
<p>Kita akan menggunakan data <span class="citation">Bindar (<a href="referensi.html#ref-bindar2022faktor">2022</a>)</span>, yaitu penelitian mengenai preferensi masyarakat Kota Bandung dalam mengakses lokasi <em>Car-Free Day</em> (CFD). Terdapat 12 variabel yang akan dianalisis:</p>
<ol style="list-style-type: decimal">
<li>
<code>ongkos</code>: Total biaya perjalanan</li>
<li>
<code>bparkir</code>: Biaya parkir</li>
<li>
<code>durasi</code>: Durasi perjalanan</li>
<li>
<code>bareng</code>: Jumlah rombongan dalam perjalanan</li>
<li>
<code>toplajur</code>: Jumlah lajur jalan terbanyak yang dilalui</li>
<li>
<code>usia</code>: Usia pelaku perjalanan</li>
<li>
<code>jmlmotor</code>: Jumlah sepeda motor di rumah tangga</li>
<li>
<code>jmlmobil</code>: Jumlah mobil di rumah tangga</li>
<li>
<code>jmlsepeda</code>: Jumlah sepeda di rumah tangga</li>
<li>
<code>jmldewasa</code>: Jumlah orang dewasa dalam rumah tangga</li>
<li>
<code>jmlanak</code>: Jumlah anak-anak dalam rumah tangga</li>
<li>
<code>jarak</code>: Jarak tempuh dari rumah ke lokasi CFD</li>
</ol>
</div>
<div id="memuat-pustaka-libraries" class="section level2" number="10.3">
<h2>
<span class="header-section-number">10.3</span> Memuat Pustaka <em>(Libraries)</em><a class="anchor" aria-label="anchor" href="#memuat-pustaka-libraries"><i class="fas fa-link"></i></a>
</h2>
<p>Kita membutuhkan paket <code>tidyverse</code> untuk manipulasi data dan <code>psych</code> untuk melakukan uji KMO, Bartlett, serta fungsi analisis faktor dan PCA.</p>
<div class="sourceCode" id="cb310"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span></span></code></pre></div>
</div>
<div id="asumsi-awal" class="section level2" number="10.4">
<h2>
<span class="header-section-number">10.4</span> Asumsi Awal<a class="anchor" aria-label="anchor" href="#asumsi-awal"><i class="fas fa-link"></i></a>
</h2>
<p>Sebelum melakukan analisis komponen prinsip atau analisis faktor, idealnya kita perlu memeriksa asumsi dasar, yaitu:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Linearitas</strong>: Adanya hubungan linear antarvariabel.</li>
<li>
<strong>Normalitas</strong>: Variabel berdistribusi normal multivariat.</li>
</ol>
<p>Kita dapat melakukan inspeksi visual menggunakan matriks diagram pencar (<em>scatter plot matrix</em>). Di sini kita menggunakan fungsi <code>pairs.panels</code> dari paket <code>psych</code> yang memberikan informasi lengkap berupa scatter plot, histogram, dan nilai korelasi.</p>
<div class="sourceCode" id="cb311"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Membaca data (Kita muat di sini untuk keperluan inspeksi awal)</span></span>
<span><span class="co"># Jika data belum dimuat, baris ini akan memuatnya.</span></span>
<span><span class="va">data_cfd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv2</a></span><span class="op">(</span><span class="st">"datasets/Data Praktikum 09.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Memilih 12 variabel metrik yang akan dianalisis sesuai studi kasus</span></span>
<span><span class="co"># Variabel ini sama dengan yang akan digunakan pada tahap persiapan data selanjutnya</span></span>
<span><span class="va">data_selected</span> <span class="op">&lt;-</span> <span class="va">data_cfd</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span></span>
<span>    <span class="va">ongkos</span>, <span class="va">bparkir</span>, <span class="va">durasi</span>, <span class="va">bareng</span>, <span class="va">toplajur</span>, <span class="va">usia</span>,</span>
<span>    <span class="va">jmlmotor</span>, <span class="va">jmlmobil</span>, <span class="va">jmlsepeda</span>, <span class="va">jmldewasa</span>, <span class="va">jmlanak</span>, <span class="va">jarak</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Membuat Scatter Plot Matrix menggunakan psych::pairs.panels</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/pairs.panels.html">pairs.panels</a></span><span class="op">(</span><span class="va">data_selected</span>,</span>
<span>  method <span class="op">=</span> <span class="st">"pearson"</span>, <span class="co"># Menggunakan korelasi Pearson</span></span>
<span>  hist.col <span class="op">=</span> <span class="st">"#00AFBB"</span>, <span class="co"># Warna histogram</span></span>
<span>  density <span class="op">=</span> <span class="cn">FALSE</span>, <span class="co"># Tidak menampilkan garis density agar lebih bersih</span></span>
<span>  lm.col <span class="op">=</span> <span class="st">"red"</span>, <span class="co"># Mengubah warna data points menjadi abu-abu gelap</span></span>
<span>  ellipses <span class="op">=</span> <span class="cn">TRUE</span>, <span class="co"># Menampilkan elips korelasi untuk melihat pola linearitas</span></span>
<span>  lm <span class="op">=</span> <span class="cn">TRUE</span>, <span class="co"># Menampilkan garis regresi linear lurus</span></span>
<span>  main <span class="op">=</span> <span class="st">"Scatter Plot Matrix Asumsi Awal"</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="figures/mod09-check-assumptions-1.png" width="960"></div>
<p><strong>Penjelasan Kode dan Output:</strong></p>
<ul>
<li>
<strong>Kode</strong>: Kita menggunakan fungsi <code>pairs.panels</code> dari paket <code>psych</code>. Argumen <code>method = "pearson"</code> digunakan untuk menghitung koefisien korelasi Pearson. <code>hist.col</code> mengatur warna histogram di diagonal utama. <code>ellipses = TRUE</code> menambahkan elips yang menggambarkan kovarians dan arah hubungan.</li>
<li>
<strong>Output</strong>:
<ul>
<li>
<strong>Diagonal Utama</strong>: Menampilkan histogram distribusi frekuensi untuk setiap variabel. Kita dapat melihat apakah distribusi variabel mendekati normal (bentuk lonceng) atau menceng (<em>skewed</em>).</li>
<li>
<strong>Bawah Diagonal</strong>: Menampilkan <em>scatter plot</em> (diagram pencar) untuk setiap pasangan variabel. Ini berguna untuk mendeteksi pola hubungan (apakah linear) dan adanya pencilan (<em>outliers</em>).</li>
<li>
<strong>Atas Diagonal</strong>: Menampilkan nilai koefisien korelasi Pearson (<span class="math inline">\(r\)</span>). Ukuran font angka korelasi menyesuaikan dengan besarnya nilai korelasi (semakin besar nilai, semakin besar font). <strong>Interpretasi Singkat</strong>:</li>
<li>
<strong>Normalitas</strong>: Pada diagonal utama, histogram yang berbentuk lonceng menunjukkan distribusi mendekati normal. Distribusi yang menceng (<em>skewed</em>) atau tidak simetris menandakan ketidaknormalan.</li>
<li>
<strong>Linearitas</strong>: Perhatikan bagian bawah diagonal (Scatter Plot).
<ul>
<li>
<strong>Garis Tren</strong>: Indikasi linearitas dapat dilihat dari garis tren (biasanya berwarna merah) yang terbentuk di antara titik-titik data. Jika garis tersebut cenderung lurus, maka hubungan antar variabel bersifat linear.</li>
<li>
<strong>Elips</strong>: Bentuk elips menunjukkan kekuatan korelasi. <strong>Elips yang pipih (sempit)</strong> menandakan korelasi kuat dan hubungan yang jelas. Sebaliknya, <strong>elips yang cenderung bulat</strong> menandakan korelasi yang lemah.</li>
<li>Perbesar grafik dengan membuka hasil di jendela baru atau klik ‘Zoom’ jika ia muncul di panel ‘Plots’.</li>
</ul>
</li>
</ul>
</li>
</ul>
<p><strong>Latihan 2:</strong></p>
<p>Berdasarkan <em>Scatter Plot Matrix</em> di atas:</p>
<ol style="list-style-type: decimal">
<li>Sebutkan satu variabel yang menurut Anda memiliki distribusi mendekati normal (lihat histogram diagonal)!</li>
<li>Sebutkan pasangan variabel yang memiliki hubungan linear cukup kuat (lihat bentuk elips/sebaran data)!</li>
</ol>
</div>
<div id="mempersiapkan-data" class="section level2" number="10.5">
<h2>
<span class="header-section-number">10.5</span> Mempersiapkan Data<a class="anchor" aria-label="anchor" href="#mempersiapkan-data"><i class="fas fa-link"></i></a>
</h2>
<p>Kita memastikan kembali variabel yang akan digunakan dalam analisis ini.</p>
<div class="sourceCode" id="cb312"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Memilih variabel yang akan dianalisis</span></span>
<span><span class="va">data_analisis</span> <span class="op">&lt;-</span> <span class="va">data_cfd</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span></span>
<span>    <span class="va">ongkos</span>, <span class="va">bparkir</span>, <span class="va">durasi</span>, <span class="va">bareng</span>, <span class="va">toplajur</span>, <span class="va">usia</span>,</span>
<span>    <span class="va">jmlmotor</span>, <span class="va">jmlmobil</span>, <span class="va">jmlsepeda</span>, <span class="va">jmldewasa</span>, <span class="va">jmlanak</span>, <span class="va">jarak</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Melihat sekilas data</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_analisis</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 319
## Columns: 12
## $ ongkos    &lt;dbl&gt; 464.40, 464.40, 464.40, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 10000.00, 30000.00, 0.00…
## $ bparkir   &lt;dbl&gt; 2000, 2000, 3000, 0, 0, 0, 0, 0, 0, 0, 2000, 5000, 0, 0, 0, 0, 0, 0, 0, 3000, 0, 0, 0, 0, …
## $ durasi    &lt;dbl&gt; 20, 10, 15, 30, 5, 30, 5, 30, 5, 9, 30, 30, 10, 30, 2, 30, 60, 30, 30, 30, 20, 5, 45, 60, …
## $ bareng    &lt;dbl&gt; 2, 0, 2, 5, 2, 0, 0, 0, 0, 0, 2, 3, 1, 0, 10, 3, 2, 3, 3, 2, 1, 1, 0, 1, 1, 1, 3, 0, 0, 1,…
## $ toplajur  &lt;dbl&gt; 4, 4, 4, 8, 2, 4, 4, 4, 0, 2, 8, 6, 4, 4, 2, 4, 6, 4, 4, 4, 4, 4, 8, 4, 4, 4, 2, 4, 6, 6, …
## $ usia      &lt;dbl&gt; 45, 46, 50, 25, 22, 63, 22, 60, 20, 19, 16, 46, 22, 28, 50, 28, 17, 28, 25, 43, 34, 17, 70…
## $ jmlmotor  &lt;dbl&gt; 2, 2, 3, 0, 2, 1, 1, 2, 1, 0, 2, 1, 1, 4, 5, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, …
## $ jmlmobil  &lt;dbl&gt; 0, 1, 0, 0, 3, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, …
## $ jmlsepeda &lt;dbl&gt; 2, 4, 0, 2, 3, 2, 1, 1, 0, 0, 0, 2, 0, 2, 6, 1, 4, 1, 1, 0, 1, 0, 3, 3, 1, 0, 1, 1, 1, 1, …
## $ jmldewasa &lt;dbl&gt; 4, 4, 4, 3, 5, 2, 2, 4, 1, 1, 3, 1, 5, 2, 2, 3, 5, 12, 5, 2, 1, 2, 5, 2, 6, 2, 12, 3, 3, 2…
## $ jmlanak   &lt;dbl&gt; 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 3, 3, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, …
## $ jarak     &lt;dbl&gt; 3000, 3000, 3000, 7000, 280, 7000, 600, 7200, 0, 500, 5000, 4000, 2000, 5000, 1000, 5000, …</code></pre>
<p><strong>Latihan 1:</strong></p>
<p>Berdasarkan output <code>glimpse</code> di atas, jawablah pertanyaan berikut:</p>
<ol style="list-style-type: decimal">
<li>Berapa jumlah observasi (baris) atau objek dalam data tersebut?</li>
<li>Berapa jumlah variabel (kolom) yang aktif digunakan dalam analisis?</li>
</ol>
</div>
<div id="uji-kelayakan-data-asumsi" class="section level2" number="10.6">
<h2>
<span class="header-section-number">10.6</span> Uji Kelayakan Data (Asumsi)<a class="anchor" aria-label="anchor" href="#uji-kelayakan-data-asumsi"><i class="fas fa-link"></i></a>
</h2>
<p>Sebelum melakukan ekstraksi dimensi, kita perlu memastikan data layak untuk dianalisis faktor/PCA. Dua indikator utama adalah <strong>Uji Bartlett of Sphericity</strong> dan <strong>Measure of Sampling Adequacy (MSA)</strong> atau <strong>Kaiser-Meyer-Olkin (KMO)</strong>.</p>
<div id="uji-bartlett-of-sphericity" class="section level3" number="10.6.1">
<h3>
<span class="header-section-number">10.6.1</span> Uji Bartlett of Sphericity<a class="anchor" aria-label="anchor" href="#uji-bartlett-of-sphericity"><i class="fas fa-link"></i></a>
</h3>
<p>Uji ini melihat apakah terdapat korelasi antarvariabel dalam data. Syarat: Nilai <span class="math inline">\(p &lt; 0,05\)</span>.</p>
<div class="sourceCode" id="cb314"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Uji Bartlett</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/cortest.bartlett.html">cortest.bartlett</a></span><span class="op">(</span><span class="va">data_analisis</span><span class="op">)</span></span></code></pre></div>
<pre><code>## $chisq
## [1] 573.4283
## 
## $p.value
## [1] 5.636504e-82
## 
## $df
## [1] 66</code></pre>
<p><strong>Latihan 3:</strong></p>
<p>Lihat nilai <span class="math inline">\(p.value\)</span> pada output di atas. Apakah nilai tersebut <span class="math inline">\(&lt; 0.05\)</span>? Apa kesimpulan Anda mengenai korelasi antar variabel dalam data ini? (Apakah matriks korelasi berbeda secara signifikan dengan matriks identitas?)</p>
</div>
<div id="uji-kmo-dan-msa" class="section level3" number="10.6.2">
<h3>
<span class="header-section-number">10.6.2</span> Uji KMO dan MSA<a class="anchor" aria-label="anchor" href="#uji-kmo-dan-msa"><i class="fas fa-link"></i></a>
</h3>
<p>Nilai KMO keseluruhan harus <span class="math inline">\(&gt; 0,5\)</span>. Selain itu, nilai MSA per variabel (diagonal pada matriks anti-image correlation) juga harus <span class="math inline">\(&gt; 0,5\)</span>.</p>
<div class="sourceCode" id="cb316"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Uji KMO</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/KMO.html">KMO</a></span><span class="op">(</span><span class="va">data_analisis</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Kaiser-Meyer-Olkin factor adequacy
## Call: KMO(r = data_analisis)
## Overall MSA =  0.63
## MSA for each item = 
##    ongkos   bparkir    durasi    bareng  toplajur      usia  jmlmotor  jmlmobil jmlsepeda jmldewasa   jmlanak 
##      0.66      0.65      0.60      0.63      0.81      0.62      0.61      0.61      0.57      0.48      0.44 
##     jarak 
##      0.64</code></pre>
<p>Berdasarkan hasil di atas: - Nilai KMO Keseluruhan (<em>Overall MSA</em>) = 0,63 (Layak, &gt; 0,5). - Namun, jika dilihat per variabel (<em>MSA for each item</em>), terdapat variabel dengan nilai &lt; 0,5 yaitu <code>jmldewasa</code> (0,48) dan <code>jmlanak</code> (0,44).</p>
<p>Sesuai prosedur, kita harus mengeluarkan variabel yang tidak memenuhi syarat MSA.</p>
<div class="sourceCode" id="cb318"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mengeluarkan variabel jmldewasa dan jmlanak</span></span>
<span><span class="va">data_analisis_final</span> <span class="op">&lt;-</span> <span class="va">data_analisis</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">jmldewasa</span>, <span class="op">-</span><span class="va">jmlanak</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Cek ulang KMO</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/KMO.html">KMO</a></span><span class="op">(</span><span class="va">data_analisis_final</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Kaiser-Meyer-Olkin factor adequacy
## Call: KMO(r = data_analisis_final)
## Overall MSA =  0.65
## MSA for each item = 
##    ongkos   bparkir    durasi    bareng  toplajur      usia  jmlmotor  jmlmobil jmlsepeda     jarak 
##      0.66      0.65      0.60      0.63      0.82      0.62      0.64      0.62      0.58      0.64</code></pre>
<p>Sekarang seluruh variabel memiliki MSA &gt; 0,5 dan KMO keseluruhan naik menjadi 0,68. Data siap diekstraksi.</p>
</div>
</div>
<div id="mengekstrak-dimensi-baru" class="section level2" number="10.7">
<h2>
<span class="header-section-number">10.7</span> Mengekstrak Dimensi Baru<a class="anchor" aria-label="anchor" href="#mengekstrak-dimensi-baru"><i class="fas fa-link"></i></a>
</h2>
<p>Langkah selanjutnya adalah menentukan berapa jumlah dimensi (faktor/komponen) yang akan dibentuk. Kita dapat menggunakan <strong>Analisis Paralel</strong> atau melihat <strong>Nilai Eigen</strong> (<em>Eigenvalues</em>) dan <strong>Scree Plot</strong>.</p>
<div id="nilai-eigen-dan-total-variansi" class="section level3" number="10.7.1">
<h3>
<span class="header-section-number">10.7.1</span> Nilai Eigen dan Total Variansi<a class="anchor" aria-label="anchor" href="#nilai-eigen-dan-total-variansi"><i class="fas fa-link"></i></a>
</h3>
<p>Kita akan melihat berapa banyak variansi yang bisa dijelaskan oleh setiap komponen.</p>
<div class="sourceCode" id="cb320"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Melakukan PCA tanpa rotasi untuk melihat Eigenvalues</span></span>
<span><span class="va">analisis_awal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/psych/man/principal.html">principal</a></span><span class="op">(</span><span class="va">data_analisis_final</span>, nfactors <span class="op">=</span> <span class="fl">10</span>, rotate <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menampilkan nilai eigen</span></span>
<span><span class="va">analisis_awal</span><span class="op">$</span><span class="va">values</span></span></code></pre></div>
<pre><code>##  [1] 2.4878770 1.6496907 1.2355641 1.0172985 0.8514614 0.8261586 0.6137405 0.5061041 0.4703792 0.3417258</code></pre>
<p>Kriteria umum penentuan jumlah dimensi: 1. <strong>Kaiser’s Criterion</strong>: Ambil komponen dengan nilai eigen &gt; 1. 2. <strong>Cumulative Variance</strong>: Ambil jumlah komponen yang menjelaskan total variansi &gt; 60%.</p>
<p>Dari nilai eigen di atas, terdapat 4 komponen dengan nilai &gt; 1 (2.488, 1.650, 1.236, 1.017).</p>
</div>
<div id="scree-plot" class="section level3" number="10.7.2">
<h3>
<span class="header-section-number">10.7.2</span> <em>Scree Plot</em><a class="anchor" aria-label="anchor" href="#scree-plot"><i class="fas fa-link"></i></a>
</h3>
<p>Grafik ini menunjukkan penurunan nilai eigen. Titik di mana grafik mulai melandai (siku) menunjukkan batas jumlah faktor.</p>
<div class="sourceCode" id="cb322"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Membuat Scree Plot</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/VSS.scree.html">scree</a></span><span class="op">(</span><span class="va">data_analisis_final</span>, pc <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="figures/mod09-scree-plot-1.png" width="672"></div>
<p><strong>Latihan 4:</strong></p>
<ol style="list-style-type: decimal">
<li>Berdasarkan <strong>Kaiser’s Criterion</strong> (Nilai Eigen &gt; 1) pada sub-bab 9.7.1, berapa komponen yang sebaiknya diekstrak?</li>
<li>Berdasarkan <strong>Scree Plot</strong> di atas (lihat titik siku/ <em>elbow</em>), berapa komponen yang sebaiknya diekstrak?</li>
</ol>
<p>Berdasarkan analisis-analisis sebelumnya, diputuskan untuk menggunakan <strong>4 dimensi</strong>.</p>
</div>
</div>
<div id="melakukan-analisis-faktor-dan-rotasi" class="section level2" number="10.8">
<h2>
<span class="header-section-number">10.8</span> Melakukan Analisis Faktor dan Rotasi<a class="anchor" aria-label="anchor" href="#melakukan-analisis-faktor-dan-rotasi"><i class="fas fa-link"></i></a>
</h2>
<p>Kita akan melakukan ekstraksi 4 faktor menggunakan metode <strong>Analisis Faktor</strong> (untuk pengelompokan variabel) dan <strong>PCA</strong> (untuk pembentukan variat), kemudian melakukan <strong>Rotasi Varimax</strong> agar pengelompokan variabel lebih tegas (nilai <em>loading</em> kontras).</p>
<div id="analisis-faktor-common-factor-analysis" class="section level3" number="10.8.1">
<h3>
<span class="header-section-number">10.8.1</span> Analisis Faktor (Common Factor Analysis)<a class="anchor" aria-label="anchor" href="#analisis-faktor-common-factor-analysis"><i class="fas fa-link"></i></a>
</h3>
<p>Analisis ini bertujuan mengelompokkan variabel-variabel yang mirip (korelasi tinggi) ke dalam faktor laten.</p>
<div class="sourceCode" id="cb323"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Analisis Faktor dengan 4 faktor dan rotasi Varimax</span></span>
<span><span class="co"># fm="pa" (Principal Axis) adalah metode umum untuk Common Factor Analysis di R (mirip SPSS)</span></span>
<span><span class="va">af_result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/psych/man/fa.html">fa</a></span><span class="op">(</span><span class="va">data_analisis_final</span>, nfactors <span class="op">=</span> <span class="fl">4</span>, rotate <span class="op">=</span> <span class="st">"varimax"</span>, fm <span class="op">=</span> <span class="st">"pa"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menampilkan hasil loading faktor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">af_result</span><span class="op">$</span><span class="va">loadings</span>, cutoff <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Loadings:
##           PA1    PA2    PA3    PA4   
## ongkos                   0.667       
## bparkir                  0.699       
## durasi     0.660                     
## bareng                               
## toplajur   0.364         0.401       
## usia                            0.420
## jmlmotor          0.300              
## jmlmobil          0.391              
## jmlsepeda         1.004              
## jarak      0.855                     
## 
##                  PA1   PA2   PA3   PA4
## SS loadings    1.404 1.329 1.238 0.424
## Proportion Var 0.140 0.133 0.124 0.042
## Cumulative Var 0.140 0.273 0.397 0.440</code></pre>
<p><em>Catatan: <code>cutoff = 0.3</code> digunakan untuk menyembunyikan nilai loading yang kecil agar tabel lebih mudah dibaca.</em></p>
<p><strong>Cara Membaca Output:</strong> Perhatikan matriks komponen yang dirotasi (<em>Rotated Factor Matrix</em>). Setiap kolom (PA1, PA2, dst) merepresentasikan faktor. Nilai angka adalah <em>factor loading</em> (korelasi antara variabel dengan faktor).</p>
<p><strong>Contoh Identifikasi Faktor 1 (PA1):</strong> Lihat kolom <code>PA1</code>. Variabel dengan nilai <em>loading</em> terbesar (dan di atas 0.5) adalah: - <code>durasi</code> (0.98) - <code>jarak</code> (0.96) Maka, Faktor 1 dibentuk oleh <code>durasi</code> dan <code>jarak</code>.</p>
<p><strong>Latihan 5:</strong></p>
<p>Berdasarkan output di atas, tentukan variabel pembentuk faktor lainnya:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Faktor 2 (PA2)</strong>: Variabel apa saja yang memiliki <em>loading</em> tinggi di kolom ini?</li>
<li>
<strong>Faktor 3 (PA3)</strong>: Variabel apa saja yang memiliki <em>loading</em> tinggi di kolom ini?</li>
<li>
<strong>Faktor 4 (PA4)</strong>: Variabel apa saja yang memiliki <em>loading</em> tinggi di kolom ini?</li>
</ol>
</div>
<div id="analisis-komponen-prinsip-pca" class="section level3" number="10.8.2">
<h3>
<span class="header-section-number">10.8.2</span> Analisis Komponen Prinsip (PCA)<a class="anchor" aria-label="anchor" href="#analisis-komponen-prinsip-pca"><i class="fas fa-link"></i></a>
</h3>
<p>Jika tujuan kita adalah mereduksi data menjadi skor komponen untuk analisis lanjutan (misal regresi), kita menggunakan PCA.</p>
<div class="sourceCode" id="cb325"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># PCA dengan 4 komponen dan rotasi Varimax</span></span>
<span><span class="va">pca_result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/psych/man/principal.html">principal</a></span><span class="op">(</span><span class="va">data_analisis_final</span>, nfactors <span class="op">=</span> <span class="fl">4</span>, rotate <span class="op">=</span> <span class="st">"varimax"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menampilkan hasil loading komponen (untuk interpretasi)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">pca_result</span><span class="op">$</span><span class="va">loadings</span>, cutoff <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Loadings:
##           RC1    RC3    RC2    RC4   
## ongkos            0.791              
## bparkir           0.823              
## durasi     0.847                     
## bareng                          0.806
## toplajur   0.490  0.425              
## usia                     0.324 -0.601
## jmlmotor   0.344         0.597       
## jmlmobil          0.385  0.638       
## jmlsepeda                0.833       
## jarak      0.825                     
## 
##                  RC1   RC3   RC2   RC4
## SS loadings    1.840 1.753 1.626 1.171
## Proportion Var 0.184 0.175 0.163 0.117
## Cumulative Var 0.184 0.359 0.522 0.639</code></pre>
<div class="sourceCode" id="cb327"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menampilkan bobot skor komponen (weights) untuk pembentukan skor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">pca_result</span><span class="op">$</span><span class="va">weights</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<pre><code>##               RC1     RC3     RC2     RC4
## ongkos     0.0254  0.4485 -0.0730  0.0301
## bparkir   -0.1330  0.5089 -0.0205  0.0298
## durasi     0.5237 -0.1667 -0.0855 -0.0144
## bareng    -0.0276 -0.0299  0.1825  0.7256
## toplajur   0.1979  0.1949  0.0396 -0.1924
## usia      -0.0194 -0.0251  0.1391 -0.4847
## jmlmotor   0.1783 -0.2001  0.3905  0.2852
## jmlmobil  -0.2100  0.2495  0.3974 -0.0890
## jmlsepeda -0.0496 -0.0641  0.5290 -0.0047
## jarak      0.4506  0.0303 -0.0532  0.0381</code></pre>
<p><strong>Identifikasi Persamaan Komponen</strong></p>
<p>Komponen Prinsip (RC) adalah kombinasi linear dari variabel asal (yang sudah distandarisasi). Persamaannya dapat ditulis sebagai: <span class="math display">\[RC_j = w_{1j}Z_1 + w_{2j}Z_2 + \dots + w_{pj}Z_p\]</span> Dimana <span class="math inline">\(w\)</span> adalah nilai <strong>Component Score Coefficients (Weights)</strong>, bukan nilai <em>loading</em>. Loading hanya menunjukkan korelasi, sedangkan weights menunjukkan bobot kontribusi setiap variabel dalam pembentukan skor komponen.</p>
<p><strong>Contoh:</strong> Misalkan kita ingin membentuk persamaan untuk <strong>RC1</strong>. Lihat output <code>Weights</code> pada kolom <code>RC1</code>: - <code>durasi</code>: 0.524 - <code>jarak</code>: 0.451 - Variabel lain memiliki bobot yang lebih kecil.</p>
<p>Maka persamaannya: <span class="math display">\[RC1 \approx 0.524(Z_{durasi}) + 0.451(Z_{jarak}) + \dots\]</span></p>
<p><strong>Menghasilkan Component Score</strong></p>
<p>Untuk mendapatkan nilai skor komponen setiap observasi secara otomatis, kita dapat mengakses objek <code>$scores</code> dari hasil PCA.</p>
<div class="sourceCode" id="cb329"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menampilkan 6 baris pertama dari skor komponen</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">pca_result</span><span class="op">$</span><span class="va">scores</span><span class="op">)</span></span></code></pre></div>
<pre><code>##             RC1        RC3         RC2         RC4
## [1,] -0.1944617 -0.4804209  0.36717340 -0.54187967
## [2,] -0.7752196 -0.1911165  1.50812139 -1.14287093
## [3,] -0.2069996 -0.2693966 -0.04572532 -0.49628033
## [4,]  0.7677605 -0.2647856 -0.21284551  0.01899626
## [5,] -1.6702167 -0.2667413  1.87084197  0.22728535
## [6,]  0.1797747 -0.6385342  0.52415727 -2.00189106</code></pre>
<p><strong>Latihan 6:</strong></p>
<p>Berdasarkan output weights PCA di atas, tuliskan persamaan matematis terbentuknya komponen <strong>RC2</strong>! (Sebutkan variabel mana saja yang memiliki kontribusi besar beserta koefisien weights-nya).</p>
</div>
</div>
<div id="interpretasi-dan-penamaan-dimensi" class="section level2" number="10.9">
<h2>
<span class="header-section-number">10.9</span> Interpretasi dan Penamaan Dimensi<a class="anchor" aria-label="anchor" href="#interpretasi-dan-penamaan-dimensi"><i class="fas fa-link"></i></a>
</h2>
<p>Langkah terakhir adalah memberi nama pada dimensi yang terbentuk berdasarkan variabel-variabel pembentuknya.</p>
<p><strong>Latihan 7:</strong> Tuliskan seluruh kelompok dari analisis faktor dan juga seluruh persamaan komponen yang dihasilkan dari PCA!</p>
<div id="aktivitas-mandiri-komprehensif-analisis-pca-mandiri-stp-14.3.capaian" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri Komprehensif: Analisis PCA Mandiri [STP-14.3].{capaian}<a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-komprehensif-analisis-pca-mandiri-stp-14.3.capaian"><i class="fas fa-link"></i></a>
</h3>
<p>Gunakan dataset dengan variabel metrik yang berbeda:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Persiapan:</strong> Pilih variabel, cek normalitas, uji Bartlett/KMO</li>
<li>
<strong>Ekstraksi:</strong> Hitung eigenvalues, buat scree plot, tentukan jumlah komponen</li>
<li>
<strong>Analisis:</strong> Lakukan PCA dengan rotasi Varimax</li>
<li>
<strong>Interpretasi:</strong> Identifikasi variabel pembentuk, beri nama komponen, tuliskan persamaan</li>
<li>
<strong>Evaluasi:</strong> Hitung proporsi variansi yang dijelaskan</li>
</ol>
</div>
<hr>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><span class="header-section-number">9</span> Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda</a></div>
<div class="next"><a href="referensi.html"><span class="header-section-number">11</span> Referensi</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca"><span class="header-section-number">10</span> Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA</a></li>
<li><a class="nav-link" href="#pendahuluan-5"><span class="header-section-number">10.1</span> Pendahuluan</a></li>
<li><a class="nav-link" href="#studi-kasus"><span class="header-section-number">10.2</span> Studi Kasus</a></li>
<li><a class="nav-link" href="#memuat-pustaka-libraries"><span class="header-section-number">10.3</span> Memuat Pustaka (Libraries)</a></li>
<li><a class="nav-link" href="#asumsi-awal"><span class="header-section-number">10.4</span> Asumsi Awal</a></li>
<li><a class="nav-link" href="#mempersiapkan-data"><span class="header-section-number">10.5</span> Mempersiapkan Data</a></li>
<li>
<a class="nav-link" href="#uji-kelayakan-data-asumsi"><span class="header-section-number">10.6</span> Uji Kelayakan Data (Asumsi)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#uji-bartlett-of-sphericity"><span class="header-section-number">10.6.1</span> Uji Bartlett of Sphericity</a></li>
<li><a class="nav-link" href="#uji-kmo-dan-msa"><span class="header-section-number">10.6.2</span> Uji KMO dan MSA</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#mengekstrak-dimensi-baru"><span class="header-section-number">10.7</span> Mengekstrak Dimensi Baru</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#nilai-eigen-dan-total-variansi"><span class="header-section-number">10.7.1</span> Nilai Eigen dan Total Variansi</a></li>
<li><a class="nav-link" href="#scree-plot"><span class="header-section-number">10.7.2</span> Scree Plot</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#melakukan-analisis-faktor-dan-rotasi"><span class="header-section-number">10.8</span> Melakukan Analisis Faktor dan Rotasi</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#analisis-faktor-common-factor-analysis"><span class="header-section-number">10.8.1</span> Analisis Faktor (Common Factor Analysis)</a></li>
<li><a class="nav-link" href="#analisis-komponen-prinsip-pca"><span class="header-section-number">10.8.2</span> Analisis Komponen Prinsip (PCA)</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#interpretasi-dan-penamaan-dimensi"><span class="header-section-number">10.9</span> Interpretasi dan Penamaan Dimensi</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#aktivitas-mandiri-komprehensif-analisis-pca-mandiri-stp-14.3.capaian">Aktivitas Mandiri Komprehensif: Analisis PCA Mandiri [STP-14.3].{capaian}</a></li></ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Modul Praktik Statistika Untuk Perencanaan</strong>: Penggunaan R dalam Pengolahan Data Kuantitatif" was written by Team Teaching Statistika Untuk Perencanaan, PWK ITERA. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
