<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Modul 7 Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal | Modul Praktik Statistika Untuk Perencanaan</title>
<meta name="author" content="Team Teaching Statistika Untuk Perencanaan, PWK ITERA">
<meta name="generator" content="bookdown 0.45 with bs4_book()">
<meta property="og:title" content="Modul 7 Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal | Modul Praktik Statistika Untuk Perencanaan">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Modul 7 Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal | Modul Praktik Statistika Untuk Perencanaan">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="libs/tabwid-1.1.3/tabwid.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
<meta name="description" content="Setelah mempelajari modul ini, Anda diharapkan dapat: mampu menghasilkan koefisien korelasi variabel di tingkat nominal dengan perangkat lunak komputer STP-9.2 mampu menghasilkan koefisien...">
<meta property="og:description" content="Setelah mempelajari modul ini, Anda diharapkan dapat: mampu menghasilkan koefisien korelasi variabel di tingkat nominal dengan perangkat lunak komputer STP-9.2 mampu menghasilkan koefisien...">
<meta name="twitter:description" content="Setelah mempelajari modul ini, Anda diharapkan dapat: mampu menghasilkan koefisien korelasi variabel di tingkat nominal dengan perangkat lunak komputer STP-9.2 mampu menghasilkan koefisien...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Penggunaan R dalam Pengolahan Data Kuantitatif">Modul Praktik Statistika Untuk Perencanaan</a>:
        <small class="text-muted">Penggunaan R dalam Pengolahan Data Kuantitatif</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Pengantar</a></li>
<li><a class="" href="pengenalan-r-dan-rstudio.html">Pengenalan R dan RStudio</a></li>
<li><a class="" href="pengenalan-teknis-r.html">Pengenalan Teknis R</a></li>
<li><a class="" href="modul-1.html"><span class="header-section-number">1</span> Pengolahan Data Terstruktur</a></li>
<li><a class="" href="analisis-statistika-deskriptif.html"><span class="header-section-number">2</span> Analisis Statistika Deskriptif</a></li>
<li><a class="" href="visualisasi-data-kuantitatif.html"><span class="header-section-number">3</span> Visualisasi Data Kuantitatif</a></li>
<li><a class="" href="distribusi-sampling-dan-interval-kepercayaan.html"><span class="header-section-number">4</span> Distribusi Sampling dan Interval Kepercayaan</a></li>
<li><a class="" href="uji-hipotesis-satu-populasi.html"><span class="header-section-number">5</span> Uji Hipotesis Satu Populasi</a></li>
<li><a class="" href="uji-hipotesis-dua-populasi.html"><span class="header-section-number">6</span> Uji Hipotesis Dua Populasi</a></li>
<li><a class="active" href="analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><span class="header-section-number">7</span> Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal</a></li>
<li><a class="" href="analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><span class="header-section-number">8</span> Analisis Hubungan Korelatif: Korelasi Variabel Metrik</a></li>
<li><a class="" href="analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><span class="header-section-number">9</span> Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda</a></li>
<li><a class="" href="analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><span class="header-section-number">10</span> Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA</a></li>
<li><a class="" href="referensi.html"><span class="header-section-number">11</span> Referensi</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal" class="section level1" number="7">
<h1>
<span class="header-section-number">Modul 7</span> Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal<a class="anchor" aria-label="anchor" href="#analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal"><i class="fas fa-link"></i></a>
</h1>
<div class="rmdcapaian">
<p>Setelah mempelajari modul ini, Anda diharapkan dapat:</p>
<ol style="list-style-type: decimal">
<li>mampu menghasilkan koefisien korelasi variabel di tingkat nominal dengan perangkat lunak komputer <span class="capaian">STP-9.2</span>
</li>
<li>mampu menghasilkan koefisien korelasi variabel di tingkat ordinal dengan perangkat lunak komputer <span class="capaian">STP-10.2</span>
</li>
</ol>
</div>
<div id="pendahuluan-2" class="section level2" number="7.1">
<h2>
<span class="header-section-number">7.1</span> Pendahuluan<a class="anchor" aria-label="anchor" href="#pendahuluan-2"><i class="fas fa-link"></i></a>
</h2>
<p>Analisis korelasi adalah salah satu teknik analisis yang termasuk ke dalam lingkup statistika bivariat, statistika yang analisisnya melibatkan dua variabel <strong>sekaligus</strong>. Pada praktikum-praktikum sebelumnya kita hanya melibatkan satu variabel saja, misalnya:</p>
<ul>
<li>
<p>pada praktikum ke-2, kita mengaplikasikan persentase hanya pada variabel <code>Jenis.Kelamin</code>, <code>Fakultas</code>, <code>Tingkat.Semester</code>, <code>Uang.Saku</code>, atau<code>jenis.tempat.tinggal</code> saja, tetapi tidak menghubungkannya satu sama lain,</p>
<div class="sourceCode" id="cb247"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data.ubl</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html">tbl_summary</a></span><span class="op">(</span>include <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">Jenis.Kelamin</span>,</span>
<span>                          <span class="va">Fakultas</span>,</span>
<span>                          <span class="va">Tingkat.Semester</span>,</span>
<span>                          <span class="va">Uang.Saku</span>,</span>
<span>                          <span class="va">jenis.tempat.tinggal</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/as_flex_table.html">as_flex_table</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
</li>
<li>
<p>pada praktikum ke-3, kita membuat histogram untuk variabel <code>Umur</code> saja</p>
<div class="sourceCode" id="cb248"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">histogram</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">data.ubl.cleaned</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Umur</span><span class="op">)</span>, binwidth <span class="op">=</span> <span class="fl">1</span>, fill <span class="op">=</span> <span class="st">"darkseagreen"</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribusi Umur Mahasiswa"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Umur (Tahun)"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Frekuensi"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">histogram</span></span></code></pre></div>
</li>
<li><p>pada praktikum-praktikum tentang analisis statistik inferensial, kita hanya tertarik pada proporsi atau rata-rata suatu variabel saja, yang pastinya tunggal.</p></li>
</ul>
<p>Dalam praktikum ini kita akan mempraktikkan analisis korelasi pada dua variabel <strong>secara bersamaan.</strong> Ketika kita tertarik pada analisis untuk dua variabel secara bersamaan, artinya kita sedang menganalisis sebuah <strong>keterkaitan</strong> atau sebuah <strong>hubungan</strong>. Dalam praktikum ini, hubungan itu disebut <strong>korelasi</strong>.</p>
<p>Korelasi yang akan kita pelajari adalah korelasi pada pasangan variabel dengan tingkat pengukuran nominal dan juga ordinal.</p>
</div>
<div id="pustaka-libraries-yang-diperlukan" class="section level2" number="7.2">
<h2>
<span class="header-section-number">7.2</span> Pustaka <em>(Libraries)</em> yang Diperlukan<a class="anchor" aria-label="anchor" href="#pustaka-libraries-yang-diperlukan"><i class="fas fa-link"></i></a>
</h2>
<p>Seperti biasa, kita perlu memuat pustaka <em>(libraries)</em> yang diperlukan dalam pengolahan data kita. Beberapa pustaka baru harus kita siapkan untuk analisis korelasi ini, di antaranya adalah <code>rcompanion</code>, <code>RCPA3</code>, dan <code>vcdExtra</code>. Untuk memuat tabel silang kita akan gunakan pustaka <code>gtsummary</code> kembali seperti pada praktikum ke-2.</p>
<div class="sourceCode" id="cb249"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readr.tidyverse.org">readr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ddsjoberg/gtsummary">gtsummary</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://CRAN.R-project.org/package=rcompanion">rcompanion</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">RCPA3</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://friendly.github.io/vcdExtra/">vcdExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://andrisignorell.github.io/DescTools/">DescTools</a></span><span class="op">)</span></span></code></pre></div>
<p>Untuk mengecek apakah pustaka-pustaka tersebut sudah terpasang, kita bisa menggunakan perintah berikut:</p>
<div class="sourceCode" id="cb250"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages</a></span><span class="op">(</span><span class="st">"tidyverse"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages</a></span><span class="op">(</span><span class="st">"readr"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages</a></span><span class="op">(</span><span class="st">"gtsummary"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages</a></span><span class="op">(</span><span class="st">"rcompanion"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages</a></span><span class="op">(</span><span class="st">"RCPA3"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages</a></span><span class="op">(</span><span class="st">"vcdExtra"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages</a></span><span class="op">(</span><span class="st">"DescTools"</span><span class="op">)</span></span></code></pre></div>
<p><strong>Perhatikan dengan seksama</strong> bahwa perintah ini mengandung akhiran “<code>ed</code>” di akhir kata “<code>install</code>”. Perintah ini sangat berbeda dengan <code><a href="https://rdrr.io/r/utils/install.packages.html">install.packages()</a></code> yang biasa kita gunakan untuk memasang pustaka.</p>
</div>
<div id="memuat-dataset-3" class="section level2" number="7.3">
<h2>
<span class="header-section-number">7.3</span> Memuat Dataset<a class="anchor" aria-label="anchor" href="#memuat-dataset-3"><i class="fas fa-link"></i></a>
</h2>
<p>Kita akan menggunakan dataset keempat kampus di Kota Bandar Lampung dan sekitarnya sebagai bahan. Tulis ulang dan jalankan baris perintah berikut untuk mengolah data keempat kampus</p>
<div class="sourceCode" id="cb251"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Membaca data</span></span>
<span><span class="va">data_mahasiswa</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv2</a></span><span class="op">(</span><span class="st">"datasets/Data Praktikum 06.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="mengatur-faktor-untuk-variabel-kategoris" class="section level2" number="7.4">
<h2>
<span class="header-section-number">7.4</span> Mengatur Faktor untuk Variabel Kategoris<a class="anchor" aria-label="anchor" href="#mengatur-faktor-untuk-variabel-kategoris"><i class="fas fa-link"></i></a>
</h2>
<p>Setelah membaca data, kita perlu mengatur variabel-variabel nominal dan ordinal dengan mengatur nilai-nilainya berupa <em>factor</em>.</p>
<p>Namun sebelum itu, kita akan membuat vektor-vektor untuk kita aplikasikan menjadi <em>factor</em> dengan memanfaatkan <code>group_by</code> dan <code>summarize</code> yang berasal dari pustaka <code>dplyr</code>.</p>
<div class="sourceCode" id="cb252"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR UNTUK KAMPUS</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Kampus PT</span></span>
<span><span class="va">faktor_kampus</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>kampus <span class="op">=</span> <span class="va">Kampus_PT</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Membuat vektor untuk faktor Kampus PT dari kolom nama Kampus</span></span>
<span><span class="va">faktor_kampus</span> <span class="op">&lt;-</span> <span class="va">faktor_kampus</span><span class="op">$</span><span class="va">kampus</span></span>
<span></span>
<span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR UNTUK FAKULTAS</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Fakultas</span></span>
<span><span class="va">faktor_fakultas</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>fakultas <span class="op">=</span> <span class="va">Fakultas</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Membuat vektor untuk faktor Fakultas dari kolom nama fakultas</span></span>
<span><span class="va">faktor_fakultas</span> <span class="op">&lt;-</span> <span class="va">faktor_fakultas</span><span class="op">$</span><span class="va">fakultas</span></span>
<span></span>
<span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR UNTUK PROGRAM STUDI</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Prodi</span></span>
<span><span class="va">faktor_prodi</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>prodi <span class="op">=</span> <span class="va">Prodi</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Membuat vektor untuk faktor Prodi dari kolom nama Prodi</span></span>
<span><span class="va">faktor_prodi</span> <span class="op">&lt;-</span> <span class="va">faktor_prodi</span><span class="op">$</span><span class="va">prodi</span></span>
<span></span>
<span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR UNTUK JENIS KELAMIN</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Jenis Kelamin</span></span>
<span><span class="va">faktor_jk</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>jk <span class="op">=</span> <span class="va">`Jenis Kelamin`</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Membuat vektor untuk faktor Jenis Kelamin dari kolom nama Jenis Kelamin</span></span>
<span><span class="va">faktor_jk</span> <span class="op">&lt;-</span> <span class="va">faktor_jk</span><span class="op">$</span><span class="va">jk</span></span>
<span></span>
<span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR UNTUK TINGKAT SEMESTER</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Tingkat Semester</span></span>
<span><span class="va">faktor_semester</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>semester <span class="op">=</span> <span class="va">`Tingkat Semester`</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Membuat vektor faktor Tingkat Semester dari kolom Tingkat Semester</span></span>
<span><span class="va">faktor_semester</span> <span class="op">&lt;-</span> <span class="va">faktor_semester</span><span class="op">$</span><span class="va">semester</span></span>
<span></span>
<span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR UNTUK UANG SAKU</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Uang Saku</span></span>
<span><span class="va">faktor_uang_saku</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>uang <span class="op">=</span> <span class="va">`Uang Saku`</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Memperbaiki urutan uang saku</span></span>
<span><span class="co"># Menukar urutan level 1 dengan level 4 pada faktor uang saku</span></span>
<span><span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">uang</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">4</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">uang</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">1</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">jumlah</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">4</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">jumlah</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">1</span><span class="op">)</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Menukar urutan level 2 dengan level 4 pada faktor uang saku</span></span>
<span><span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">uang</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">4</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">uang</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">2</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">jumlah</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">4</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">jumlah</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">2</span><span class="op">)</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Menukar urutan level 3 dengan level 4 pada faktor uang saku</span></span>
<span><span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">uang</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">uang</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">3</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">jumlah</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">jumlah</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">3</span><span class="op">)</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Membuat vektor faktor Tingkat Uang Saku dari kolom Uang Saku</span></span>
<span><span class="va">faktor_uang_saku</span> <span class="op">&lt;-</span> <span class="va">faktor_uang_saku</span><span class="op">$</span><span class="va">uang</span></span>
<span></span>
<span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR UNTUK KENDARAAN UTAMA</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Kendaraan Utama</span></span>
<span><span class="va">faktor_kendaraan_utama</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>kendaraan <span class="op">=</span> <span class="va">`kendaraan utama`</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Membuat vektpr faktor untuk kendaraan utama dari kolom 'kendaraan'</span></span>
<span><span class="va">faktor_kendaraan_utama</span> <span class="op">&lt;-</span> <span class="va">faktor_kendaraan_utama</span><span class="op">$</span><span class="va">kendaraan</span></span>
<span></span>
<span><span class="co"># ---------------------------</span></span>
<span><span class="co"># MEMBUAT FAKTOR JENIS TEMPAT TINGGAL</span></span>
<span><span class="co"># ---------------------------</span></span>
<span></span>
<span><span class="co"># Meringkas data berdasarkan kolom Jenis Tempat Tinggal</span></span>
<span><span class="va">faktor_jenis_tempat_tinggal</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>tempat_tinggal <span class="op">=</span> <span class="va">`jenis tempat tinggal`</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Membuat vektor faktor untuk jenis tempat tinggal berdasarkan kolom Jenis Tempat Tinggal</span></span>
<span><span class="va">faktor_jenis_tempat_tinggal</span> <span class="op">&lt;-</span> <span class="va">faktor_jenis_tempat_tinggal</span><span class="op">$</span><span class="va">tempat_tinggal</span></span></code></pre></div>
<p>Setelah vektor-vektor variabel kategoris tersebut selesai, barulah selanjutnya kita bisa mengatur <em>factor</em> untuk setiap variabel kategoris.</p>
<div class="sourceCode" id="cb253"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_mahasiswa</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    Kampus_PT <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Kampus_PT</span>, levels <span class="op">=</span> <span class="va">faktor_kampus</span><span class="op">)</span>,</span>
<span>    `Jenis Kelamin` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">`Jenis Kelamin`</span>, levels <span class="op">=</span> <span class="va">faktor_jk</span><span class="op">)</span>,</span>
<span>    Fakultas <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Fakultas</span>, levels <span class="op">=</span> <span class="va">faktor_fakultas</span><span class="op">)</span>,</span>
<span>    Prodi <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Prodi</span>, levels <span class="op">=</span> <span class="va">faktor_prodi</span><span class="op">)</span>,</span>
<span>    `Tingkat Semester` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">`Tingkat Semester`</span>,</span>
<span>      levels <span class="op">=</span> <span class="va">faktor_semester</span>,</span>
<span>      ordered <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>    <span class="op">)</span>, <span class="co"># Variabel ordinal</span></span>
<span>    `Uang Saku` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">`Uang Saku`</span>,</span>
<span>      levels <span class="op">=</span> <span class="va">faktor_uang_saku</span>,</span>
<span>      ordered <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>    <span class="op">)</span>, <span class="co"># Variabel ordinal</span></span>
<span>    `kendaraan utama` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">`kendaraan utama`</span>,</span>
<span>      levels <span class="op">=</span> <span class="va">faktor_kendaraan_utama</span></span>
<span>    <span class="op">)</span>,</span>
<span>    `jenis tempat tinggal` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">`jenis tempat tinggal`</span>,</span>
<span>      levels <span class="op">=</span> <span class="va">faktor_jenis_tempat_tinggal</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<p>Kita dapat memeriksa hasil pekerjaan kita dengan perintah <code>glimpse</code>.</p>
<div class="sourceCode" id="cb254"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Memeriksa hasil pengaturan factor</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_mahasiswa</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 1,557
## Columns: 22
## $ Kampus_PT                  &lt;fct&gt; ITERA, ITERA, ITERA, ITERA, ITERA, ITERA, IT…
## $ `Nomor urut`               &lt;dbl&gt; 17, 211, 342, 42, 56, 254, 267, 289, 330, 25…
## $ `Jenis Kelamin`            &lt;fct&gt; Perempuan, Perempuan, Perempuan, Perempuan, …
## $ Umur                       &lt;dbl&gt; 20, 20, 22, 21, 22, 22, 21, 21, 20, 23, 19, …
## $ Fakultas                   &lt;fct&gt; FTIK, FTIK, FTI, FTIK, FTIK, FTIK, FTIK, FTI…
## $ Prodi                      &lt;fct&gt; Perencanaan Wilayah dan Kota, Perencanaan Wi…
## $ `Tingkat Semester`         &lt;ord&gt; Semester 3-4, Semester 5-6, Semester 7-8, Se…
## $ `Uang Saku`                &lt;ord&gt; "1 - 2 Jt", "2,1 - 3 Jt", "2,1 - 3 Jt", "2,1…
## $ `jumlah mobil`             &lt;dbl&gt; 1, 0, 3, 3, 1, 3, 3, 3, 3, 2, 1, 0, 3, 2, 2,…
## $ `jumlah motor`             &lt;dbl&gt; 0, 1, 2, 3, 0, 2, 2, 3, 2, 2, 0, 1, 1, 2, 1,…
## $ `jumlah sepeda`            &lt;dbl&gt; 1, 1, 3, 3, 0, 2, 3, 4, 2, 2, 1, 0, 1, 2, 1,…
## $ `kendaraan utama`          &lt;fct&gt; Sepeda motor pribadi, Mobil pribadi, Mobil p…
## $ `jenis tempat tinggal`     &lt;fct&gt; Kos sendiri, Rumah pribadi, Rumah pribadi, R…
## $ jarak                      &lt;dbl&gt; 3.47, 4.88, 3.09, 5.46, 3.70, 6.18, 4.87, 5.…
## $ `biaya sepekan`            &lt;dbl&gt; 400, 280, 225, 200, 200, 200, 200, 200, 200,…
## $ `Jumlah Perjalanan Senin`  &lt;dbl&gt; 2, 4, 2, 0, 4, 0, 3, 4, 2, 0, 1, 4, 2, 0, 3,…
## $ `Jumlah Perjalanan Selasa` &lt;dbl&gt; 3, 4, 2, 3, 3, 0, 4, 4, 2, 2, 1, 3, 2, 2, 2,…
## $ `Jumlah Perjalanan Rabu`   &lt;dbl&gt; 3, 5, 0, 4, 3, 3, 4, 4, 0, 2, 1, 2, 2, 2, 4,…
## $ `Jumlah Perjalanan Kamis`  &lt;dbl&gt; 0, 4, 2, 3, 2, 0, 4, 4, 2, 2, 1, 2, 2, 2, 2,…
## $ `Jumlah Perjalanan Jumat`  &lt;dbl&gt; 0, 5, 0, 3, 2, 2, 4, 5, 2, 2, 1, 3, 3, 4, 4,…
## $ `Jumlah Perjalanan Sabtu`  &lt;dbl&gt; 2, 0, 3, 0, 3, 3, 0, 2, 2, 0, 1, 2, 2, 0, 0,…
## $ `Jumlah Perjalanan Ahad`   &lt;dbl&gt; 4, 3, 0, 2, 2, 0, 3, 2, 2, 0, 1, 2, 0, 0, 2,…</code></pre>
</div>
<div id="pembuatan-tabel-silang" class="section level2" number="7.5">
<h2>
<span class="header-section-number">7.5</span> Pembuatan Tabel Silang<a class="anchor" aria-label="anchor" href="#pembuatan-tabel-silang"><i class="fas fa-link"></i></a>
</h2>
<p>Setelah kita memastikan data kita bersih, kita siap untuk menganalisis korelasi antarvariabel kategoris.</p>
<p>Korelasi antarvariabel kategoris memerlukan “bahan baku” berupa <strong>tabel silang</strong> atau <strong><em>cross table</em></strong>. Kebanyakan literatur juga menggunakan istilah <strong><em>contingency table</em></strong>. Tabel silang adalah tabel dua arah, yakni yang baik baris maupun kolomnya adalah <strong>nilai-nilai dari dua variabel</strong> yang disilangkan.</p>
<p><em>Chunk</em> berikut memperlihatkan bagaimana membuat tabel silang antara variabel <code>jenis tempat tinggal</code> dengan <code>kendaraan utama</code> menggunakan <code><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_cross.html">tbl_cross()</a></code> dari pustaka <code>gtsummary</code>.</p>
<div class="sourceCode" id="cb256"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ddsjoberg/gtsummary">gtsummary</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ardata-fr.github.io/flextable-book/">flextable</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menghasilkan tabel silang antara variabel kendaraan utama dan jenis tempat tinggal</span></span>
<span><span class="co"># untuk keperluan presentasi</span></span>
<span><span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_cross.html">tbl_cross</a></span><span class="op">(</span></span>
<span>    row <span class="op">=</span> <span class="va">`kendaraan utama`</span>,</span>
<span>    col <span class="op">=</span> <span class="va">`jenis tempat tinggal`</span>,</span>
<span>    label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>      `kendaraan utama` <span class="op">=</span> <span class="st">"Jenis Kendaraan Utama"</span>,</span>
<span>      `jenis tempat tinggal` <span class="op">=</span> <span class="st">"Jenis Tempat Tinggal"</span></span>
<span>    <span class="op">)</span>,</span>
<span>    percent <span class="op">=</span> <span class="st">"none"</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/as_flex_table.html">as_flex_table</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="tabwid">
<style>.cl-f115ac40{}.cl-f101ed5e{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f106ac36{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f106ac4a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f106ac54{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f106ac55{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f106ac5e{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:15pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f106e174{width:2.967in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e17e{width:0.812in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e17f{width:1.61in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e188{width:1.041in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e192{width:2.264in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e19c{width:2.128in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1a6{width:1.279in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1b0{width:1.372in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1ba{width:0.668in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1bb{width:2.967in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1c4{width:0.812in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1ce{width:1.61in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1d8{width:1.041in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1e2{width:2.264in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1e3{width:2.128in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1ec{width:1.279in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1ed{width:1.372in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e1f6{width:0.668in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e200{width:2.967in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e201{width:0.812in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e20a{width:1.61in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e20b{width:1.041in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e214{width:2.264in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e21e{width:2.128in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e21f{width:1.279in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e228{width:1.372in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e232{width:0.668in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e233{width:2.967in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e23c{width:0.812in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e23d{width:1.61in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e246{width:1.041in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e247{width:2.264in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e250{width:2.128in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e25a{width:1.279in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e264{width:1.372in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e26e{width:0.668in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e26f{width:2.967in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e278{width:0.812in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e279{width:1.61in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e282{width:1.041in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e296{width:2.264in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e297{width:2.128in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2aa{width:1.279in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2ab{width:1.372in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2b4{width:0.668in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2be{width:2.967in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2bf{width:0.812in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2c8{width:1.61in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2d2{width:1.041in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2dc{width:2.264in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2e6{width:2.128in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2f0{width:1.279in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2fa{width:1.372in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e2fb{width:0.668in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e304{width:2.967in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e318{width:0.812in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e322{width:1.61in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e323{width:1.041in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e32c{width:2.264in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e32d{width:2.128in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e336{width:1.279in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e340{width:1.372in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f106e34a{width:0.668in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<div class="inline-table"><table data-quarto-disable-processing="true" class="cl-f115ac40">
<thead>
<tr style="overflow-wrap:break-word;">
<th class="cl-f106e174"><p class="cl-f106ac36"><span class="cl-f101ed5e"> </span></p></th>
<th colspan="7" class="cl-f106e17e"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Jenis Tempat Tinggal</span></p></th>
<th class="cl-f106e1ba"><p class="cl-f106ac4a"><span class="cl-f101ed5e"> </span></p></th>
</tr>
<tr style="overflow-wrap:break-word;">
<th class="cl-f106e174"><p class="cl-f106ac36"><span class="cl-f101ed5e"></span></p></th>
<th class="cl-f106e17e"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Asrama</span></p></th>
<th class="cl-f106e17f"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Kos bersama-sama</span></p></th>
<th class="cl-f106e188"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Kos sendiri</span></p></th>
<th class="cl-f106e192"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Rumah mengontrak bersama</span></p></th>
<th class="cl-f106e19c"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Rumah mengontrak pribadi</span></p></th>
<th class="cl-f106e1a6"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Rumah pribadi</span></p></th>
<th class="cl-f106e1b0"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Rumah saudara</span></p></th>
<th class="cl-f106e1ba"><p class="cl-f106ac4a"><span class="cl-f101ed5e">Total</span></p></th>
</tr>
</thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e1bb"><p class="cl-f106ac54"><span class="cl-f101ed5e">Jenis Kendaraan Utama</span></p></td>
<td class="cl-f106e1c4"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
<td class="cl-f106e1ce"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
<td class="cl-f106e1d8"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
<td class="cl-f106e1e2"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
<td class="cl-f106e1e3"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
<td class="cl-f106e1ec"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
<td class="cl-f106e1ed"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
<td class="cl-f106e1f6"><p class="cl-f106ac55"><span class="cl-f101ed5e"></span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e200"><p class="cl-f106ac5e"><span class="cl-f101ed5e">Berjalan kaki</span></p></td>
<td class="cl-f106e201"><p class="cl-f106ac55"><span class="cl-f101ed5e">23</span></p></td>
<td class="cl-f106e20a"><p class="cl-f106ac55"><span class="cl-f101ed5e">20</span></p></td>
<td class="cl-f106e20b"><p class="cl-f106ac55"><span class="cl-f101ed5e">39</span></p></td>
<td class="cl-f106e214"><p class="cl-f106ac55"><span class="cl-f101ed5e">17</span></p></td>
<td class="cl-f106e21e"><p class="cl-f106ac55"><span class="cl-f101ed5e">11</span></p></td>
<td class="cl-f106e21f"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e228"><p class="cl-f106ac55"><span class="cl-f101ed5e">1</span></p></td>
<td class="cl-f106e232"><p class="cl-f106ac55"><span class="cl-f101ed5e">111</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e200"><p class="cl-f106ac5e"><span class="cl-f101ed5e">Layanan online</span></p></td>
<td class="cl-f106e201"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e20a"><p class="cl-f106ac55"><span class="cl-f101ed5e">19</span></p></td>
<td class="cl-f106e20b"><p class="cl-f106ac55"><span class="cl-f101ed5e">86</span></p></td>
<td class="cl-f106e214"><p class="cl-f106ac55"><span class="cl-f101ed5e">28</span></p></td>
<td class="cl-f106e21e"><p class="cl-f106ac55"><span class="cl-f101ed5e">6</span></p></td>
<td class="cl-f106e21f"><p class="cl-f106ac55"><span class="cl-f101ed5e">37</span></p></td>
<td class="cl-f106e228"><p class="cl-f106ac55"><span class="cl-f101ed5e">12</span></p></td>
<td class="cl-f106e232"><p class="cl-f106ac55"><span class="cl-f101ed5e">188</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e233"><p class="cl-f106ac5e"><span class="cl-f101ed5e">Menumpang dengan teman/keluarga</span></p></td>
<td class="cl-f106e23c"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e23d"><p class="cl-f106ac55"><span class="cl-f101ed5e">18</span></p></td>
<td class="cl-f106e246"><p class="cl-f106ac55"><span class="cl-f101ed5e">24</span></p></td>
<td class="cl-f106e247"><p class="cl-f106ac55"><span class="cl-f101ed5e">40</span></p></td>
<td class="cl-f106e250"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e25a"><p class="cl-f106ac55"><span class="cl-f101ed5e">11</span></p></td>
<td class="cl-f106e264"><p class="cl-f106ac55"><span class="cl-f101ed5e">4</span></p></td>
<td class="cl-f106e26e"><p class="cl-f106ac55"><span class="cl-f101ed5e">97</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e26f"><p class="cl-f106ac5e"><span class="cl-f101ed5e">Mobil pribadi</span></p></td>
<td class="cl-f106e278"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e279"><p class="cl-f106ac55"><span class="cl-f101ed5e">6</span></p></td>
<td class="cl-f106e282"><p class="cl-f106ac55"><span class="cl-f101ed5e">15</span></p></td>
<td class="cl-f106e296"><p class="cl-f106ac55"><span class="cl-f101ed5e">5</span></p></td>
<td class="cl-f106e297"><p class="cl-f106ac55"><span class="cl-f101ed5e">3</span></p></td>
<td class="cl-f106e2aa"><p class="cl-f106ac55"><span class="cl-f101ed5e">110</span></p></td>
<td class="cl-f106e2ab"><p class="cl-f106ac55"><span class="cl-f101ed5e">13</span></p></td>
<td class="cl-f106e2b4"><p class="cl-f106ac55"><span class="cl-f101ed5e">152</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e2be"><p class="cl-f106ac5e"><span class="cl-f101ed5e">Sepeda</span></p></td>
<td class="cl-f106e2bf"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e2c8"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e2d2"><p class="cl-f106ac55"><span class="cl-f101ed5e">8</span></p></td>
<td class="cl-f106e2dc"><p class="cl-f106ac55"><span class="cl-f101ed5e">8</span></p></td>
<td class="cl-f106e2e6"><p class="cl-f106ac55"><span class="cl-f101ed5e">0</span></p></td>
<td class="cl-f106e2f0"><p class="cl-f106ac55"><span class="cl-f101ed5e">1</span></p></td>
<td class="cl-f106e2fa"><p class="cl-f106ac55"><span class="cl-f101ed5e">1</span></p></td>
<td class="cl-f106e2fb"><p class="cl-f106ac55"><span class="cl-f101ed5e">18</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e2be"><p class="cl-f106ac5e"><span class="cl-f101ed5e">Sepeda motor pribadi</span></p></td>
<td class="cl-f106e2bf"><p class="cl-f106ac55"><span class="cl-f101ed5e">2</span></p></td>
<td class="cl-f106e2c8"><p class="cl-f106ac55"><span class="cl-f101ed5e">57</span></p></td>
<td class="cl-f106e2d2"><p class="cl-f106ac55"><span class="cl-f101ed5e">296</span></p></td>
<td class="cl-f106e2dc"><p class="cl-f106ac55"><span class="cl-f101ed5e">125</span></p></td>
<td class="cl-f106e2e6"><p class="cl-f106ac55"><span class="cl-f101ed5e">23</span></p></td>
<td class="cl-f106e2f0"><p class="cl-f106ac55"><span class="cl-f101ed5e">394</span></p></td>
<td class="cl-f106e2fa"><p class="cl-f106ac55"><span class="cl-f101ed5e">94</span></p></td>
<td class="cl-f106e2fb"><p class="cl-f106ac55"><span class="cl-f101ed5e">991</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-f106e304"><p class="cl-f106ac54"><span class="cl-f101ed5e">Total</span></p></td>
<td class="cl-f106e318"><p class="cl-f106ac55"><span class="cl-f101ed5e">25</span></p></td>
<td class="cl-f106e322"><p class="cl-f106ac55"><span class="cl-f101ed5e">120</span></p></td>
<td class="cl-f106e323"><p class="cl-f106ac55"><span class="cl-f101ed5e">468</span></p></td>
<td class="cl-f106e32c"><p class="cl-f106ac55"><span class="cl-f101ed5e">223</span></p></td>
<td class="cl-f106e32d"><p class="cl-f106ac55"><span class="cl-f101ed5e">43</span></p></td>
<td class="cl-f106e336"><p class="cl-f106ac55"><span class="cl-f101ed5e">553</span></p></td>
<td class="cl-f106e340"><p class="cl-f106ac55"><span class="cl-f101ed5e">125</span></p></td>
<td class="cl-f106e34a"><p class="cl-f106ac55"><span class="cl-f101ed5e">1,557</span></p></td>
</tr>
</tbody>
</table></div>
</div>
<p>Tabel silang yang merupakan hasil dari <em>script</em> di atas adalah seperti berikut.</p>
<ul>
<li>Baris menunjukkan kategori dalam variabel <code>kendaraan utama</code> (<code>row = `kendaraan utama`</code>)</li>
<li>Kolom menunjukkan kategori dalam variabel <code>jenis tempat tinggal</code> (<code>col = `jenis tempat tinggal`</code>)</li>
<li>Nilai-nilai dalam sel-selnya adalah frekuensi/jumlah data yang termasuk ke dalam kondisi berupa kategori kedua variabel.</li>
</ul>
<p>Sementara itu, maksud perintah yang dituliskan di dalam <em>chunk</em> di atas adalah:</p>
<ul>
<li>
<code>percent = "none"</code> digunakan untuk menghilangkan persentase dari tabel silang.</li>
<li>
<code>label = list(...)</code> digunakan untuk mengubah nama variabel yang akan ditampilkan di tabel silang.</li>
</ul>
<p>Perhatikan cara menginterpretasi informasi dari tabel tersebut:</p>
<ul>
<li><p>jumlah pengguna <strong>layanan online</strong> yang tinggal di <strong>kos bersama-sama</strong> adalah <strong>19 orang</strong>, yang setara dengan <strong>16%</strong>.</p></li>
<li><p>tidak ada pengguna <strong>sepeda</strong> yang tinggal di <strong>Asrama</strong>, <strong>Kos bersama-sama</strong>, atau <strong>mengontrak rumah secara pribadi</strong>. Keberadaannya juga langka pada kalangan mahasiswa yang tinggal di <strong>rumah pribadi</strong> atau di <strong>saudaranya</strong>.</p></li>
</ul>
<p>Selain dengan <code><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_cross.html">tbl_cross()</a></code> (atau <code><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html">tbl_summary()</a></code> yang kita gunakan di praktikum sebelumnya) yang gunanya cenderung untuk presentasi, kita dapat menggunakan perintah <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> untuk menghasilkan tabel silang yang siap dioperasikan ke dalam perhitungan koefisien korelasi di tahap selanjutnya. Perintah <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> mengambil dua masukan, yakni vektor variabel-variabel yang kita akan analisis, dipisahkan dengan tanda koma (<code>,</code>).</p>
<div class="sourceCode" id="cb257"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># vektor variabel-variabel ini kita akses dari dataset menggunakan operator '$'</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span></span>
<span>  <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`jenis tempat tinggal`</span>,</span>
<span>  <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`kendaraan utama`</span></span>
<span><span class="op">)</span></span>
<span><span class="co">##                           </span></span>
<span><span class="co">##                            Berjalan kaki Layanan online</span></span>
<span><span class="co">##   Asrama                              23              0</span></span>
<span><span class="co">##   Kos bersama-sama                    20             19</span></span>
<span><span class="co">##   Kos sendiri                         39             86</span></span>
<span><span class="co">##   Rumah mengontrak bersama            17             28</span></span>
<span><span class="co">##   Rumah mengontrak pribadi            11              6</span></span>
<span><span class="co">##   Rumah pribadi                        0             37</span></span>
<span><span class="co">##   Rumah saudara                        1             12</span></span>
<span><span class="co">##                           </span></span>
<span><span class="co">##                            Menumpang dengan teman/keluarga Mobil pribadi Sepeda</span></span>
<span><span class="co">##   Asrama                                                 0             0      0</span></span>
<span><span class="co">##   Kos bersama-sama                                      18             6      0</span></span>
<span><span class="co">##   Kos sendiri                                           24            15      8</span></span>
<span><span class="co">##   Rumah mengontrak bersama                              40             5      8</span></span>
<span><span class="co">##   Rumah mengontrak pribadi                               0             3      0</span></span>
<span><span class="co">##   Rumah pribadi                                         11           110      1</span></span>
<span><span class="co">##   Rumah saudara                                          4            13      1</span></span>
<span><span class="co">##                           </span></span>
<span><span class="co">##                            Sepeda motor pribadi</span></span>
<span><span class="co">##   Asrama                                      2</span></span>
<span><span class="co">##   Kos bersama-sama                           57</span></span>
<span><span class="co">##   Kos sendiri                               296</span></span>
<span><span class="co">##   Rumah mengontrak bersama                  125</span></span>
<span><span class="co">##   Rumah mengontrak pribadi                   23</span></span>
<span><span class="co">##   Rumah pribadi                             394</span></span>
<span><span class="co">##   Rumah saudara                              94</span></span></code></pre></div>
<div id="aktivitas-mandiri-1-2" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 1<a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-1-2"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li>Buatlah dataset <em>subset</em> dari <code>data_mahasiswa</code> untuk mahasiswa kampus ITERA saja dengan menggunakan perintah <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>! Simpan ke dalam variabel <code>data_itera</code>.</li>
<li>Buatlah tabel silang antara variabel <code>Tingkat Semester</code> dan <code>Uang Saku</code> dari dataset <em>subset</em> yang telah dibuat pada poin 1, baik dengan <code><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_cross.html">tbl_cross()</a></code> maupun dengan <code><a href="https://rdrr.io/r/base/table.html">table()</a></code>!</li>
</ol>
</div>
</div>
<div id="analisis-korelasi-antarvariabel-nominal" class="section level2" number="7.6">
<h2>
<span class="header-section-number">7.6</span> Analisis Korelasi Antarvariabel Nominal<a class="anchor" aria-label="anchor" href="#analisis-korelasi-antarvariabel-nominal"><i class="fas fa-link"></i></a>
</h2>
<p>Dalam analisis korelasi variabel nominal, kita mengukur <strong>keberadaan</strong> dan juga <strong>kekuatan hubungan</strong>. Ukuran yang kita pakai untuk menyatakan hal tersebut adalah <strong>koefisien korelasi variabel nominal</strong>, yang di antaranya adalah koefisien <span class="math inline">\(\phi\)</span> <strong>(phi)</strong>, <strong>V Cramer</strong> dan <strong>koefisien C</strong>. Ketiga koefisien tersebut dihitung dari nilai <span class="math inline">\(\chi^2\)</span> (“chi kuadrat”).</p>
<p>Selain itu, terdapat juga <span class="math inline">\(\lambda\)</span> <strong>(lambda)</strong> yang merupakan koefisien korelasi variabel nominal berbasis <em>error,</em> atau disebut juga PRE <em>(proportional reduction of error).</em></p>
<p>Ukuran dari keempat koefisien tersebut adalah besarnya yang berkisar <strong>antara 0 dan 1</strong> dengan <strong>0 berarti tidak ada hubungan sama sekali</strong> dan <strong>1 berarti hubungan yang ada sangat kuat.</strong></p>
<div id="koefisien-korelasi-variabel-nominal-berbasis-chi2" class="section level3" number="7.6.1">
<h3>
<span class="header-section-number">7.6.1</span> Koefisien Korelasi Variabel Nominal Berbasis <span class="math inline">\(\chi^2\)</span><a class="anchor" aria-label="anchor" href="#koefisien-korelasi-variabel-nominal-berbasis-chi2"><i class="fas fa-link"></i></a>
</h3>
<p>Perhitungan koefisien korelasi variabel nominal berbasis nilai <span class="math inline">\(\chi^2\)</span> pada praktikum ini kita lakukan dengan cara <em>semi-manual</em> seperti pada buku dan langsung menggunakan koefisien korelasi yang sudah tersedia pada paket-paket tambahan yang pada bagian pertama kita muat.</p>
<div id="cara-semi-manual" class="section level4" number="7.6.1.1">
<h4>
<span class="header-section-number">7.6.1.1</span> Cara <em>Semi-Manual</em><a class="anchor" aria-label="anchor" href="#cara-semi-manual"><i class="fas fa-link"></i></a>
</h4>
<p>Cara semi-manual ini dilakukan dengan terlebih dahulu menghitung nilai <span class="math inline">\(\chi^2\)</span> antara dua variabel kita. Kemudian, dari nilai <span class="math inline">\(\chi^2\)</span> tersebut, kita menghitung koefisien korelasi variabel nominal yang kita inginkan.</p>
<p>Untuk menghitung <span class="math inline">\(\chi^2\)</span> kita menggunakan dua perintah utama dalam R, yakni <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> dan <code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code>. Perintah <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> berfungsi membuat tabel silang yang berguna sebagai “bahan baku” perhitungan <span class="math inline">\(\chi^2\)</span> kita, kemudian perintah <code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code> menghitung nilai <span class="math inline">\(\chi^2\)</span> tersebut.</p>
<div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menyimpan tabel</span></span>
<span><span class="va">tempat_tinggal_kend</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span></span>
<span>  <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`kendaraan utama`</span>,</span>
<span>  <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`jenis tempat tinggal`</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menyimpan hasil chi-square test</span></span>
<span><span class="va">chisq_tempat_tinggal_kend</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">tempat_tinggal_kend</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>Seperti yang bisa kita lihat, hasil perhitungan berupa variabel R <code>chisq_tempat_tinggal_kend</code> berada di bagian data, dan jika kita perluas, maka di dalamnya terdapat banyak variabel-variabel lain. Variabel-variabel lain tersebut menyimpan berbagai nilai yang menjadi bagian dari hasil perhitungan. Nilai-nilai yang penting untuk</p>
<ul>
<li><p><code>.$statistic</code> menyimpan nilai <span class="math inline">\(\chi^2\)</span> dari tabel. Ini digunakan untuk menghitung kekuatan korelasi</p></li>
<li><p><code>.$parameter</code> menyimpan nilai <em>degree of freedom</em> (df)</p></li>
<li><p><code>.$p.value</code> menyimpan nilai probabilitas untuk menerima <span class="math inline">\(H_0\)</span> yang berarti tidak ada hubungan antara dua variabel yang dianalisis</p></li>
<li><p><code>.$expected</code> menyimpan tabel frekuensi yang diharapkan dari data kita</p></li>
</ul>
<p>Tampilkan seluruh nilai tersebut</p>
<div class="sourceCode" id="cb259"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menampilkan nilai chi-square</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Nilai Chi-square: "</span><span class="op">)</span></span>
<span><span class="va">chisq_tempat_tinggal_kend</span><span class="op">$</span><span class="va">statistic</span></span>
<span></span>
<span><span class="co"># Menampilkan nilai degree of freedom</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Nilai Degree of Freedom: "</span><span class="op">)</span></span>
<span><span class="va">chisq_tempat_tinggal_kend</span><span class="op">$</span><span class="va">parameter</span></span>
<span></span>
<span><span class="co"># Menampilkan nilai probabilitas</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Nilai Probabilitas: "</span><span class="op">)</span></span>
<span><span class="va">chisq_tempat_tinggal_kend</span><span class="op">$</span><span class="va">p.value</span></span>
<span></span>
<span><span class="co"># Menampilkan tabel frekuensi yang diharapkan</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Tabel Frekuensi yang Diharapkan: "</span><span class="op">)</span></span>
<span><span class="va">chisq_tempat_tinggal_kend</span><span class="op">$</span><span class="va">expected</span></span>
<span><span class="co">## Nilai Chi-square: X-squared </span></span>
<span><span class="co">##  600.8622 </span></span>
<span><span class="co">## Nilai Degree of Freedom: df </span></span>
<span><span class="co">## 30 </span></span>
<span><span class="co">## Nilai Probabilitas: [1] 1.963807e-107</span></span>
<span><span class="co">## Tabel Frekuensi yang Diharapkan:                                  </span></span>
<span><span class="co">##                                       Asrama Kos bersama-sama Kos sendiri</span></span>
<span><span class="co">##   Berjalan kaki                    1.7822736         8.554913   33.364162</span></span>
<span><span class="co">##   Layanan online                   3.0186256        14.489403   56.508671</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga  1.5574823         7.475915   29.156069</span></span>
<span><span class="co">##   Mobil pribadi                    2.4405909        11.714836   45.687861</span></span>
<span><span class="co">##   Sepeda                           0.2890173         1.387283    5.410405</span></span>
<span><span class="co">##   Sepeda motor pribadi            15.9120103        76.377649  297.872832</span></span>
<span><span class="co">##                                  </span></span>
<span><span class="co">##                                   Rumah mengontrak bersama</span></span>
<span><span class="co">##   Berjalan kaki                                  15.897881</span></span>
<span><span class="co">##   Layanan online                                 26.926140</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga                13.892742</span></span>
<span><span class="co">##   Mobil pribadi                                  21.770071</span></span>
<span><span class="co">##   Sepeda                                          2.578035</span></span>
<span><span class="co">##   Sepeda motor pribadi                          141.935132</span></span>
<span><span class="co">##                                  </span></span>
<span><span class="co">##                                   Rumah mengontrak pribadi Rumah pribadi</span></span>
<span><span class="co">##   Berjalan kaki                                  3.0655106     39.423892</span></span>
<span><span class="co">##   Layanan online                                 5.1920360     66.771997</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga                2.6788696     34.451509</span></span>
<span><span class="co">##   Mobil pribadi                                  4.1978163     53.985870</span></span>
<span><span class="co">##   Sepeda                                         0.4971098      6.393064</span></span>
<span><span class="co">##   Sepeda motor pribadi                          27.3686577    351.973667</span></span>
<span><span class="co">##                                  </span></span>
<span><span class="co">##                                   Rumah saudara</span></span>
<span><span class="co">##   Berjalan kaki                        8.911368</span></span>
<span><span class="co">##   Layanan online                      15.093128</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga      7.787412</span></span>
<span><span class="co">##   Mobil pribadi                       12.202954</span></span>
<span><span class="co">##   Sepeda                               1.445087</span></span>
<span><span class="co">##   Sepeda motor pribadi                79.560051</span></span></code></pre></div>
<p>Kita akan menghitung nilai koefisien V Cramer untuk menyatakan korelasi antara jenis kendaraan yang digunakan sebagai moda ke kampus dan jenis tempat tinggal mahasiswa menggunakan rumus berikut dan berdasarkan nilai <span class="math inline">\(\chi^2\)</span> yang kita dapatkan dari tes sebelumnya.</p>
<p><span class="math display">\[
V = \sqrt{\frac{\chi^2}{n \times min(c−1,r−1)}}
\]</span></p>
<div class="sourceCode" id="cb260"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menyimpan nilai Chi-squared menggunakan metode "as.numeric"</span></span>
<span><span class="va">chisq_tempat_tinggal_kend</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">chisq_tempat_tinggal_kend</span><span class="op">$</span><span class="va">statistic</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menghitung jumlah data</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="va">n</span><span class="op">$</span><span class="va">jumlah</span></span>
<span></span>
<span><span class="co"># Menghitung jumlah kategori dari 'jenis tempat tinggal' sebagai jumlah kolom</span></span>
<span><span class="va">kolom</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>jenis <span class="op">=</span> <span class="va">`jenis tempat tinggal`</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">kolom</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">kolom</span><span class="op">$</span><span class="va">jenis</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menghitung jumlah kategori dari 'kendaraan utama' sebagai jumlah baris</span></span>
<span><span class="va">baris</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span>kend <span class="op">=</span> <span class="va">`kendaraan utama`</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>jumlah <span class="op">=</span> <span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">baris</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">baris</span><span class="op">$</span><span class="va">kend</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menghitung koefisien V</span></span>
<span><span class="va">v_tempat_tinggal_kend</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">chisq_tempat_tinggal_kend</span> <span class="op">/</span> <span class="op">(</span><span class="va">n</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">kolom</span> <span class="op">-</span> <span class="fl">1</span>, <span class="va">baris</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">v_tempat_tinggal_kend</span></span></code></pre></div>
<pre><code>## [1] 0.2778166</code></pre>
<p>Koefisien V dipilih karena tabel silang kita terdiri atas banyak kategori dan juga berdimensi persegi panjang (6x7 kategori).</p>
<p><strong>Kesimpulan:</strong> Hasil dari perhitungan koefisien V adalah <strong>0.2778166</strong>. Angka ini menunjukkan hubungan yang sedikit lemah, karena berada di bawah nilai tengah-tengah yaitu 0,5. Artinya, hubungan antara jenis tempat tinggal dengan jenis kendaraan yang sering digunakan ke kampus tidak begitu kuat.</p>
</div>
<div id="cara-langsung-dengan-pustaka-rcompanion" class="section level4" number="7.6.1.2">
<h4>
<span class="header-section-number">7.6.1.2</span> Cara Langsung dengan Pustaka <code>rcompanion</code><a class="anchor" aria-label="anchor" href="#cara-langsung-dengan-pustaka-rcompanion"><i class="fas fa-link"></i></a>
</h4>
<p>kita dapat menggunakan pustaka <code>rcompanion</code> untuk menghitung koefisien V Cramer, yaitu dengan perintah <code><a href="https://rdrr.io/pkg/rcompanion/man/cramerV.html">cramerV()</a></code>. Perintah ini mengambil langsung vektor kolom variabel yang kita akan analisis, sehingga menggunakan notasi <code>$</code> untuk mengakses kolom <code>`jenis tempat tinggal`</code> dan <code>`kendaraan utama`</code>.</p>
<div class="rmdnote">
<p>Untuk menggunakan koefisien <span class="math inline">\(\phi\)</span> kita dapat menggunakan perintah <code><a href="https://rdrr.io/pkg/rcompanion/man/phi.html">phi()</a></code>. Sementara itu, untuk koefisien kontingensi <span class="math inline">\(C\)</span> kita dapat menggunakan perintah <code>ContCoeff()</code> yang membutuhkan pustaka <code>DescTools</code>.</p>
</div>
<div class="sourceCode" id="cb262"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">v_tempat_tinggal_kend</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/rcompanion/man/cramerV.html">cramerV</a></span><span class="op">(</span></span>
<span>  <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`jenis tempat tinggal`</span>, <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`kendaraan utama`</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span></span>
<span>  <span class="st">"Nilai V Cramer variabel jenis tempat tinggal"</span>,</span>
<span>  <span class="st">"dengan kendaraan utama: "</span>,</span>
<span>  <span class="va">v_tempat_tinggal_kend</span></span>
<span><span class="op">)</span></span>
<span><span class="co">## Nilai V Cramer variabel jenis tempat tinggal dengan kendaraan utama:  0.2778</span></span></code></pre></div>
<p>Bandingkan dengan nilai V dari perhitungan semi-manual, apakah hasilnya sama?</p>
</div>
</div>
<div id="aktivitas-mandiri-2-2" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 2<a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-2-2"><i class="fas fa-link"></i></a>
</h3>
<p>Analisislah korelasi antara variabel <code>jenis tempat tinggal</code> dengan <code>kendaraan utama</code> dari dataset <code>data_itera</code> menggunakan koefisien korelasi berbasis <span class="math inline">\(\chi^2\)</span> dan simpan ke dalam variabel <code>v_itera_tempat_tinggal_kendaraan</code>.</p>
</div>
<div id="koefisien-korelasi-variabel-nominal-berbasis-error" class="section level3" number="7.6.2">
<h3>
<span class="header-section-number">7.6.2</span> Koefisien Korelasi Variabel Nominal Berbasis <em>Error</em><a class="anchor" aria-label="anchor" href="#koefisien-korelasi-variabel-nominal-berbasis-error"><i class="fas fa-link"></i></a>
</h3>
<p>Untuk analisis korelasi variabel nominal berbasis <em>error</em> yang menggunakan koefisien <span class="math inline">\(\lambda\)</span> kita dapat menggunakan perintah <code><a href="https://rdrr.io/pkg/RCPA3/man/lambda.html">lambda()</a></code> yang ada di dalam pustaka <code>RCPA3</code>. Perintah <code><a href="https://rdrr.io/pkg/RCPA3/man/lambda.html">lambda()</a></code> mengambil masukan berupa tabel silang seperti yang kita buat pada perhitungan <span class="math inline">\(\chi^2\)</span>, yakni perintah <code><a href="https://rdrr.io/r/base/table.html">table()</a></code>. Karena koefisien <span class="math inline">\(\lambda\)</span> merupakan koefisien korelasi variabel nominal yang memperhitungkan variabel independen, penentuan variabel yang menjadi independen dilakukan <strong>sejak kita memformat tabel silang</strong>, yakni <strong>variabel dependen ditempatkan pada baris</strong> dan <strong>independen pada kolom</strong>. Untuk memastikan, mari kita muat ulang tabel silang kita dengan memanggil kembali nama variabelnya.</p>
<div class="sourceCode" id="cb263"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">tempat_tinggal_kend</span><span class="op">)</span></span>
<span><span class="co">##                                  </span></span>
<span><span class="co">##                                   Asrama Kos bersama-sama Kos sendiri</span></span>
<span><span class="co">##   Berjalan kaki                       23               20          39</span></span>
<span><span class="co">##   Layanan online                       0               19          86</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga      0               18          24</span></span>
<span><span class="co">##   Mobil pribadi                        0                6          15</span></span>
<span><span class="co">##   Sepeda                               0                0           8</span></span>
<span><span class="co">##   Sepeda motor pribadi                 2               57         296</span></span>
<span><span class="co">##                                  </span></span>
<span><span class="co">##                                   Rumah mengontrak bersama</span></span>
<span><span class="co">##   Berjalan kaki                                         17</span></span>
<span><span class="co">##   Layanan online                                        28</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga                       40</span></span>
<span><span class="co">##   Mobil pribadi                                          5</span></span>
<span><span class="co">##   Sepeda                                                 8</span></span>
<span><span class="co">##   Sepeda motor pribadi                                 125</span></span>
<span><span class="co">##                                  </span></span>
<span><span class="co">##                                   Rumah mengontrak pribadi Rumah pribadi</span></span>
<span><span class="co">##   Berjalan kaki                                         11             0</span></span>
<span><span class="co">##   Layanan online                                         6            37</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga                        0            11</span></span>
<span><span class="co">##   Mobil pribadi                                          3           110</span></span>
<span><span class="co">##   Sepeda                                                 0             1</span></span>
<span><span class="co">##   Sepeda motor pribadi                                  23           394</span></span>
<span><span class="co">##                                  </span></span>
<span><span class="co">##                                   Rumah saudara</span></span>
<span><span class="co">##   Berjalan kaki                               1</span></span>
<span><span class="co">##   Layanan online                             12</span></span>
<span><span class="co">##   Menumpang dengan teman/keluarga             4</span></span>
<span><span class="co">##   Mobil pribadi                              13</span></span>
<span><span class="co">##   Sepeda                                      1</span></span>
<span><span class="co">##   Sepeda motor pribadi                       94</span></span></code></pre></div>
<p>Ternyata kita sudah mengatur sedemikian rupa agar variabel independen kita, <code>jenis tempat tinggal</code>, berada di kolom. Artinya, urutan kita menempatkan variabel di argumen <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> sangat berpengaruh: <strong>variabel pertama akan menempati baris</strong>, sementara <strong>yang kedua menempati kolom</strong>. Karena susunan ini sudah sesuai dengan perintah <code><a href="https://rdrr.io/pkg/RCPA3/man/lambda.html">lambda()</a></code>, kita bisa melanjutkan analisis kita.</p>
<div class="sourceCode" id="cb264"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menghitung koefisien lambda</span></span>
<span><span class="va">lambda_tempat_tinggal_kend</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/RCPA3/man/lambda.html">lambda</a></span><span class="op">(</span></span>
<span>  <span class="va">tempat_tinggal_kend</span>,</span>
<span>  <span class="co"># digits menandakan berapa desimal angka yang kita hasilkan</span></span>
<span>  digits <span class="op">=</span> <span class="fl">3</span>,</span>
<span>  <span class="co"># detailed menandakan apakah kita memperlihatkan nilai-nilai error yang dihitung</span></span>
<span>  detailed <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">lambda_tempat_tinggal_kend</span></span></code></pre></div>
<pre><code>##   Naive Errors Prediction Errors Lambda
## 1          566               545  0.037</code></pre>
<p>Nilai 566, 545, 0.037 ini menunjukkan bahwa dengan mempertimbangkan variabel independen berupa <code>jenis tempat tinggal</code>, error dalam memprediksi variabel dependen berupa <code>kendaraan utama</code> berkurang sebesar 5.66^{4}, 5.45^{4}, 3.7%, yang mana bukan angka yang signifikan besarnya. Artinya, hubungan antara jenis kendaraan dengan jenis tempat tinggal yang kita analisis sangat-sangat lemah.</p>
</div>
<div id="aktivitas-mandiri-3-2" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 3<a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-3-2"><i class="fas fa-link"></i></a>
</h3>
<p>Analisislah korelasi antara variabel <code>jenis tempat tinggal</code> dengan <code>kendaraan utama</code> dari dataset <code>data_itera</code> menggunakan koefisien korelasi <span class="math inline">\(\lambda\)</span> dan simpan ke dalam variabel <code>lambda_itera_tempat_tinggal_kendaraan</code>.</p>
</div>
</div>
<div id="analisis-korelasi-antarvariabel-ordinal" class="section level2" number="7.7">
<h2>
<span class="header-section-number">7.7</span> Analisis Korelasi Antarvariabel Ordinal<a class="anchor" aria-label="anchor" href="#analisis-korelasi-antarvariabel-ordinal"><i class="fas fa-link"></i></a>
</h2>
<p>Dalam analisis korelasi variabel ordinal, kita tidak hanya dapat mengukur keberadaan dan juga kekuatan hubungan, tetapi juga <strong>arah hubungan</strong>. Yang dimaksud dengan ‘arah hubungan’ adalah <strong>searah</strong> atau <strong>berlawanan</strong>. Hubungan searah berarti semakin tinggi nilai variabel #1, maka semakin tinggi juga nilai variabel #2, begitu pula sebaliknya. Akan tetapi, jika arah hubungan berlawanan, semakin tinggi nilai variabel #1 maka semakin rendah nilai variabel #2, begitu pula sebaliknya.</p>
<p>Arah hubungan ditunjukkan oleh <strong>tanda koefisien</strong> dan kekuatannya ditunjukkan oleh <strong>besar angka koefisien.</strong> Oleh karena itu, nilai korelasi pada variabel ordinal berkisar antara <span class="math inline">\(-1\)</span> hingga <span class="math inline">\(+1\)</span> dengan tanda <span class="math inline">\(-\)</span> untuk menandakan hubungan berlawanan dan <span class="math inline">\(+\)</span> untuk hubungan searah.</p>
<p>Kita akan mempelajari penggunaan perintah dalam R untuk menghitung koefisien korelasi Gamma (<span class="math inline">\(\gamma\)</span>) dan Somer’s d.</p>
<div id="koefisien-gamma-gamma" class="section level3" number="7.7.1">
<h3>
<span class="header-section-number">7.7.1</span> Koefisien Gamma (<span class="math inline">\(\gamma\)</span>)<a class="anchor" aria-label="anchor" href="#koefisien-gamma-gamma"><i class="fas fa-link"></i></a>
</h3>
<p>Kita dapat menggunakan perintah <code><a href="https://friendly.github.io/vcdExtra/reference/GKgamma.html">GKgamma()</a></code> dari pustaka <code>vcdExtra</code> untuk mengukur koefisien (<span class="math inline">\(\gamma\)</span>). Perintah <code><a href="https://friendly.github.io/vcdExtra/reference/GKgamma.html">GKgamma()</a></code> mengambil masukan yang sama seperti <code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code>, yakni tabel silang yang dihasilkan dari perintah <code><a href="https://rdrr.io/r/base/table.html">table()</a></code>.</p>
<p>Dalam praktikum ini, kita akan menganalisis kekuatan dan arah hubungan antara variabel <code>Uang Saku</code> dan <code>Tingkat Semester</code>. Apakah mahasiswa dengan tingkat semester makin tinggi uang sakunya makin tinggi pula, atau sebaliknya?</p>
<div class="sourceCode" id="cb266"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Membuat variabel table() sebagai masukan</span></span>
<span><span class="va">uang_saku_tingkat_semester</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span></span>
<span>  <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`Uang Saku`</span>,</span>
<span>  <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`Tingkat Semester`</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menghitung nilai Gamma dari variabel table() yang sudah dibuat</span></span>
<span><span class="va">gamma_uang_saku_tingkat_semester</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://friendly.github.io/vcdExtra/reference/GKgamma.html">GKgamma</a></span><span class="op">(</span><span class="va">uang_saku_tingkat_semester</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menampilkan nilai Gamma</span></span>
<span><span class="va">gamma_uang_saku_tingkat_semester</span></span>
<span><span class="co">## gamma        : -0.009 </span></span>
<span><span class="co">## std. error   : 0.033 </span></span>
<span><span class="co">## CI           : -0.073 0.056</span></span></code></pre></div>
<p>Nilai <span class="math inline">\(\gamma\)</span> sebesar -0.008545 menunjukkan bahwa kekuatan hubungan antara uang saku dengan tingkat semester adalah sangat-sangat lemah.</p>
<p>Seperti halnya nilai variabel hasil perhitungan <code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code>, hasil perhitungan <code><a href="https://friendly.github.io/vcdExtra/reference/GKgamma.html">GKgamma()</a></code> juga terdiri atas banyak variabel. Nilai gamma sendiri dapat kita akses dengan <code>.$gamma</code>. Walaupun ada tanda negatif pada nilai tersebut yang artinya adalah ada hubungan berlawanan arah antara tingkat uang saku dengan tingkat semester. Semakin tinggi semester, semakin rendah uang saku yang diterima mahasiswa. Akan tetapi, pernyataan itu tidak bisa dijadikan pegangan karena besar nilai koefisiennya yang sangat kecil.</p>
<div class="sourceCode" id="cb267"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mengakses nilai gamma</span></span>
<span><span class="va">gamma_uang_saku_tingkat_semester</span><span class="op">$</span><span class="va">gamma</span></span>
<span><span class="co">## [1] -0.008545005</span></span></code></pre></div>
<p>Nilai lain yang penting bagi kita adalah nilai <code>.$C</code> dan <code>.$D</code> . Nilai-nilai tersebut adalah nilai operasi dalam sel tabel silang yang merupakan penyusun dalam perhitungan koefisien tersebut mengikuti rumus berikut:</p>
<p><span class="math display">\[
G = \frac{C-D}{C+D}
\]</span></p>
<div class="sourceCode" id="cb268"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menampilkan nilai C dan D</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">gamma_uang_saku_tingkat_semester</span><span class="op">$</span><span class="va">C</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">gamma_uang_saku_tingkat_semester</span><span class="op">$</span><span class="va">D</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 283397
## [1] 288282</code></pre>
</div>
<div id="koefisien-somers-d" class="section level3" number="7.7.2">
<h3>
<span class="header-section-number">7.7.2</span> Koefisien Somer’s d<a class="anchor" aria-label="anchor" href="#koefisien-somers-d"><i class="fas fa-link"></i></a>
</h3>
<p>Koefisien Somer’s d menghitung korelasi dengan mempertimbangkan salah satunya sebagai variabel independen. Oleh karena itu, kita perlu menentukan variabel mana yang menjadi independen dan mana yang menjadi dependen. Dalam praktikum ini, kita akan menganalisis hubungan antara variabel <code>Uang Saku</code> dan <code>Tingkat Semester</code>. Kita akan menentukan bahwa <code>Tingkat Semester</code> sebagai variabel independen dan <code>Uang Saku</code> sebagai variabel dependen karena lebih masuk akal bahwa tingkat semester mempengaruhi uang saku, bukan sebaliknya.</p>
<div class="sourceCode" id="cb270"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menetapkan variabel dependen dan independen</span></span>
<span><span class="co"># Variabel dependen kita sebut 'y', independen kita sebut 'x'</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`Tingkat Semester`</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">data_mahasiswa</span><span class="op">$</span><span class="va">`Uang Saku`</span></span>
<span></span>
<span><span class="co"># Menghitung koefisien d Somer</span></span>
<span><span class="va">somerd_uang_saku_tingkat_semester</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://andrisignorell.github.io/DescTools/reference/SomersDelta.html">SomersDelta</a></span><span class="op">(</span></span>
<span>  <span class="va">x</span>, <span class="va">y</span>, direction <span class="op">=</span> <span class="st">"column"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">somerd_uang_saku_tingkat_semester</span></span>
<span><span class="co">## [1] -0.005806946</span></span></code></pre></div>
<p>Perintah tersebut menghitung koefisien d Somer dengan variabel independen yang berada pada kolom (<code>direction = "column"</code>). Secara bawaan, fungsi <code><a href="https://andrisignorell.github.io/DescTools/reference/SomersDelta.html">SomersDelta()</a></code> menganggap variabel independen berada pada baris (<code>direction = "row"</code>). Jika kita mendefinisikan variabel x dan y secara bersamaan, kita harus mendefinisikan <code>direction = "column"</code> secara eksplisit.</p>
<p>Nilai koefisien d Somer tersebut juga menunjukkan kesimpulan yang sama dengan koefisien <span class="math inline">\(\gamma\)</span>.</p>
</div>
<div id="aktivitas-mandiri-4-2" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 4<a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-4-2"><i class="fas fa-link"></i></a>
</h3>
<p>Hitunglah korelasi antara <code>Tingkat Semester</code> dan <code>Uang Saku</code> pada dataset <code>data_itera</code> menggunakan koefisien <span class="math inline">\(\gamma\)</span> dan d Somer. Simpan kedua variabel berturut-turut pada <code>gamma_lat_itera</code> dan <code>somerd_lat_itera</code>.</p>
</div>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="uji-hipotesis-dua-populasi.html"><span class="header-section-number">6</span> Uji Hipotesis Dua Populasi</a></div>
<div class="next"><a href="analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><span class="header-section-number">8</span> Analisis Hubungan Korelatif: Korelasi Variabel Metrik</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal"><span class="header-section-number">7</span> Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal</a></li>
<li><a class="nav-link" href="#pendahuluan-2"><span class="header-section-number">7.1</span> Pendahuluan</a></li>
<li><a class="nav-link" href="#pustaka-libraries-yang-diperlukan"><span class="header-section-number">7.2</span> Pustaka (Libraries) yang Diperlukan</a></li>
<li><a class="nav-link" href="#memuat-dataset-3"><span class="header-section-number">7.3</span> Memuat Dataset</a></li>
<li><a class="nav-link" href="#mengatur-faktor-untuk-variabel-kategoris"><span class="header-section-number">7.4</span> Mengatur Faktor untuk Variabel Kategoris</a></li>
<li>
<a class="nav-link" href="#pembuatan-tabel-silang"><span class="header-section-number">7.5</span> Pembuatan Tabel Silang</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#aktivitas-mandiri-1-2">Aktivitas Mandiri 1</a></li></ul>
</li>
<li>
<a class="nav-link" href="#analisis-korelasi-antarvariabel-nominal"><span class="header-section-number">7.6</span> Analisis Korelasi Antarvariabel Nominal</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#koefisien-korelasi-variabel-nominal-berbasis-chi2"><span class="header-section-number">7.6.1</span> Koefisien Korelasi Variabel Nominal Berbasis \(\chi^2\)</a></li>
<li><a class="nav-link" href="#aktivitas-mandiri-2-2">Aktivitas Mandiri 2</a></li>
<li><a class="nav-link" href="#koefisien-korelasi-variabel-nominal-berbasis-error"><span class="header-section-number">7.6.2</span> Koefisien Korelasi Variabel Nominal Berbasis Error</a></li>
<li><a class="nav-link" href="#aktivitas-mandiri-3-2">Aktivitas Mandiri 3</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#analisis-korelasi-antarvariabel-ordinal"><span class="header-section-number">7.7</span> Analisis Korelasi Antarvariabel Ordinal</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#koefisien-gamma-gamma"><span class="header-section-number">7.7.1</span> Koefisien Gamma (\(\gamma\))</a></li>
<li><a class="nav-link" href="#koefisien-somers-d"><span class="header-section-number">7.7.2</span> Koefisien Somer’s d</a></li>
<li><a class="nav-link" href="#aktivitas-mandiri-4-2">Aktivitas Mandiri 4</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Modul Praktik Statistika Untuk Perencanaan</strong>: Penggunaan R dalam Pengolahan Data Kuantitatif" was written by Team Teaching Statistika Untuk Perencanaan, PWK ITERA. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
