<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Modul 1 Pengolahan Data Terstruktur | Modul Praktik Statistika Untuk Perencanaan</title>
<meta name="author" content="Team Teaching Statistika Untuk Perencanaan, PWK ITERA">
<meta name="generator" content="bookdown 0.46 with bs4_book()">
<meta property="og:title" content="Modul 1 Pengolahan Data Terstruktur | Modul Praktik Statistika Untuk Perencanaan">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Modul 1 Pengolahan Data Terstruktur | Modul Praktik Statistika Untuk Perencanaan">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="libs/tabwid-1.1.3/tabwid.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
<meta name="description" content="Setelah mempelajari modul ini Anda diharapkan dapat: 1. menganalisis variabel dan objek dalam sebuah format data terstruktur STP-1.3 2. mengelola data terstruktur dengan tepat menggunakan...">
<meta property="og:description" content="Setelah mempelajari modul ini Anda diharapkan dapat: 1. menganalisis variabel dan objek dalam sebuah format data terstruktur STP-1.3 2. mengelola data terstruktur dengan tepat menggunakan...">
<meta name="twitter:description" content="Setelah mempelajari modul ini Anda diharapkan dapat: 1. menganalisis variabel dan objek dalam sebuah format data terstruktur STP-1.3 2. mengelola data terstruktur dengan tepat menggunakan...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Penggunaan R dalam Pengolahan Data Kuantitatif">Modul Praktik Statistika Untuk Perencanaan</a>:
        <small class="text-muted">Penggunaan R dalam Pengolahan Data Kuantitatif</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Pengantar</a></li>
<li><a class="" href="pengenalan-r-dan-rstudio.html">Pengenalan R dan RStudio</a></li>
<li><a class="" href="pengenalan-teknis-r.html">Pengenalan Teknis R</a></li>
<li><a class="active" href="modul-1.html"><span class="header-section-number">1</span> Pengolahan Data Terstruktur</a></li>
<li><a class="" href="analisis-statistika-deskriptif.html"><span class="header-section-number">2</span> Analisis Statistika Deskriptif</a></li>
<li><a class="" href="visualisasi-data-kuantitatif.html"><span class="header-section-number">3</span> Visualisasi Data Kuantitatif</a></li>
<li><a class="" href="distribusi-sampling-dan-interval-kepercayaan.html"><span class="header-section-number">4</span> Distribusi Sampling dan Interval Kepercayaan</a></li>
<li><a class="" href="uji-hipotesis-satu-populasi.html"><span class="header-section-number">5</span> Uji Hipotesis Satu Populasi</a></li>
<li><a class="" href="uji-hipotesis-dua-populasi.html"><span class="header-section-number">6</span> Uji Hipotesis Dua Populasi</a></li>
<li><a class="" href="analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><span class="header-section-number">7</span> Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal</a></li>
<li><a class="" href="analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><span class="header-section-number">8</span> Analisis Hubungan Korelatif: Korelasi Variabel Metrik</a></li>
<li><a class="" href="analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><span class="header-section-number">9</span> Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda</a></li>
<li><a class="" href="analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><span class="header-section-number">10</span> Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA</a></li>
<li><a class="" href="referensi.html"><span class="header-section-number">11</span> Referensi</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="modul-1" class="section level1" number="1">
<h1>
<span class="header-section-number">Modul 1</span> Pengolahan Data Terstruktur<a class="anchor" aria-label="anchor" href="#modul-1"><i class="fas fa-link"></i></a>
</h1>
<div class="rmdcapaian">
<p>Setelah mempelajari modul ini Anda diharapkan dapat:</p>
<p><strong>1. menganalisis variabel dan objek dalam sebuah format data terstruktur</strong> <span class="capaian">STP-1.3</span>
<strong>2. mengelola data terstruktur dengan tepat menggunakan perangkat komputer</strong> <span class="capaian">STP-1.4</span></p>
</div>
<p>Kita akan mempelajari cara pengolahan data terstruktur atau <em>dataset</em>/set data dari hasil kuesioner kepada mahasiswa-mahasiswa Universitas Islam Negeri Raden Intan Lampung (UINRIL) dan Universitas Bandar Lampung (UBL) tentang pola perjalanan mereka.</p>
<p>Dalam R, pengolahan data terstruktur dipermudah dengan adanya paket <code>tidyverse</code>. Paket ini menyertakan paket-paket lain yang mempunyai kegunaan unik dalam pengolahan data terstruktur.</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code></pre></div>
<p>Seperti yang kalian lihat, paket <code>tidyverse</code> menyertakan paket-paket berikut yang mempunyai kegunaan masing-masing:</p>
<ul>
<li>
<code>dplyr</code>: menyediakan serangkaian fungsi inti untuk memanipulasi dan mentransformasi data secara efisien.</li>
<li>
<code>forcats</code>: memudahkan pekerjaan dengan data kategorikal atau yang dalam R disebut juga ‘factors’.</li>
<li>
<code>ggplot2</code>: untuk membuat grafik yang ciamik.</li>
<li>
<code>lubridate</code>: mempermudah pekerjaan terkait format tanggal</li>
<li>
<code>purrr</code>: meningkatkan kemampuan pemrograman fungsi dan vektor</li>
<li>
<code>readr</code>: untuk membaca data tabular seperti <code>.csv</code>
</li>
<li>
<code>stringr</code>: menyederhanakan operasi teks/<em>string</em>
</li>
<li>
<code>tibble</code>: versi modern dari <em>data.frame</em> yang lebih rapi dan mudah digunakan.</li>
<li>
<code>tidyr</code>: untuk merapikan data dengan mengubah format atau struktur tata letaknya.</li>
</ul>
<p>Selain paket <code>tidyverse</code>, kita juga akan menggunakan paket <code>openxlsx</code> untuk mengoperasikan <em>file</em> Excel.</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ycphs.github.io/openxlsx/index.html">openxlsx</a></span><span class="op">)</span></span></code></pre></div>
<div id="mengimpor-set-data-dataset-dari-excel" class="section level2" number="1.1">
<h2>
<span class="header-section-number">1.1</span> Mengimpor set data <em>(dataset)</em> dari Excel<a class="anchor" aria-label="anchor" href="#mengimpor-set-data-dataset-dari-excel"><i class="fas fa-link"></i></a>
</h2>
<p>Untuk membuat set data di lingkungan kerja R kita, gunakan fungsi <code><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx()</a></code> seperti berikut. Fungsi <code><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx()</a></code> mempunyai atribut utama berupa <em>file path</em> lokasi file yang ditempatkan di dalam tanda kurung.</p>
<div class="rmdwarning">
<p>⚠️ <strong>Penting</strong></p>
<p>Pastikan file Excel yang akan diimpor sudah tertutup, karena mengimpor file yang sedang terbuka akan menghasilkan <em>error</em>.</p>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Memuat dataset dari file Excel "Data Praktikum 01.xlsx" yang terletak di folder datasets/</span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx</a></span><span class="op">(</span><span class="st">"datasets/Data Praktikum 01.xlsx"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Menampilkan 6 baris pertama dataset</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   Kampus_PT Nomor.urut Jenis.Kelamin Umur Fakultas          Prodi            Tingkat.Semester  Uang.Saku kepemilikan.mobil
## 1    UINRIL          1     Laki-laki   22  Syariah Hukum Keluarga 4 (Semester 7 - Semester 8) 1Jt - 2 Jt                 0
## 2    UINRIL          2     Laki-laki   25  Syariah Hukum Keluarga 4 (Semester 7 - Semester 8)     &lt; 1 Jt                 1
##   kepemilikan.motor kepemilikan.sepedan      kendaraan.utama kelurahan  jenis.tempat.tinggal nama.jalan.tempat.tinggal
## 1                 1                   0 Sepeda Motor Pribadi    Wiyono Rumah Bersama Saudara              Pasar Wiyono
## 2                 4                   0 Sepeda Motor Pribadi  Sukarame           Kos Sendiri       jln endro suratmin 
##   alasan.pemilihan.lokasi.tempat.tinggal jarak.(km) biaya.dalam.ribu2 Jumlah.Perjalanan.Senin Jumlah.Perjalanan.Selasa
## 1                              Lain-lain      19.27               100                       3                        3
## 2                    Dekat dengan kampus       0.58                80                       3                        3
##   Jumlah.Perjalanan.Rabu Jumlah.Perjalanan.Kamis Jumlah.Perjalanan.Jumat Jumlah.Perjalanan.Sabtu Jumlah.Perjalanan.Ahad
## 1                      0                       0                       0                       0                      0
## 2                      0                       3                       0                       0                      0
##  [ reached 'max' / getOption("max.print") -- omitted 4 rows ]</code></pre>
<p>Fungsi tersebut akan mengimpor seluruh isi dari file Excel <code>Data Praktikum 01.xlsx</code> pada <em>sheet</em> pertama saja. <em>Dataset</em> yang kita impor akan menjadi objek dengan jenis <strong>tibble</strong>.</p>
<p>Apabila kita ingin mengimpor set data dari <em>sheet</em> lainnya, kita harus menyertakan detil nama sheet yang kita ingin impor pada atribut <code>sheet</code>. Misalnya kita ingin mengimpor <em>sheet</em> UBL yang bernama “DataUtama_mhsUBL”, maka perintahnya adalah:</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menyimpan file sebagai variabel tersendiri sehingga lebih fleksibel</span></span>
<span><span class="va">file_dibaca</span> <span class="op">&lt;-</span> <span class="st">"datasets/Data Praktikum 01.xlsx"</span> <span class="co"># nama variabel bukan 'file' saja karena sudah ada fungsi R tersendiri dengan nama tersebut</span></span>
<span></span>
<span><span class="co"># Mengimpor data dari file_dibaca dan menyimpannya sebagai variabel</span></span>
<span><span class="va">data_ubl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx</a></span><span class="op">(</span><span class="va">file_dibaca</span>, sheet <span class="op">=</span> <span class="st">"DataUtama_mhsUBL"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Melihat data tersebut</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data_ubl</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   Timestamp Kampus_PT Nomor.urut Jenis.Kelamin Umur                         Fakultas           Prodi            Tingkat.Semester
## 1  45413.83       UBL          1     Perempuan   21 Fakultas Ilmu Sosial dan Politik Ilmu Komunikasi 4 (Semester 7 - Semester 8)
##   Uang.Saku kepemilikan.mobil kepemilikan.motor kepemilikan.sepeda      kendaraan.utama         kelurahan
## 1    &lt; 1 jt                 1                 2                  1 Sepeda Motor Pribadi Kalibalau Kencana
##           jenis.tempat.tinggal nama.jalan.tempat.tinggal jarak.(km) alasan.pemilihan.lokasi.tempat.tinggal biaya.dalam.seminggu
## 1 Rumah pribadi/rumah keluarga              eLBe Loundry   4.223797         Bersama keluarga/saudara/teman              25 ribu
##   Jumlah.perjalanan.Senin Jumlah.Perjalanan.Selasa Jumlah.Perjalanan.Rabu Jumlah.Perjalanan.Kamis Jumlah.Perjalanan.Jumat
## 1                       2                        3                      2                       3                       2
##   Jumlah.Perjalanan.Sabtu Jumlah.Perjalanan.Ahad
## 1                       2                      2
##  [ reached 'max' / getOption("max.print") -- omitted 5 rows ]</code></pre>
<p>Kita juga dapat melihat <em>dataset</em> kita secara lengkap dengan perintah <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code>.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Melihat set data UINRIL</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/View.html">View</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Melihat set data UBL</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/View.html">View</a></span><span class="op">(</span><span class="va">data_ubl</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="analisis-data-terstruktur-pada-set-data" class="section level2" number="1.2">
<h2>
<span class="header-section-number">1.2</span> Analisis data terstruktur pada set data<a class="anchor" aria-label="anchor" href="#analisis-data-terstruktur-pada-set-data"><i class="fas fa-link"></i></a>
</h2>
<p>Kita sudah mempelajari bahwa data terstruktur terdiri atas <strong>objek</strong>, <strong>variabel</strong>, dan <strong>nilai</strong>. Satu objek diwakili oleh satu baris, variabel oleh kolom, dan nilai berada di dalam sel-sel yang merupakan perpotongan kolom dan baris.</p>
<div class="rmdwarning">
<p>⚠️ <strong>Perhatian</strong></p>
<p>Di modul ini kita menggunakan istilah “variabel” untuk menyebut dua hal yang berbeda. Makna pertama mengacu pada penyimpan nilai di R, sementara yang kedua adalah elemen data terstruktur yang menjadi kolom-kolom.</p>
<p>Dalam modul ini kita akan menggunakan istilah yang sama untuk kedua makna, jadi pahami konteks kalimatnya terlebih dahulu ketika menemukan kata ini.</p>
</div>
<p>Untuk mengetahui ringkasan struktur data, kita dapat menggunakan fungsi <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code> yang membutuhkan set data yang kita simpan sebagai argumen.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># ringkasan struktur data UIN RIL</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 400
## Columns: 25
## $ Kampus_PT                              &lt;chr&gt; "UINRIL", "UINRIL", "UINRIL", "UINRIL", "UINRIL", "UINRIL", "UINRIL", "UINRIL", "UINR…
## $ Nomor.urut                             &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24…
## $ Jenis.Kelamin                          &lt;chr&gt; "Laki-laki", "Laki-laki", "Perempuan", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-l…
## $ Umur                                   &lt;dbl&gt; 22, 25, 24, 19, 23, 21, 22, 21, 21, 21, 19, 19, 19, 19, 19, 20, 19, 21, 20, 20, 20, 2…
## $ Fakultas                               &lt;chr&gt; "Syariah", "Syariah", "Tarbiyah dan Keguruan", "Dakwah dan Ilmu Komunikasi", "Tarbiya…
## $ Prodi                                  &lt;chr&gt; "Hukum Keluarga", "Hukum Keluarga", "Pendidikan Agama Islam", "Komunikasi dan Penyiar…
## $ Tingkat.Semester                       &lt;chr&gt; "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semest…
## $ Uang.Saku                              &lt;chr&gt; "1Jt - 2 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "…
## $ kepemilikan.mobil                      &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0…
## $ kepemilikan.motor                      &lt;dbl&gt; 1, 4, 0, 1, 1, 1, 1, 4, 4, 1, 0, 1, 3, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 1, 3, 2, 2, 0…
## $ kepemilikan.sepedan                    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 3, 0…
## $ kendaraan.utama                        &lt;chr&gt; "Sepeda Motor Pribadi", "Sepeda Motor Pribadi", "Berjalan Kaki", "Sepeda Motor Pribad…
## $ kelurahan                              &lt;chr&gt; "Wiyono", "Sukarame", "Sukarame", "Harapan Jaya", "Korpri Raya", "Rajabasa ", "Campan…
## $ jenis.tempat.tinggal                   &lt;chr&gt; "Rumah Bersama Saudara", "Kos Sendiri", "Kos Sendiri", "Kos Sendiri", "Rumah Mengontr…
## $ nama.jalan.tempat.tinggal              &lt;chr&gt; "Pasar Wiyono", "jln endro suratmin ", "Jl. Pulau ambon", "Jl.pulau pisang, gg way pe…
## $ alasan.pemilihan.lokasi.tempat.tinggal &lt;chr&gt; "Lain-lain", "Dekat dengan kampus", "Dekat dengan kampus", "Dekat dengan kampus", "De…
## $ `jarak.(km)`                           &lt;dbl&gt; 19.27, 0.58, 0.56, 1.05, 1.69, 7.91, 2.58, 2.32, 0.77, 6.56, 0.63, 0.53, 0.91, 2.52, …
## $ biaya.dalam.ribu2                      &lt;dbl&gt; 100, 80, 0, 50, 50, 50, 35, 50, 40, 50, 0, 50, 50, 40, 0, 0, 30, 50, 60, 15, 0, 0, 40…
## $ Jumlah.Perjalanan.Senin                &lt;dbl&gt; 3, 3, 3, 0, 4, 0, 3, 4, 2, 3, 4, 2, 3, 2, 3, 2, 2, 2, 3, 2, 0, 2, 0, 3, 3, 2, 3, 1, 2…
## $ Jumlah.Perjalanan.Selasa               &lt;dbl&gt; 3, 3, 0, 2, 4, 2, 0, 4, 0, 2, 4, 2, 2, 2, 3, 2, 2, 2, 3, 0, 0, 0, 2, 0, 0, 2, 3, 1, 0…
## $ Jumlah.Perjalanan.Rabu                 &lt;dbl&gt; 0, 0, 3, 0, 0, 2, 3, 4, 3, 2, 4, 2, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 3, 3, 0, 2, 2, 0…
## $ Jumlah.Perjalanan.Kamis                &lt;dbl&gt; 0, 3, 0, 2, 0, 0, 0, 4, 0, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2…
## $ Jumlah.Perjalanan.Jumat                &lt;dbl&gt; 0, 0, 0, 2, 3, 2, 2, 4, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 0…
## $ Jumlah.Perjalanan.Sabtu                &lt;dbl&gt; 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0…
## $ Jumlah.Perjalanan.Ahad                 &lt;dbl&gt; 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0…</code></pre>
<p>Hasil dari fungsi <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code> tersebut menunjukkan jumlah baris, jumlah kolom, dan kolom-kolom yang ada dalam set data kita beserta rinciannya. Set data kita memiliki 400 baris yang ditunjukkan oleh <strong><code>Rows</code></strong> dan 25 kolom yang ditunjukkan oleh <strong><code>Columns</code></strong> . Ini artinya, set data kita memiliki 400 objek dan 25 variabel.</p>
<p>Rincian nama-nama variabel ditunjukkan pada baris keluaran yang diawali oleh simbol <strong><code>$</code></strong>. Singkatan-singkatan di dalam kurung sudut <code>&lt;&gt;</code> bermakna jenis nilai dari variabel tersebut. <a href="https://cran.r-project.org/web/packages/tibble/vignettes/types.html">Laman ini</a> memberikan penjelasan makna setiap singkatan tersebut.</p>
<p>Terlihat dalam data kita bahwa hanya ada dua tipe nilai variabel: <code>dbl</code> dan <code>chr</code> yang berarti <em>double</em> (bilangan desimal) dan <em>character</em> (huruf/<em>string</em>).</p>
<div id="aktivitas-mandiri-1-menganalisis-struktur-data-stp-1.3" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 1: Menganalisis Struktur Data <span class="capaian">STP-1.3</span><a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-1-menganalisis-struktur-data-stp-1.3"><i class="fas fa-link"></i></a>
</h3>
<p>Jalankan <code>glimpse(data)</code> untuk dataset <strong>UBL</strong> dan jawab:</p>
<ol style="list-style-type: decimal">
<li>Berapa jumlah objek (baris) dalam dataset ini?</li>
<li>Berapa jumlah variabel (kolom)?</li>
<li>Sebutkan 3 variabel dengan tipe <code>dbl</code> dan 3 variabel dengan tipe <code>chr</code>
</li>
<li>Mengapa variabel <code>Jenis.Kelamin</code> bertipe <code>chr</code> bukan <code>dbl</code>? Jelaskan!</li>
</ol>
</div>
</div>
<div id="mengolah-set-data" class="section level2" number="1.3">
<h2>
<span class="header-section-number">1.3</span> Mengolah set data<a class="anchor" aria-label="anchor" href="#mengolah-set-data"><i class="fas fa-link"></i></a>
</h2>
<p>Dalam bagian ini kita akan mengolah set data kita yang bertujuan untuk memenuhi kebutuhan pengolahan data kita. Sebelum melakukan pengolahan, maka kita perlu menjawab pertanyaan terlebih dahulu “apa yang kita butuhkan untuk pengolahan data kita?”</p>
<p>Dalam praktikum ini kita sudah mengetahui bahwa terdapat dua jenis set data hasil kuesioner, yakni set data mahasiswa Universitas Islam Negeri Raden Intan Lampung (UINRIL) dan juga Universitas Bandar Lampung (UBL). Kedua jenis set data tersebut disimpan dalam variabel yang berbeda. Kita butuh untuk <em>menggabungkan kedua set data</em> tersebut menjadi satu set data yang mencakup kedua kampus agar nanti kita bisa melakukan analisis dengan lebih leluasa.</p>
<p>Pengolahan set data seperti ini punya istilah yang keren: <strong><em>data wrangling</em></strong> (bisa dibaca “data rengling”)</p>
<div id="merancang-algoritma-urutan-kerja" class="section level3" number="1.3.1">
<h3>
<span class="header-section-number">1.3.1</span> Merancang Algoritma (Urutan kerja)<a class="anchor" aria-label="anchor" href="#merancang-algoritma-urutan-kerja"><i class="fas fa-link"></i></a>
</h3>
<p>Karena R adalah program yang mayoritasnya <em>character user interface</em> (CUI) alih-alih <em>graphical user interface</em>, maka pekerjaan kita tidak bisa seleluasa GUI yang dapat kita bolak-balik urutannya. Kita sebaiknya memiliki “rencana kerja” yang jelas, yang dalam bahasa pemrograman disebut <strong>algoritma</strong>.</p>
<p>Algoritma yang akan kita lakukan dalam praktikum ini adalah sebagai berikut:</p>
<ol style="list-style-type: decimal">
<li>Mengidentifikasi nama-nama kolom di set data UIN RIL</li>
<li>Mengidentifikasi nama-nama kolom di set data UBL</li>
<li>Menentukan kolom-kolom yang akan diambil di set data baru</li>
<li>Menyeleksi kolom-kolom yang akan dipakai di set data UIN RIL dan UBL,</li>
<li>Mengubah nama kolom-kolom di kedua set data menjadi nama-nama yang sudah ditentukan di langkah-3.</li>
<li>Menyatukan kedua set data.</li>
</ol>
<div class="rmdnote">
<p>💡 <strong>Tip</strong></p>
<p>Sebisa mungkin rancang setiap langkah pada urutan kerja kita dengan rinci agar kita dapat menerjemahkan langkah-langkah tersebut dengan lebih mudah ke baris kode.</p>
</div>
</div>
<div id="mengidentifikasi-nama-nama-kolom" class="section level3" number="1.3.2">
<h3>
<span class="header-section-number">1.3.2</span> Mengidentifikasi Nama-nama Kolom<a class="anchor" aria-label="anchor" href="#mengidentifikasi-nama-nama-kolom"><i class="fas fa-link"></i></a>
</h3>
<p>Untuk mengidentifikasi nama-nama kolom kita dapat menggunakan fungsi <code><a href="https://rdrr.io/r/base/colnames.html">colnames()</a></code> yang mengambil argumen nama set data.</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># data UIN RIL</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "Kampus_PT"                              "Nomor.urut"                             "Jenis.Kelamin"                         
##  [4] "Umur"                                   "Fakultas"                               "Prodi"                                 
##  [7] "Tingkat.Semester"                       "Uang.Saku"                              "kepemilikan.mobil"                     
## [10] "kepemilikan.motor"                      "kepemilikan.sepedan"                    "kendaraan.utama"                       
## [13] "kelurahan"                              "jenis.tempat.tinggal"                   "nama.jalan.tempat.tinggal"             
## [16] "alasan.pemilihan.lokasi.tempat.tinggal" "jarak.(km)"                             "biaya.dalam.ribu2"                     
## [19] "Jumlah.Perjalanan.Senin"                "Jumlah.Perjalanan.Selasa"               "Jumlah.Perjalanan.Rabu"                
## [22] "Jumlah.Perjalanan.Kamis"                "Jumlah.Perjalanan.Jumat"                "Jumlah.Perjalanan.Sabtu"               
## [25] "Jumlah.Perjalanan.Ahad"</code></pre>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># data UIN RIL</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data_ubl</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "Timestamp"                              "Kampus_PT"                              "Nomor.urut"                            
##  [4] "Jenis.Kelamin"                          "Umur"                                   "Fakultas"                              
##  [7] "Prodi"                                  "Tingkat.Semester"                       "Uang.Saku"                             
## [10] "kepemilikan.mobil"                      "kepemilikan.motor"                      "kepemilikan.sepeda"                    
## [13] "kendaraan.utama"                        "kelurahan"                              "jenis.tempat.tinggal"                  
## [16] "nama.jalan.tempat.tinggal"              "jarak.(km)"                             "alasan.pemilihan.lokasi.tempat.tinggal"
## [19] "biaya.dalam.seminggu"                   "Jumlah.perjalanan.Senin"                "Jumlah.Perjalanan.Selasa"              
## [22] "Jumlah.Perjalanan.Rabu"                 "Jumlah.Perjalanan.Kamis"                "Jumlah.Perjalanan.Jumat"               
## [25] "Jumlah.Perjalanan.Sabtu"                "Jumlah.Perjalanan.Ahad"</code></pre>
<p>Kita dapat mengetahui jumlah kolom setiap set data secara langsung dengan fungsi <code><a href="https://rdrr.io/r/base/length.html">length()</a></code>.</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span><span class="op">)</span> <span class="co"># jumlah kolom set data UIN RIL</span></span></code></pre></div>
<pre><code>## [1] 25</code></pre>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data_ubl</span><span class="op">)</span><span class="op">)</span> <span class="co"># jumlah kolom set data UBL</span></span></code></pre></div>
<pre><code>## [1] 26</code></pre>
<p>Hasil ini menunjukkan bahwa kedua dataset memiliki jumlah kolom yang hanya berbeda 1 kolom (25 kolom untuk UINRIL, 26 untuk UBL). Selain jumlahnya yang berbeda, terdapat juga perbedaan penamaan kolom pada kedua dataset sehingga perlu diseragamkan.</p>
<div class="rmdnote">
<p><strong>Catatan</strong></p>
<p>Fungsi <code><a href="https://rdrr.io/r/base/length.html">length()</a></code> pada dasarnya adalah fungsi penghitung jumlah elemen dalam suatu vektor atau jenis data lain yang berupa daftar.</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mendefinisikan suatu vektor</span></span>
<span><span class="va">suatu_vektor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Mengukur panjangnya</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">suatu_vektor</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 5</code></pre>
</div>
<p>Dari kedua fungsi tersebut, <code><a href="https://rdrr.io/r/base/length.html">length()</a></code> dan <code><a href="https://rdrr.io/r/base/colnames.html">colnames()</a></code>, kita dapat mengetahui bahwa terdapat perbedaan jumlah kolom dan juga perbedaan penamaan:</p>
<ul>
<li><p><code>kepemilikan.sepedan</code> di data UIN vs <code>kepemilikan.sepeda</code> di data UBL.</p></li>
<li><p><code>biaya.dalam.ribu2</code> di data UIN vs <code>biaya.dalam.seminggu</code> di data UBL.</p></li>
</ul>
<p>Perbedaan-perbedaan inilah yang membuat kita tidak bisa langsung menggabungkan data. Kita harus menyeragamkannya terlebih dahulu.</p>
</div>
<div id="menentukan-kolom-kolom-yang-akan-diambil-di-set-data-baru" class="section level3" number="1.3.3">
<h3>
<span class="header-section-number">1.3.3</span> Menentukan Kolom-kolom yang Akan Diambil di Set Data Baru<a class="anchor" aria-label="anchor" href="#menentukan-kolom-kolom-yang-akan-diambil-di-set-data-baru"><i class="fas fa-link"></i></a>
</h3>
<p>Setelah mengidentifikasi nama-nama variabel dan jumlahnya, kita putuskan untuk mengambil variabel-variabel berikut: (1) <code>Nomor.urut</code>, (2) <code>Jenis.Kelamin</code>, (3) <code>Umur</code>, (4) <code>Fakultas</code>, (5) <code>Prodi</code>, (6) <code>Tingkat.Semester</code>, (7) <code>Uang.Saku</code>, (8) <code>kepemilikan.mobil</code>, (9) <code>kepemilikan.motor</code>, (10) <code>kepemilikan.sepeda</code>, (11) <code>kendaraan.utama</code>, (12) <code>jenis.tempat.tinggal</code>, (13) <code>jarak</code>, (14) <code>biaya.dalam.seminggu</code>, (15) <code>Jumlah.perjalanan.Senin</code>, (16) <code>Jumlah.perjalanan.Selasa</code>, (17) <code>Jumlah.perjalanan.Rabu</code>, (18) <code>Jumlah.perjalanan.Kamis</code>, (19) <code>Jumlah.perjalanan.Jumat</code>, (20) <code>Jumlah.perjalanan.Sabtu</code>, (21) <code>Jumlah.perjalanan.Ahad</code>.</p>
<p>Kita akan menyimpan nama-nama kolom yang sudah kita tentukan tersebut menjadi sebuah vektor.</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Membuat vektor berisi nama-nama kolom final yang kita inginkan</span></span>
<span><span class="va">kolom_final</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>   <span class="st">"nomor_urut"</span>, <span class="st">"jenis_kelamin"</span>, <span class="st">"umur"</span>, <span class="st">"fakultas"</span>, <span class="st">"prodi"</span>,</span>
<span>   <span class="st">"tingkat_semester"</span>, <span class="st">"uang_saku"</span>,</span>
<span>   <span class="st">"kepemilikan_mobil"</span>,</span>
<span>   <span class="st">"kepemilikan_motor"</span>, <span class="st">"kepemilikan_sepeda"</span>, <span class="st">"kendaraan_utama"</span>,</span>
<span>   <span class="st">"jenis_tempat_tinggal"</span>, <span class="st">"jarak"</span>, <span class="st">"biaya_dalam_sepekan"</span>,</span>
<span>   <span class="st">"jumlah_perjalanan_senin"</span>, <span class="st">"jumlah_perjalanan_selasa"</span>,</span>
<span>   <span class="st">"jumlah_perjalanan_rabu"</span>, <span class="st">"jumlah_perjalanan_kamis"</span>,</span>
<span>   <span class="st">"jumlah_perjalanan_jumat"</span>, <span class="st">"jumlah_perjalanan_sabtu"</span>,</span>
<span>   <span class="st">"jumlah_perjalanan_ahad"</span></span>
<span><span class="op">)</span></span></code></pre></div>
</div>
<div id="menyeleksi-kolom-kolom-yang-akan-dipakai" class="section level3" number="1.3.4">
<h3>
<span class="header-section-number">1.3.4</span> Menyeleksi Kolom-kolom Yang Akan Dipakai<a class="anchor" aria-label="anchor" href="#menyeleksi-kolom-kolom-yang-akan-dipakai"><i class="fas fa-link"></i></a>
</h3>
<p>Kita akan menggunakan fungsi <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> dari <code>dplyr</code> (bagian dari <code>tidyverse</code>) untuk memilih hanya kolom-kolom yang relevan dari masing-masing set data. Perhatikan baik-baik, kita harus menggunakan <strong>nama kolom asli</strong> saat menyeleksi.</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 4. Menyeleksi kolom dari data UIN RIL</span></span>
<span><span class="co"># Fungsi select() memilih kolom yang kita butuhkan dari 25 kolom yang ada</span></span>
<span><span class="va">data_uin_selected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span></span>
<span>   <span class="va">data</span>,</span>
<span>   <span class="va">Nomor.urut</span>, <span class="va">Jenis.Kelamin</span>, <span class="va">Umur</span>, <span class="va">Fakultas</span>, <span class="va">Prodi</span>, <span class="va">Tingkat.Semester</span>,</span>
<span>   <span class="va">Uang.Saku</span>,</span>
<span>   <span class="va">kepemilikan.mobil</span>, <span class="va">kepemilikan.motor</span>,</span>
<span>   <span class="va">kepemilikan.sepedan</span>, <span class="co"># Perhatian: Nama asli pakai 'n'</span></span>
<span>   <span class="va">kendaraan.utama</span>, <span class="va">jenis.tempat.tinggal</span>,</span>
<span>   <span class="va">`jarak.(km)`</span>, <span class="co"># Backtick (`) WAJIB untuk nama kolom dengan karakter spesial</span></span>
<span>   <span class="va">`biaya.dalam.ribu2`</span>, <span class="co"># Backtick melindungi tanda kurung dan angka</span></span>
<span>   <span class="va">Jumlah.Perjalanan.Senin</span>, <span class="va">Jumlah.Perjalanan.Selasa</span>, <span class="va">Jumlah.Perjalanan.Rabu</span>,</span>
<span>   <span class="va">Jumlah.Perjalanan.Kamis</span>, <span class="va">Jumlah.Perjalanan.Jumat</span>, <span class="va">Jumlah.Perjalanan.Sabtu</span>,</span>
<span>   <span class="va">Jumlah.Perjalanan.Ahad</span></span>
<span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 5. Menyeleksi kolom dari data UBL</span></span>
<span><span class="va">data_ubl_selected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span></span>
<span>   <span class="va">data_ubl</span>,</span>
<span>   <span class="va">Nomor.urut</span>, <span class="va">Jenis.Kelamin</span>, <span class="va">Umur</span>, <span class="va">Fakultas</span>, <span class="va">Prodi</span>, <span class="va">Tingkat.Semester</span>,</span>
<span>   <span class="va">Uang.Saku</span>,</span>
<span>   <span class="va">kepemilikan.mobil</span>, <span class="va">kepemilikan.motor</span>,</span>
<span>   <span class="va">kepemilikan.sepeda</span>, <span class="co"># Di sini namanya sudah benar</span></span>
<span>   <span class="va">kendaraan.utama</span>, <span class="va">jenis.tempat.tinggal</span>,</span>
<span>   <span class="va">`jarak.(km)`</span>,</span>
<span>   <span class="va">biaya.dalam.seminggu</span>,</span>
<span>   <span class="va">Jumlah.perjalanan.Senin</span>, <span class="va">Jumlah.Perjalanan.Selasa</span>, <span class="va">Jumlah.Perjalanan.Rabu</span>,</span>
<span>   <span class="va">Jumlah.Perjalanan.Kamis</span>, <span class="va">Jumlah.Perjalanan.Jumat</span>, <span class="va">Jumlah.Perjalanan.Sabtu</span>,</span>
<span>   <span class="va">Jumlah.Perjalanan.Ahad</span></span>
<span><span class="op">)</span></span></code></pre></div>
<p>Sekarang kita punya dua <em>data frame</em> baru (<code>data_uin_selected</code> dan <code>data_ubl_selected</code>) yang isinya hanya kolom-kolom yang kita butuhkan.</p>
</div>
<div id="mengubah-nama-kolom-menjadi-nama-standar" class="section level3" number="1.3.5">
<h3>
<span class="header-section-number">1.3.5</span> Mengubah Nama Kolom Menjadi Nama Standar<a class="anchor" aria-label="anchor" href="#mengubah-nama-kolom-menjadi-nama-standar"><i class="fas fa-link"></i></a>
</h3>
<p>Ini adalah langkah kuncinya. Kita cukup menimpa nama-nama kolom di kedua <em>data frame</em> yang sudah kita seleksi tadi dengan nama-nama kolom dari vektor <code>kolom_final</code> yang kita buat di 3.3.3.</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mengganti nama kolom di kedua data frame</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data_uin_selected</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">kolom_final</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data_ubl_selected</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">kolom_final</span></span></code></pre></div>
<p>Untuk membuktikan bahwa namanya sudah berubah, kita bisa cek lagi.</p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Cek nama kolom setelah diubah</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data_uin_selected</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "nomor_urut"               "jenis_kelamin"            "umur"                     "fakultas"                
##  [5] "prodi"                    "tingkat_semester"         "uang_saku"                "kepemilikan_mobil"       
##  [9] "kepemilikan_motor"        "kepemilikan_sepeda"       "kendaraan_utama"          "jenis_tempat_tinggal"    
## [13] "jarak"                    "biaya_dalam_sepekan"      "jumlah_perjalanan_senin"  "jumlah_perjalanan_selasa"
## [17] "jumlah_perjalanan_rabu"   "jumlah_perjalanan_kamis"  "jumlah_perjalanan_jumat"  "jumlah_perjalanan_sabtu" 
## [21] "jumlah_perjalanan_ahad"</code></pre>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data_ubl_selected</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "nomor_urut"               "jenis_kelamin"            "umur"                     "fakultas"                
##  [5] "prodi"                    "tingkat_semester"         "uang_saku"                "kepemilikan_mobil"       
##  [9] "kepemilikan_motor"        "kepemilikan_sepeda"       "kendaraan_utama"          "jenis_tempat_tinggal"    
## [13] "jarak"                    "biaya_dalam_sepekan"      "jumlah_perjalanan_senin"  "jumlah_perjalanan_selasa"
## [17] "jumlah_perjalanan_rabu"   "jumlah_perjalanan_kamis"  "jumlah_perjalanan_jumat"  "jumlah_perjalanan_sabtu" 
## [21] "jumlah_perjalanan_ahad"</code></pre>
<p>Hasil dari kedua perintah di atas seharusnya adalah daftar nama yang identik.</p>
</div>
<div id="aktivitas-mandiri-2-seleksi-dan-rename-kolom-stp-1.4" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 2: Seleksi dan Rename Kolom <span class="capaian">STP-1.4</span><a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-2-seleksi-dan-rename-kolom-stp-1.4"><i class="fas fa-link"></i></a>
</h3>
<p>Pada aktivitas ini kita akan mengolah kembali dataset dari UINRIL.</p>
<ol style="list-style-type: decimal">
<li>Impor kembali sheet pertama (UINRIL) dari file dataset dengan fungsi <code><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx()</a></code>, lalu simpan hasilnya dengan nama <code>data_uinril_lat</code>.</li>
<li>Pilih hanya 6 kolom berikut menggunakan perintah <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>: <code>Kampus_PT</code>, <code>Jenis.Kelamin</code>, <code>kepemilikan.mobil</code>, <code>kepemilikan.motor</code>, <code>kepemilikan.sepedan</code>, dan <code>`jarak.(km)`</code> (ingat menggunakan <em>backtick</em> (`) untuk kolom jarak karena terdapat karakter khusus).</li>
<li>Buat vektor <code>kolom_final</code> berisi nama standar berikut: <code>c("kampus", "jenis_kelamin", "kepemilikan_mobil", "kepemilikan_motor", "kepemilikan_sepeda", "jarak")</code>.</li>
<li>Gunakan vektor tersebut untuk menyeragamkan nama kolom dari data hasil seleksi Langkah 2 dengan fungsi <code>colnames(...) &lt;- ...</code>
</li>
<li>Simpan hasil akhir (setelah diseleksi dan diubah nama kolomnya) ke variabel <code>data_uinril_subset</code>.</li>
<li>Gunakan <code>glimpse(data_uinril_subset)</code> untuk memverifikasi bahwa sekarang hanya ada 6 kolom dan namanya sudah seragam sesuai dengan isi dari <code>kolom_final</code>.</li>
</ol>
</div>
<div id="menyatukan-kedua-set-data" class="section level3" number="1.3.6">
<h3>
<span class="header-section-number">1.3.6</span> Menyatukan Kedua Set Data<a class="anchor" aria-label="anchor" href="#menyatukan-kedua-set-data"><i class="fas fa-link"></i></a>
</h3>
<p>Ini adalah langkah terakhir kita. Karena kedua set data kini memiliki struktur kolom yang sama persis, kita bisa menyatukannya menjadi satu <em>data frame</em> besar dengan fungsi <code><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows()</a></code>.</p>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menggabungkan kedua data frame menjadi satu</span></span>
<span><span class="va">data_gabungan</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">data_uin_selected</span>, <span class="va">data_ubl_selected</span><span class="op">)</span></span></code></pre></div>
<p>Hasil dari penggabungan tersebut menyebabkan <em>error</em> pada kolom <code>biaya.dalam.sepekan</code> . Ini disebabkan oleh <code>biaya.dalam.sepekan</code> dalam set data UINRIL (<code>data</code>) berbeda jenisnya dengan set data UBL (<code>data_ubl</code>). Begitu pula <code>Jumlah.perjalanan.Senin</code></p>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mengecek tipe data dalam set data UINRIL</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_uin_selected</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 400
## Columns: 21
## $ nomor_urut               &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, …
## $ jenis_kelamin            &lt;chr&gt; "Laki-laki", "Laki-laki", "Perempuan", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-la…
## $ umur                     &lt;dbl&gt; 22, 25, 24, 19, 23, 21, 22, 21, 21, 21, 19, 19, 19, 19, 19, 20, 19, 21, 20, 20, 20, 20, 20, 19, 20,…
## $ fakultas                 &lt;chr&gt; "Syariah", "Syariah", "Tarbiyah dan Keguruan", "Dakwah dan Ilmu Komunikasi", "Tarbiyah dan Keguruan…
## $ prodi                    &lt;chr&gt; "Hukum Keluarga", "Hukum Keluarga", "Pendidikan Agama Islam", "Komunikasi dan Penyiaran Islam", "Ma…
## $ tingkat_semester         &lt;chr&gt; "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semester 8)", "1 (Se…
## $ uang_saku                &lt;chr&gt; "1Jt - 2 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "1Jt - 2 Jt", "…
## $ kepemilikan_mobil        &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, …
## $ kepemilikan_motor        &lt;dbl&gt; 1, 4, 0, 1, 1, 1, 1, 4, 4, 1, 0, 1, 3, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 1, 3, 2, 2, 0, 1, 1, 1, 2, …
## $ kepemilikan_sepeda       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 3, 0, 0, 0, 0, 4, …
## $ kendaraan_utama          &lt;chr&gt; "Sepeda Motor Pribadi", "Sepeda Motor Pribadi", "Berjalan Kaki", "Sepeda Motor Pribadi", "Sepeda Mo…
## $ jenis_tempat_tinggal     &lt;chr&gt; "Rumah Bersama Saudara", "Kos Sendiri", "Kos Sendiri", "Kos Sendiri", "Rumah Mengontrak Bersama-sam…
## $ jarak                    &lt;dbl&gt; 19.27, 0.58, 0.56, 1.05, 1.69, 7.91, 2.58, 2.32, 0.77, 6.56, 0.63, 0.53, 0.91, 2.52, 1.31, 0.83, 0.…
## $ biaya_dalam_sepekan      &lt;dbl&gt; 100, 80, 0, 50, 50, 50, 35, 50, 40, 50, 0, 50, 50, 40, 0, 0, 30, 50, 60, 15, 0, 0, 40, 15, 37, 25, …
## $ jumlah_perjalanan_senin  &lt;dbl&gt; 3, 3, 3, 0, 4, 0, 3, 4, 2, 3, 4, 2, 3, 2, 3, 2, 2, 2, 3, 2, 0, 2, 0, 3, 3, 2, 3, 1, 2, 2, 3, 2, 2, …
## $ jumlah_perjalanan_selasa &lt;dbl&gt; 3, 3, 0, 2, 4, 2, 0, 4, 0, 2, 4, 2, 2, 2, 3, 2, 2, 2, 3, 0, 0, 0, 2, 0, 0, 2, 3, 1, 0, 2, 3, 2, 3, …
## $ jumlah_perjalanan_rabu   &lt;dbl&gt; 0, 0, 3, 0, 0, 2, 3, 4, 3, 2, 4, 2, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 3, 3, 0, 2, 2, 0, 4, 3, 2, 2, …
## $ jumlah_perjalanan_kamis  &lt;dbl&gt; 0, 3, 0, 2, 0, 0, 0, 4, 0, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 4, 3, 2, 2, …
## $ jumlah_perjalanan_jumat  &lt;dbl&gt; 0, 0, 0, 2, 3, 2, 2, 4, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 0, 0, 4, 2, 2, …
## $ jumlah_perjalanan_sabtu  &lt;dbl&gt; 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 2, 0, …
## $ jumlah_perjalanan_ahad   &lt;dbl&gt; 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, …</code></pre>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mengecek tipe data dalam set data UBL</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_ubl_selected</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 379
## Columns: 21
## $ nomor_urut               &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, …
## $ jenis_kelamin            &lt;chr&gt; "Perempuan", "Laki-Laki", "Laki-Laki", "Laki-Laki", "Laki-Laki", "Perempuan", "Perempuan", "Perempu…
## $ umur                     &lt;dbl&gt; 21, 20, 21, 22, 21, 21, 22, 22, 22, 22, 21, 22, 22, 22, 19, 22, 23, 22, 23, 22, 20, 19, 21, 22, 18,…
## $ fakultas                 &lt;chr&gt; "Fakultas Ilmu Sosial dan Politik", "Fakultas Hukum", "Fakultas Ekonomi dan Bisnis", "Fakultas Ekon…
## $ prodi                    &lt;chr&gt; "Ilmu Komunikasi", "Ilmu Hukum", "Manajemen", "Akuntansi", "Manajemen", "Akuntansi", "Administrasi …
## $ tingkat_semester         &lt;chr&gt; "4 (Semester 7 - Semester 8)", "3 (Semester 5 - Semester 6)", "4 (Semester 7 - Semester 8)", "4 (Se…
## $ uang_saku                &lt;chr&gt; "&lt; 1 jt", "1 jt – 2 jt", "1 jt – 2 jt", "1 jt – 2 jt", "2,1 jt – 3 jt", "1 jt – 2 jt", "1 jt – 2 jt…
## $ kepemilikan_mobil        &lt;dbl&gt; 1, 2, 1, 1, 4, 1, 1, 1, 1, 1, NA, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 2, 1, 1, 2, 1, 2,…
## $ kepemilikan_motor        &lt;dbl&gt; 2, 1, 2, 4, 4, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 2, 2, 1, 1, 0, 1, 0, 1, 3, 1, 3, 2, 2, 2, …
## $ kepemilikan_sepeda       &lt;dbl&gt; 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 1, 0, 0, 3, 1, 0, 0, 0, 0,…
## $ kendaraan_utama          &lt;chr&gt; "Sepeda Motor Pribadi", "Mobil Pribadi", "Sepeda Motor Pribadi", "Kendaraan Bermotor (menumpang den…
## $ jenis_tempat_tinggal     &lt;chr&gt; "Rumah pribadi/rumah keluarga", "Rumah pribadi/rumah keluarga", "Rumah pribadi/rumah keluarga", "Ru…
## $ jarak                    &lt;dbl&gt; 4.2237967, 2.7033310, 3.2370722, 3.0023362, 5.9619250, 2.9253306, 2.0588294, 12.0078709, 4.7355783,…
## $ biaya_dalam_sepekan      &lt;chr&gt; "25 ribu", "200", "50rb menggunakan kendaraan pribadi", "Sminggu 20 rb", "20 JUTA RUPIAH", "40 rb",…
## $ jumlah_perjalanan_senin  &lt;chr&gt; "2", "3", "1", "2", "1", "3", "2", "4", "4", "3", "Tidak Valid", "2", "Tidak Valid", "4", "2", "2",…
## $ jumlah_perjalanan_selasa &lt;dbl&gt; 3, 3, 1, 2, 1, 3, 2, 4, 4, 3, 3, 1, 1, 4, 1, 3, 3, 1, 1, 3, 1, 1, 1, 3, 4, 1, 5, 1, 1, 3, 3, 3, 3, …
## $ jumlah_perjalanan_rabu   &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 4, 4, 3, 1, 2, 1, 4, 3, 2, 4, 1, 1, 3, 1, 1, 1, 3, 3, 1, 5, 1, 1, 3, 2, 3, 1, …
## $ jumlah_perjalanan_kamis  &lt;dbl&gt; 3, 3, 1, 2, 1, 1, 2, 4, 4, 3, 1, 1, 1, 4, 3, 2, 2, 1, 1, 3, 1, 1, 1, 3, 3, 1, 5, 1, 2, 3, 1, 2, 4, …
## $ jumlah_perjalanan_jumat  &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 4, 3, 3, 1, 2, 1, 4, 3, 2, 3, 1, 1, 3, 1, 1, 1, 3, 3, 1, 5, 1, 1, 3, 1, 1, 1, …
## $ jumlah_perjalanan_sabtu  &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 3, 4, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 3, 3, 1, 3, 1, 1, 3, 1, 4, 3, …
## $ jumlah_perjalanan_ahad   &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 3, 4, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 3, 3, 1, 3, 1, 1, 1, 1, 1, 1, …</code></pre>
<p>Ini adalah kasus yang tepat untuk menggambarkan bahwa dalam data terstruktur, jenis nilai harus sama persis. Untuk kesederhanaan praktikum, kita akan melewati dulu variabel <code>biaya.dalam.sepekan</code> dan <code>Jumlah.perjalanan.Senin</code> tersebut.</p>
</div>
<div id="memperbaiki-set-data-yang-akan-digabungkan" class="section level3" number="1.3.7">
<h3>
<span class="header-section-number">1.3.7</span> Memperbaiki Set Data yang Akan Digabungkan<a class="anchor" aria-label="anchor" href="#memperbaiki-set-data-yang-akan-digabungkan"><i class="fas fa-link"></i></a>
</h3>
<p>Kita akan menghapus <code>biaya.dalam.sepekan</code> dari kedua set data kita. Untuk menghapus suatu kolom, kita dapat menggunakan fungsi <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> juga, akan tetapi kita tambahkan tanda negatif (<code>-</code>) di depan nama variabelnya.</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 'Menimpa' data_uin_selected dengan data_uin_selected yang variabel biaya.dalam.sepekan sudah dihapus</span></span>
<span><span class="va">data_uin_selected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span></span>
<span>   <span class="va">data_uin_selected</span>,</span>
<span>   <span class="op">-</span><span class="va">`biaya_dalam_sepekan`</span>, <span class="op">-</span><span class="va">`jumlah_perjalanan_senin`</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Melihat hasilnya</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_uin_selected</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 400
## Columns: 19
## $ nomor_urut               &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, …
## $ jenis_kelamin            &lt;chr&gt; "Laki-laki", "Laki-laki", "Perempuan", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-la…
## $ umur                     &lt;dbl&gt; 22, 25, 24, 19, 23, 21, 22, 21, 21, 21, 19, 19, 19, 19, 19, 20, 19, 21, 20, 20, 20, 20, 20, 19, 20,…
## $ fakultas                 &lt;chr&gt; "Syariah", "Syariah", "Tarbiyah dan Keguruan", "Dakwah dan Ilmu Komunikasi", "Tarbiyah dan Keguruan…
## $ prodi                    &lt;chr&gt; "Hukum Keluarga", "Hukum Keluarga", "Pendidikan Agama Islam", "Komunikasi dan Penyiaran Islam", "Ma…
## $ tingkat_semester         &lt;chr&gt; "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semester 8)", "1 (Se…
## $ uang_saku                &lt;chr&gt; "1Jt - 2 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "1Jt - 2 Jt", "…
## $ kepemilikan_mobil        &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, …
## $ kepemilikan_motor        &lt;dbl&gt; 1, 4, 0, 1, 1, 1, 1, 4, 4, 1, 0, 1, 3, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 1, 3, 2, 2, 0, 1, 1, 1, 2, …
## $ kepemilikan_sepeda       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 3, 0, 0, 0, 0, 4, …
## $ kendaraan_utama          &lt;chr&gt; "Sepeda Motor Pribadi", "Sepeda Motor Pribadi", "Berjalan Kaki", "Sepeda Motor Pribadi", "Sepeda Mo…
## $ jenis_tempat_tinggal     &lt;chr&gt; "Rumah Bersama Saudara", "Kos Sendiri", "Kos Sendiri", "Kos Sendiri", "Rumah Mengontrak Bersama-sam…
## $ jarak                    &lt;dbl&gt; 19.27, 0.58, 0.56, 1.05, 1.69, 7.91, 2.58, 2.32, 0.77, 6.56, 0.63, 0.53, 0.91, 2.52, 1.31, 0.83, 0.…
## $ jumlah_perjalanan_selasa &lt;dbl&gt; 3, 3, 0, 2, 4, 2, 0, 4, 0, 2, 4, 2, 2, 2, 3, 2, 2, 2, 3, 0, 0, 0, 2, 0, 0, 2, 3, 1, 0, 2, 3, 2, 3, …
## $ jumlah_perjalanan_rabu   &lt;dbl&gt; 0, 0, 3, 0, 0, 2, 3, 4, 3, 2, 4, 2, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 3, 3, 0, 2, 2, 0, 4, 3, 2, 2, …
## $ jumlah_perjalanan_kamis  &lt;dbl&gt; 0, 3, 0, 2, 0, 0, 0, 4, 0, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 4, 3, 2, 2, …
## $ jumlah_perjalanan_jumat  &lt;dbl&gt; 0, 0, 0, 2, 3, 2, 2, 4, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 0, 0, 4, 2, 2, …
## $ jumlah_perjalanan_sabtu  &lt;dbl&gt; 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 2, 0, …
## $ jumlah_perjalanan_ahad   &lt;dbl&gt; 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, …</code></pre>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">data_uin_selected</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "nomor_urut"               "jenis_kelamin"            "umur"                     "fakultas"                
##  [5] "prodi"                    "tingkat_semester"         "uang_saku"                "kepemilikan_mobil"       
##  [9] "kepemilikan_motor"        "kepemilikan_sepeda"       "kendaraan_utama"          "jenis_tempat_tinggal"    
## [13] "jarak"                    "jumlah_perjalanan_selasa" "jumlah_perjalanan_rabu"   "jumlah_perjalanan_kamis" 
## [17] "jumlah_perjalanan_jumat"  "jumlah_perjalanan_sabtu"  "jumlah_perjalanan_ahad"</code></pre>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 'Menimpa' data_ubl_selected dengan data_ubl_selected yang variabel biaya.dalam.sepekan sudah dihapus</span></span>
<span><span class="va">data_ubl_selected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span></span>
<span>   <span class="va">data_ubl_selected</span>,</span>
<span>   <span class="op">-</span><span class="va">`biaya_dalam_sepekan`</span>, <span class="op">-</span><span class="va">`jumlah_perjalanan_senin`</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Melihat hasilnya</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_ubl_selected</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 379
## Columns: 19
## $ nomor_urut               &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, …
## $ jenis_kelamin            &lt;chr&gt; "Perempuan", "Laki-Laki", "Laki-Laki", "Laki-Laki", "Laki-Laki", "Perempuan", "Perempuan", "Perempu…
## $ umur                     &lt;dbl&gt; 21, 20, 21, 22, 21, 21, 22, 22, 22, 22, 21, 22, 22, 22, 19, 22, 23, 22, 23, 22, 20, 19, 21, 22, 18,…
## $ fakultas                 &lt;chr&gt; "Fakultas Ilmu Sosial dan Politik", "Fakultas Hukum", "Fakultas Ekonomi dan Bisnis", "Fakultas Ekon…
## $ prodi                    &lt;chr&gt; "Ilmu Komunikasi", "Ilmu Hukum", "Manajemen", "Akuntansi", "Manajemen", "Akuntansi", "Administrasi …
## $ tingkat_semester         &lt;chr&gt; "4 (Semester 7 - Semester 8)", "3 (Semester 5 - Semester 6)", "4 (Semester 7 - Semester 8)", "4 (Se…
## $ uang_saku                &lt;chr&gt; "&lt; 1 jt", "1 jt – 2 jt", "1 jt – 2 jt", "1 jt – 2 jt", "2,1 jt – 3 jt", "1 jt – 2 jt", "1 jt – 2 jt…
## $ kepemilikan_mobil        &lt;dbl&gt; 1, 2, 1, 1, 4, 1, 1, 1, 1, 1, NA, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 2, 1, 1, 2, 1, 2,…
## $ kepemilikan_motor        &lt;dbl&gt; 2, 1, 2, 4, 4, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 2, 2, 1, 1, 0, 1, 0, 1, 3, 1, 3, 2, 2, 2, …
## $ kepemilikan_sepeda       &lt;dbl&gt; 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 1, 0, 0, 3, 1, 0, 0, 0, 0,…
## $ kendaraan_utama          &lt;chr&gt; "Sepeda Motor Pribadi", "Mobil Pribadi", "Sepeda Motor Pribadi", "Kendaraan Bermotor (menumpang den…
## $ jenis_tempat_tinggal     &lt;chr&gt; "Rumah pribadi/rumah keluarga", "Rumah pribadi/rumah keluarga", "Rumah pribadi/rumah keluarga", "Ru…
## $ jarak                    &lt;dbl&gt; 4.2237967, 2.7033310, 3.2370722, 3.0023362, 5.9619250, 2.9253306, 2.0588294, 12.0078709, 4.7355783,…
## $ jumlah_perjalanan_selasa &lt;dbl&gt; 3, 3, 1, 2, 1, 3, 2, 4, 4, 3, 3, 1, 1, 4, 1, 3, 3, 1, 1, 3, 1, 1, 1, 3, 4, 1, 5, 1, 1, 3, 3, 3, 3, …
## $ jumlah_perjalanan_rabu   &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 4, 4, 3, 1, 2, 1, 4, 3, 2, 4, 1, 1, 3, 1, 1, 1, 3, 3, 1, 5, 1, 1, 3, 2, 3, 1, …
## $ jumlah_perjalanan_kamis  &lt;dbl&gt; 3, 3, 1, 2, 1, 1, 2, 4, 4, 3, 1, 1, 1, 4, 3, 2, 2, 1, 1, 3, 1, 1, 1, 3, 3, 1, 5, 1, 2, 3, 1, 2, 4, …
## $ jumlah_perjalanan_jumat  &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 4, 3, 3, 1, 2, 1, 4, 3, 2, 3, 1, 1, 3, 1, 1, 1, 3, 3, 1, 5, 1, 1, 3, 1, 1, 1, …
## $ jumlah_perjalanan_sabtu  &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 3, 4, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 3, 3, 1, 3, 1, 1, 3, 1, 4, 3, …
## $ jumlah_perjalanan_ahad   &lt;dbl&gt; 2, 3, 1, 2, 1, 1, 2, 3, 4, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 3, 3, 1, 3, 1, 1, 1, 1, 1, 1, …</code></pre>
</div>
<div id="menyatukan-kedua-set-data-setelah-diperbaiki" class="section level3" number="1.3.8">
<h3>
<span class="header-section-number">1.3.8</span> Menyatukan Kedua Set Data Setelah Diperbaiki<a class="anchor" aria-label="anchor" href="#menyatukan-kedua-set-data-setelah-diperbaiki"><i class="fas fa-link"></i></a>
</h3>
<p>Kita akan coba menggabungkan kedua set data tadi.</p>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Menggabungkan kedua data frame menjadi satu</span></span>
<span><span class="co"># bind_rows() menumpuk baris-baris dari kedua dataset (seperti menumpuk kartu)</span></span>
<span><span class="co"># PENTING: Nama kolom harus sama PERSIS agar penggabungan berhasil</span></span>
<span><span class="va">data_gabungan</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">data_uin_selected</span>, <span class="va">data_ubl_selected</span><span class="op">)</span></span></code></pre></div>
<p>Selesai! 🥳 Mari kita lihat hasil akhir dari kerja keras kita dengan <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code>. Hasil akan menunjukkan bahwa kita mempunyai 779 objek yang merupakan gabungan responden mahasiswa UIN RIL dan UBL.</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Tampilkan struktur data gabungan yang sudah rapi</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_gabungan</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 779
## Columns: 19
## $ nomor_urut               &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, …
## $ jenis_kelamin            &lt;chr&gt; "Laki-laki", "Laki-laki", "Perempuan", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-la…
## $ umur                     &lt;dbl&gt; 22, 25, 24, 19, 23, 21, 22, 21, 21, 21, 19, 19, 19, 19, 19, 20, 19, 21, 20, 20, 20, 20, 20, 19, 20,…
## $ fakultas                 &lt;chr&gt; "Syariah", "Syariah", "Tarbiyah dan Keguruan", "Dakwah dan Ilmu Komunikasi", "Tarbiyah dan Keguruan…
## $ prodi                    &lt;chr&gt; "Hukum Keluarga", "Hukum Keluarga", "Pendidikan Agama Islam", "Komunikasi dan Penyiaran Islam", "Ma…
## $ tingkat_semester         &lt;chr&gt; "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semester 8)", "4 (Semester 7 - Semester 8)", "1 (Se…
## $ uang_saku                &lt;chr&gt; "1Jt - 2 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "&lt; 1 Jt", "1Jt - 2 Jt", "…
## $ kepemilikan_mobil        &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, …
## $ kepemilikan_motor        &lt;dbl&gt; 1, 4, 0, 1, 1, 1, 1, 4, 4, 1, 0, 1, 3, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 1, 3, 2, 2, 0, 1, 1, 1, 2, …
## $ kepemilikan_sepeda       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 3, 0, 0, 0, 0, 4, …
## $ kendaraan_utama          &lt;chr&gt; "Sepeda Motor Pribadi", "Sepeda Motor Pribadi", "Berjalan Kaki", "Sepeda Motor Pribadi", "Sepeda Mo…
## $ jenis_tempat_tinggal     &lt;chr&gt; "Rumah Bersama Saudara", "Kos Sendiri", "Kos Sendiri", "Kos Sendiri", "Rumah Mengontrak Bersama-sam…
## $ jarak                    &lt;dbl&gt; 19.27, 0.58, 0.56, 1.05, 1.69, 7.91, 2.58, 2.32, 0.77, 6.56, 0.63, 0.53, 0.91, 2.52, 1.31, 0.83, 0.…
## $ jumlah_perjalanan_selasa &lt;dbl&gt; 3, 3, 0, 2, 4, 2, 0, 4, 0, 2, 4, 2, 2, 2, 3, 2, 2, 2, 3, 0, 0, 0, 2, 0, 0, 2, 3, 1, 0, 2, 3, 2, 3, …
## $ jumlah_perjalanan_rabu   &lt;dbl&gt; 0, 0, 3, 0, 0, 2, 3, 4, 3, 2, 4, 2, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 3, 3, 0, 2, 2, 0, 4, 3, 2, 2, …
## $ jumlah_perjalanan_kamis  &lt;dbl&gt; 0, 3, 0, 2, 0, 0, 0, 4, 0, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 4, 3, 2, 2, …
## $ jumlah_perjalanan_jumat  &lt;dbl&gt; 0, 0, 0, 2, 3, 2, 2, 4, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 0, 0, 4, 2, 2, …
## $ jumlah_perjalanan_sabtu  &lt;dbl&gt; 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 2, 0, …
## $ jumlah_perjalanan_ahad   &lt;dbl&gt; 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, …</code></pre>
<p>🎉 <strong>Selamat!</strong> Kita telah berhasil menggabungkan dataset dari dua kampus berbeda. Dataset gabungan kita sekarang memiliki:</p>
<ul>
<li>
<strong>779 baris</strong> (400 dari UIN RIL + 379 dari UBL)</li>
<li>
<strong>19 kolom</strong> yang sudah diseragamkan namanya</li>
<li>Sudah siap untuk analisis lebih lanjut!</li>
</ul>
</div>
<div id="aktivitas-mandiri-3-menggabungkan-data-uinril-dan-itera-stp-1.3-stp-1.4" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 3: Menggabungkan Data UINRIL dan ITERA <span class="capaian">STP-1.3, STP-1.4</span><a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-3-menggabungkan-data-uinril-dan-itera-stp-1.3-stp-1.4"><i class="fas fa-link"></i></a>
</h3>
<p>Melanjutkan dari aktivitas mandiri sebelumnya, gabungkan data responden dari UINRIL yang sudah kita siapkan (<code>data_uinril_subset</code>) dengan data mahasiswa ITERA.</p>
<p><strong>Langkah-langkah:</strong></p>
<ol style="list-style-type: decimal">
<li>
<strong>Impor data dari sheet ITERA</strong> menggunakan <code><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx()</a></code>
<ul>
<li>Buka kembali file Excel asal dan impor dataset ITERA dari <em>sheet</em> <code>DataUtama_mhsITERA</code> ke variabel <code>data_itera_lat</code>.</li>
</ul>
</li>
<li>
<strong>Seleksi kolom yang sesuai</strong> menggunakan <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>
<ul>
<li>Gunakan <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code> untuk mengecek nama variabel pada hasil impor di Langkah 1.</li>
<li>Pilihlah 6 kolom yang maknanya bersesuaian dengan variabel kita pada aktivitas sebelumnya (yakni: kampus, jenis kelamin, kepemilikan mobil, motor, sepeda, dan jarak).</li>
<li>
<em>Penting</em>: Urutan kolom yang diseleksi harus sejajar dengan urutan nama di <code>kolom_final</code> pada aktivitas mandiri sebelumnya.</li>
</ul>
</li>
<li>
<strong>Ganti nama kolom</strong> menggunakan fungsi <code><a href="https://rdrr.io/r/base/colnames.html">colnames()</a></code>
<ul>
<li>Timpa nama kolom dataset ITERA yang sudah diseleksi pada Langkah 2 tadi dengan vektor <code>kolom_final</code> dari aktivitas mandiri sebelumnya.</li>
<li>Simpan hasil akhirnya ke dalam variabel <code>data_itera_subset</code>.</li>
</ul>
</li>
<li>
<strong>Gabungkan dengan <code><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows()</a></code></strong>
<ul>
<li>Gabungkan <code>data_uinril_subset</code> dengan <code>data_itera_subset</code> menggunakan <code><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows()</a></code>.</li>
<li>Simpan set data dari hasil gabungan ini ke variabel <code>data_gabungan_iterauinril</code>.</li>
</ul>
</li>
</ol>
<p><strong>Analisis [STP-1.3]:</strong></p>
<ol style="list-style-type: decimal">
<li>Berapa jumlah <strong>variabel</strong> (kolom) dalam data gabungan (<code>data_gabungan_iterauinril</code>)?</li>
<li>Berapa jumlah <strong>objek</strong> (baris) dalam data gabungan?</li>
<li>Tampilkan bukti dengan menjalankan perintah <code>glimpse(data_gabungan_iterauinril)</code>.</li>
</ol>
<p><strong>Refleksi:</strong>
- Apa tantangan terbesar yang Anda hadapi dalam menggabungkan data?
- Mengapa penting untuk mengecek atau menyeragamkan tipe data sebelum menggabungkan dataset?</p>
</div>
<div id="mengekspor-set-data-hasil-pengolahan-ke-fail-file-terpisah" class="section level3" number="1.3.9">
<h3>
<span class="header-section-number">1.3.9</span> Mengekspor Set Data Hasil Pengolahan ke Fail <em>(File)</em> Terpisah<a class="anchor" aria-label="anchor" href="#mengekspor-set-data-hasil-pengolahan-ke-fail-file-terpisah"><i class="fas fa-link"></i></a>
</h3>
<p>Dalam dunia data sains dikenal jenis fail <code>.csv</code> yang merupakan singkatan dari <strong><em>comma-separated values</em></strong>. Fail ini menyimpan nilai-nilai dalam bentuk teks biasa yang dipisahkan oleh koma (<em>comma-separated</em>) sehingga dapat dibaca sebagai tabel.</p>
<div class="rmdnote">
<p>Teks biasa:</p>
<pre><code>Nama, umur
Ifna, 20
Salbina, 21</code></pre>
<p>Ketika dibaca menjadi:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th>Nama</th>
<th>umur</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Ifna</td>
<td>20</td>
</tr>
<tr class="even">
<td>Salbina</td>
<td>21</td>
</tr>
</tbody>
</table></div>
</div>
<p>Selain tanda koma, tanda titik-koma (<code>;</code>) juga sering dipakai untuk menjadi pemisah nilai. Tanda ini biasanya dipakai pada fail yang menggunakan koma sebagai pemisah desimal, seperti di Indonesia, agar tanda koma tidak dibaca sebagai pemisah.</p>
<div class="rmdnote">
<pre><code>Nama; jarak
Ifna; 2,01
Salbina; 19,7</code></pre>
<p>Dibaca menjadi:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th>Nama</th>
<th>jarak</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Ifna</td>
<td>2,01</td>
</tr>
<tr class="even">
<td>Salbina</td>
<td>19,7</td>
</tr>
</tbody>
</table></div>
</div>
<p>Cara mengekspor dataset hasil pengolahan kita ke format CSV adalah dengan menggunakan perintah <code><a href="https://rdrr.io/r/utils/write.table.html">write.csv()</a></code> atau <code><a href="https://rdrr.io/r/utils/write.table.html">write.csv2()</a></code>.</p>
<p>Penggunaan keduanya sangat ketat dan harus dipatuhi agar file tidak sulit dibaca oleh komputer lain ke depannya:</p>
<ul>
<li><p><code><a href="https://rdrr.io/r/utils/write.table.html">write.csv()</a></code> akan menulis fail csv dengan <strong>titik sebagai pemisah desimal</strong> dan <strong>koma sebagai pemisah sel</strong>.</p></li>
<li><p><code><a href="https://rdrr.io/r/utils/write.table.html">write.csv2()</a></code> akan menulis fail csv dengan <strong>koma sebagai pemisah desimal</strong> dan <strong>titi-koma sebagai pemisah sel</strong>.</p></li>
</ul>
<p>Kita dapat mengekspor set data hasil pengolahan kita menjadi fail dengan format data terstruktur seperti <code>.csv</code> atau Excel (<code>.xls</code>, <code>.xlsx</code>) dengan fungsi <code><a href="https://rdrr.io/r/utils/write.table.html">write.csv2()</a></code> atau <code><a href="https://rdrr.io/pkg/openxlsx/man/write.xlsx.html">write.xlsx()</a></code>.</p>
<p>Format perintah fungsi-fungsi ini adalah:</p>
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv2</a></span><span class="op">(</span><span class="va">variabel_dataset</span>, <span class="st">"nama_file_ekspor.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/openxlsx/man/write.xlsx.html">write.xlsx</a></span><span class="op">(</span><span class="va">variabel_dataset</span>, <span class="st">"nama_file_ekspor.xlsx"</span><span class="op">)</span></span></code></pre></div>
<p>Seluruh fail yang diekspor lokasi direktorinya <strong>sama seperti lokasi file .Rproj</strong> kita.</p>
<div id="mengekspor-set-data-ke-fail-.csv" class="section level4" number="1.3.9.1">
<h4>
<span class="header-section-number">1.3.9.1</span> Mengekspor set data ke fail <code>.csv</code><a class="anchor" aria-label="anchor" href="#mengekspor-set-data-ke-fail-.csv"><i class="fas fa-link"></i></a>
</h4>
<p>Terdapat dua jenis fungsi untuk mengekspor set data ke fail <code>.csv</code>: <code><a href="https://rdrr.io/r/utils/write.table.html">write.csv()</a></code> dan <code><a href="https://rdrr.io/r/utils/write.table.html">write.csv2()</a></code>. Perbedaan antara keduanya adalah <strong>pemisah nilainya</strong>.</p>
<p>Fungsi <code><a href="https://rdrr.io/r/utils/write.table.html">write.csv()</a></code> digunakan untuk set data yang menggunakan <strong>tanda titik</strong> sebagai pemisah desimal, sehingga pemisahnya adalah <strong>tanda koma (,)</strong>. Ini adalah format yang biasa dipakai di Amerika Utara.</p>
<p>Sementara itu, <code><a href="https://rdrr.io/r/utils/write.table.html">write.csv2()</a></code> menggunakan pemisah <strong>titik-koma (;)</strong> <em>(semicolon)</em>. Ini digunakan untuk set data yang pemisah desimalnya adalah <strong>tanda koma</strong>.</p>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mengekspor data_gabungan dalam format csv</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv2</a></span><span class="op">(</span><span class="va">data_gabungan</span>, <span class="st">"Data UINRIL &amp; UBL.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="mengekspor-set-data-ke-fail-.xlsx" class="section level4" number="1.3.9.2">
<h4>
<span class="header-section-number">1.3.9.2</span> Mengekspor set data ke fail <code>.xlsx</code><a class="anchor" aria-label="anchor" href="#mengekspor-set-data-ke-fail-.xlsx"><i class="fas fa-link"></i></a>
</h4>
<p>Sama seperti write.csv2(), fungsi write.xlsx() juga mengikuti format yang sama.</p>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/openxlsx/man/write.xlsx.html">write.xlsx</a></span><span class="op">(</span><span class="va">data_gabungan</span>, <span class="st">"Data UINRIL &amp; UBL.xlsx"</span><span class="op">)</span></span></code></pre></div>
<p>Jika kita ingin mengekspor fail ke dalam suatu direktori yang sudah ada, misalnya <code>dir-saya</code>, maka kita bisa menambahkan nama direktori tersebut sebelum nama failnya.</p>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mengekspor data_gabungan ke dalam direktori dir-saya</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv2</a></span><span class="op">(</span><span class="va">data_gabungan</span>, <span class="st">"dir-saya/Data UINRIL &amp; UBL.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
</div>
<div id="aktivitas-mandiri-4-mengekspor-set-data-gabungan-stp-1.3-stp-1.4" class="section level3 unnumbered rmdexercise">
<h3>Aktivitas Mandiri 4: Mengekspor Set Data Gabungan <span class="capaian">STP-1.3, STP-1.4</span><a class="anchor" aria-label="anchor" href="#aktivitas-mandiri-4-mengekspor-set-data-gabungan-stp-1.3-stp-1.4"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Simpan ke file</strong>
- Ekspor hasil gabungan dengan <code><a href="https://rdrr.io/pkg/openxlsx/man/write.xlsx.html">write.xlsx()</a></code>
- Nama file: <code>Prak1_[NIM]_[Nama].xlsx</code>
- Pastikan direktori file hasil ekspor ada di direktori <code>output</code>.</p>
</div>
<hr>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="pengenalan-teknis-r.html">Pengenalan Teknis R</a></div>
<div class="next"><a href="analisis-statistika-deskriptif.html"><span class="header-section-number">2</span> Analisis Statistika Deskriptif</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#modul-1"><span class="header-section-number">1</span> Pengolahan Data Terstruktur</a></li>
<li><a class="nav-link" href="#mengimpor-set-data-dataset-dari-excel"><span class="header-section-number">1.1</span> Mengimpor set data (dataset) dari Excel</a></li>
<li>
<a class="nav-link" href="#analisis-data-terstruktur-pada-set-data"><span class="header-section-number">1.2</span> Analisis data terstruktur pada set data</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#aktivitas-mandiri-1-menganalisis-struktur-data-stp-1.3">Aktivitas Mandiri 1: Menganalisis Struktur Data STP-1.3</a></li></ul>
</li>
<li>
<a class="nav-link" href="#mengolah-set-data"><span class="header-section-number">1.3</span> Mengolah set data</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#merancang-algoritma-urutan-kerja"><span class="header-section-number">1.3.1</span> Merancang Algoritma (Urutan kerja)</a></li>
<li><a class="nav-link" href="#mengidentifikasi-nama-nama-kolom"><span class="header-section-number">1.3.2</span> Mengidentifikasi Nama-nama Kolom</a></li>
<li><a class="nav-link" href="#menentukan-kolom-kolom-yang-akan-diambil-di-set-data-baru"><span class="header-section-number">1.3.3</span> Menentukan Kolom-kolom yang Akan Diambil di Set Data Baru</a></li>
<li><a class="nav-link" href="#menyeleksi-kolom-kolom-yang-akan-dipakai"><span class="header-section-number">1.3.4</span> Menyeleksi Kolom-kolom Yang Akan Dipakai</a></li>
<li><a class="nav-link" href="#mengubah-nama-kolom-menjadi-nama-standar"><span class="header-section-number">1.3.5</span> Mengubah Nama Kolom Menjadi Nama Standar</a></li>
<li><a class="nav-link" href="#aktivitas-mandiri-2-seleksi-dan-rename-kolom-stp-1.4">Aktivitas Mandiri 2: Seleksi dan Rename Kolom STP-1.4</a></li>
<li><a class="nav-link" href="#menyatukan-kedua-set-data"><span class="header-section-number">1.3.6</span> Menyatukan Kedua Set Data</a></li>
<li><a class="nav-link" href="#memperbaiki-set-data-yang-akan-digabungkan"><span class="header-section-number">1.3.7</span> Memperbaiki Set Data yang Akan Digabungkan</a></li>
<li><a class="nav-link" href="#menyatukan-kedua-set-data-setelah-diperbaiki"><span class="header-section-number">1.3.8</span> Menyatukan Kedua Set Data Setelah Diperbaiki</a></li>
<li><a class="nav-link" href="#aktivitas-mandiri-3-menggabungkan-data-uinril-dan-itera-stp-1.3-stp-1.4">Aktivitas Mandiri 3: Menggabungkan Data UINRIL dan ITERA STP-1.3, STP-1.4</a></li>
<li><a class="nav-link" href="#mengekspor-set-data-hasil-pengolahan-ke-fail-file-terpisah"><span class="header-section-number">1.3.9</span> Mengekspor Set Data Hasil Pengolahan ke Fail (File) Terpisah</a></li>
<li><a class="nav-link" href="#aktivitas-mandiri-4-mengekspor-set-data-gabungan-stp-1.3-stp-1.4">Aktivitas Mandiri 4: Mengekspor Set Data Gabungan STP-1.3, STP-1.4</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Modul Praktik Statistika Untuk Perencanaan</strong>: Penggunaan R dalam Pengolahan Data Kuantitatif" was written by Team Teaching Statistika Untuk Perencanaan, PWK ITERA. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
