<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Modul-8: Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda | Modul Praktik Statistika Untuk Perencanaan</title>
  <meta name="description" content="8 Modul-8: Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda | Modul Praktik Statistika Untuk Perencanaan" />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Modul-8: Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda | Modul Praktik Statistika Untuk Perencanaan" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Modul-8: Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda | Modul Praktik Statistika Untuk Perencanaan" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"/>
<link rel="next" href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Pengantar</a></li>
<li class="chapter" data-level="" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html"><i class="fa fa-check"></i>Pengenalan R dan RStudio</a>
<ul>
<li class="chapter" data-level="0.1" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html#apa-itu-r"><i class="fa fa-check"></i><b>0.1</b> Apa itu R?</a></li>
<li class="chapter" data-level="0.2" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html#mengapa-menggunakan-r"><i class="fa fa-check"></i><b>0.2</b> Mengapa Menggunakan R?</a></li>
<li class="chapter" data-level="0.3" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html#apa-itu-rstudio"><i class="fa fa-check"></i><b>0.3</b> Apa itu RStudio?</a></li>
<li class="chapter" data-level="0.4" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html#instalasi-r-dan-rstudio"><i class="fa fa-check"></i><b>0.4</b> Instalasi R dan RStudio</a></li>
<li class="chapter" data-level="0.5" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html#cara-menjalankan-r"><i class="fa fa-check"></i><b>0.5</b> Cara Menjalankan R</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html#langsung-di-console"><i class="fa fa-check"></i><b>0.5.1</b> Langsung di <em>Console</em></a></li>
<li class="chapter" data-level="0.5.2" data-path="pengenalan-r-dan-rstudio.html"><a href="pengenalan-r-dan-rstudio.html#menggunakan-file-kode-sumber"><i class="fa fa-check"></i><b>0.5.2</b> Menggunakan <em>File</em> Kode Sumber</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html"><i class="fa fa-check"></i>Pengenalan Teknis R</a>
<ul>
<li class="chapter" data-level="0.6" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#pengaturan-direktori"><i class="fa fa-check"></i><b>0.6</b> Pengaturan Direktori</a>
<ul>
<li class="chapter" data-level="0.6.1" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#struktur-direktori-yang-ideal"><i class="fa fa-check"></i><b>0.6.1</b> Struktur Direktori yang Ideal</a></li>
<li class="chapter" data-level="0.6.2" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#membuat-dan-mengatur-direktori-praktikum"><i class="fa fa-check"></i><b>0.6.2</b> Membuat dan Mengatur Direktori Praktikum</a></li>
<li class="chapter" data-level="0.6.3" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#mengunduh-dataset-praktikum-dari-github"><i class="fa fa-check"></i><b>0.6.3</b> Mengunduh Dataset Praktikum dari GitHub</a></li>
</ul></li>
<li class="chapter" data-level="0.7" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#sintaks-dasar-bahasa-r"><i class="fa fa-check"></i><b>0.7</b> Sintaks Dasar Bahasa R</a>
<ul>
<li class="chapter" data-level="0.7.1" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#komentar"><i class="fa fa-check"></i><b>0.7.1</b> Komentar</a></li>
<li class="chapter" data-level="0.7.2" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#variabel"><i class="fa fa-check"></i><b>0.7.2</b> Variabel</a></li>
<li class="chapter" data-level="0.7.3" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#konvensi-penamaan-dalam-r"><i class="fa fa-check"></i><b>0.7.3</b> Konvensi Penamaan dalam R</a></li>
</ul></li>
<li class="chapter" data-level="0.8" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#paket-packages"><i class="fa fa-check"></i><b>0.8</b> Paket (<em>Packages</em>)</a></li>
<li class="chapter" data-level="0.9" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#fungsi-functions"><i class="fa fa-check"></i><b>0.9</b> Fungsi (<em>Functions</em>)</a>
<ul>
<li class="chapter" data-level="0.9.1" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#menggunakan-fungsi"><i class="fa fa-check"></i><b>0.9.1</b> Menggunakan Fungsi</a></li>
<li class="chapter" data-level="0.9.2" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#membuat-fungsi-sendiri"><i class="fa fa-check"></i><b>0.9.2</b> Membuat Fungsi Sendiri</a></li>
</ul></li>
<li class="chapter" data-level="0.10" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#struktur-data-dasar"><i class="fa fa-check"></i><b>0.10</b> Struktur Data Dasar</a>
<ul>
<li class="chapter" data-level="0.10.1" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#vektor"><i class="fa fa-check"></i><b>0.10.1</b> Vektor</a></li>
<li class="chapter" data-level="0.10.2" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#list"><i class="fa fa-check"></i><b>0.10.2</b> List</a></li>
<li class="chapter" data-level="0.10.3" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#tipe-data"><i class="fa fa-check"></i><b>0.10.3</b> Tipe Data</a></li>
<li class="chapter" data-level="0.10.4" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#data-frame-dan-tibble"><i class="fa fa-check"></i><b>0.10.4</b> Data Frame dan Tibble</a></li>
</ul></li>
<li class="chapter" data-level="0.11" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#operator-pipa"><i class="fa fa-check"></i><b>0.11</b> Operator Pipa (<code>|&gt;</code>)</a></li>
<li class="chapter" data-level="0.12" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#manajemen-data-inputoutput"><i class="fa fa-check"></i><b>0.12</b> Manajemen Data (Input/Output)</a>
<ul>
<li class="chapter" data-level="0.12.1" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#membaca-data"><i class="fa fa-check"></i><b>0.12.1</b> Membaca Data</a></li>
<li class="chapter" data-level="0.12.2" data-path="pengenalan-teknis-r.html"><a href="pengenalan-teknis-r.html#menyimpan-data"><i class="fa fa-check"></i><b>0.12.2</b> Menyimpan Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="modul-1.html"><a href="modul-1.html"><i class="fa fa-check"></i><b>1</b> Modul-1: Pengolahan Data Terstruktur</a>
<ul>
<li class="chapter" data-level="1.1" data-path="modul-1.html"><a href="modul-1.html#mengimpor-set-data-dataset-dari-excel"><i class="fa fa-check"></i><b>1.1</b> Mengimpor set data <em>(dataset)</em> dari Excel</a></li>
<li class="chapter" data-level="1.2" data-path="modul-1.html"><a href="modul-1.html#analisis-data-terstruktur-pada-set-data"><i class="fa fa-check"></i><b>1.2</b> Analisis data terstruktur pada set data</a></li>
<li class="chapter" data-level="1.3" data-path="modul-1.html"><a href="modul-1.html#mengolah-set-data"><i class="fa fa-check"></i><b>1.3</b> Mengolah set data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="modul-1.html"><a href="modul-1.html#merancang-algoritma-urutan-kerja"><i class="fa fa-check"></i><b>1.3.1</b> Merancang Algoritma (Urutan kerja)</a></li>
<li class="chapter" data-level="1.3.2" data-path="modul-1.html"><a href="modul-1.html#mengidentifikasi-nama-nama-kolom"><i class="fa fa-check"></i><b>1.3.2</b> Mengidentifikasi Nama-nama Kolom</a></li>
<li class="chapter" data-level="1.3.3" data-path="modul-1.html"><a href="modul-1.html#menentukan-kolom-kolom-yang-akan-diambil-di-set-data-baru"><i class="fa fa-check"></i><b>1.3.3</b> Menentukan Kolom-kolom yang Akan Diambil di Set Data Baru</a></li>
<li class="chapter" data-level="1.3.4" data-path="modul-1.html"><a href="modul-1.html#menyeleksi-kolom-kolom-yang-akan-dipakai"><i class="fa fa-check"></i><b>1.3.4</b> Menyeleksi Kolom-kolom Yang Akan Dipakai</a></li>
<li class="chapter" data-level="1.3.5" data-path="modul-1.html"><a href="modul-1.html#mengubah-nama-kolom-menjadi-nama-standar"><i class="fa fa-check"></i><b>1.3.5</b> Mengubah Nama Kolom Menjadi Nama Standar</a></li>
<li class="chapter" data-level="1.3.6" data-path="modul-1.html"><a href="modul-1.html#menyatukan-kedua-set-data"><i class="fa fa-check"></i><b>1.3.6</b> Menyatukan Kedua Set Data</a></li>
<li class="chapter" data-level="1.3.7" data-path="modul-1.html"><a href="modul-1.html#memperbaiki-set-data-yang-akan-digabungkan"><i class="fa fa-check"></i><b>1.3.7</b> Memperbaiki Set Data yang Akan Digabungkan</a></li>
<li class="chapter" data-level="1.3.8" data-path="modul-1.html"><a href="modul-1.html#menyatukan-kedua-set-data-setelah-diperbaiki"><i class="fa fa-check"></i><b>1.3.8</b> Menyatukan Kedua Set Data Setelah Diperbaiki</a></li>
<li class="chapter" data-level="1.3.9" data-path="modul-1.html"><a href="modul-1.html#mengekspor-set-data-hasil-pengolahan-ke-fail-file-terpisah"><i class="fa fa-check"></i><b>1.3.9</b> Mengekspor Set Data Hasil Pengolahan ke Fail <em>(File)</em> Terpisah</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modul-2-analisis-statistika-deskriptif.html"><a href="modul-2-analisis-statistika-deskriptif.html"><i class="fa fa-check"></i><b>2</b> Modul-2: Analisis Statistika Deskriptif</a>
<ul>
<li class="chapter" data-level="2.1" data-path="modul-2-analisis-statistika-deskriptif.html"><a href="modul-2-analisis-statistika-deskriptif.html#persiapan"><i class="fa fa-check"></i><b>2.1</b> Persiapan</a></li>
<li class="chapter" data-level="2.2" data-path="modul-2-analisis-statistika-deskriptif.html"><a href="modul-2-analisis-statistika-deskriptif.html#mengimpor-dataset"><i class="fa fa-check"></i><b>2.2</b> Mengimpor Dataset</a></li>
<li class="chapter" data-level="2.3" data-path="modul-2-analisis-statistika-deskriptif.html"><a href="modul-2-analisis-statistika-deskriptif.html#merapikan-dataset-data-wrangling"><i class="fa fa-check"></i><b>2.3</b> Merapikan Dataset <em>(Data Wrangling)</em></a></li>
<li class="chapter" data-level="2.4" data-path="modul-2-analisis-statistika-deskriptif.html"><a href="modul-2-analisis-statistika-deskriptif.html#analisis-statistika-deskriptif"><i class="fa fa-check"></i><b>2.4</b> Analisis Statistika Deskriptif</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="modul-2-analisis-statistika-deskriptif.html"><a href="modul-2-analisis-statistika-deskriptif.html#variabel-kategoris"><i class="fa fa-check"></i><b>2.4.1</b> Variabel Kategoris</a></li>
<li class="chapter" data-level="2.4.2" data-path="modul-2-analisis-statistika-deskriptif.html"><a href="modul-2-analisis-statistika-deskriptif.html#variabel-numerik"><i class="fa fa-check"></i><b>2.4.2</b> Variabel Numerik</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html"><i class="fa fa-check"></i><b>3</b> Modul-3: Visualisasi Data Kuantitatif</a>
<ul>
<li class="chapter" data-level="3.1" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#visualisasi-data-dengan-ggplot2"><i class="fa fa-check"></i><b>3.1</b> Visualisasi Data dengan <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#mengimpor-library-mengatur-dataset"><i class="fa fa-check"></i><b>3.1.1</b> Mengimpor <em>Library</em> &amp; Mengatur Dataset</a></li>
<li class="chapter" data-level="3.1.2" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#tata-tulis-grafik-grammar-of-graphics"><i class="fa fa-check"></i><b>3.1.2</b> Tata Tulis Grafik <em>(Grammar of Graphics)</em></a></li>
<li class="chapter" data-level="3.1.3" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#praktik-visualisasi-data"><i class="fa fa-check"></i><b>3.1.3</b> Praktik Visualisasi Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#diagram-lollipop"><i class="fa fa-check"></i><b>3.1.4</b> Diagram Lollipop</a></li>
<li class="chapter" data-level="3.1.5" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#diagram-paidonat-piedonut-chart"><i class="fa fa-check"></i><b>3.1.5</b> Diagram Pai/Donat <em>(Pie/Donut Chart)</em></a></li>
<li class="chapter" data-level="3.1.6" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#diagram-treemap"><i class="fa fa-check"></i><b>3.1.6</b> Diagram <em>Treemap</em></a></li>
<li class="chapter" data-level="3.1.7" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#histogram"><i class="fa fa-check"></i><b>3.1.7</b> Histogram</a></li>
<li class="chapter" data-level="3.1.8" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#boxplot"><i class="fa fa-check"></i><b>3.1.8</b> <em>Boxplot</em></a></li>
<li class="chapter" data-level="3.1.9" data-path="modul-3-visualisasi-data-kuantitatif.html"><a href="modul-3-visualisasi-data-kuantitatif.html#grafik-pencar-scatter-plot"><i class="fa fa-check"></i><b>3.1.9</b> Grafik Pencar <em>(Scatter Plot)</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><i class="fa fa-check"></i><b>4</b> Modul-4: Distribusi Sampling dan Interval Kepercayaan</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#pendahuluan"><i class="fa fa-check"></i><b>4.1</b> Pendahuluan</a></li>
<li class="chapter" data-level="4.2" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#perangkat-lunak-dan-pustaka-libraries"><i class="fa fa-check"></i><b>4.2</b> Perangkat Lunak dan Pustaka (Libraries)</a></li>
<li class="chapter" data-level="4.3" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#memuat-dan-mempersiapkan-data"><i class="fa fa-check"></i><b>4.3</b> Memuat dan Mempersiapkan Data</a></li>
<li class="chapter" data-level="4.4" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#distribusi-sampling-dan-standard-error"><i class="fa fa-check"></i><b>4.4</b> Distribusi <em>Sampling</em> dan <em>Standard Error</em></a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#mendefinisikan-parameter-populasi"><i class="fa fa-check"></i><b>4.4.1</b> Mendefinisikan Parameter Populasi</a></li>
<li class="chapter" data-level="4.4.2" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#simulasi-pengambilan-sampel"><i class="fa fa-check"></i><b>4.4.2</b> Simulasi Pengambilan Sampel</a></li>
<li class="chapter" data-level="4.4.3" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#visualisasi-distribusi-sampling"><i class="fa fa-check"></i><b>4.4.3</b> Visualisasi Distribusi Sampling</a></li>
<li class="chapter" data-level="4.4.4" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#menghitung-standard-error-se"><i class="fa fa-check"></i><b>4.4.4</b> Menghitung <em>Standard Error</em> (SE)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#estimasi-parameter-1-interval-kepercayaan-rata-rata"><i class="fa fa-check"></i><b>4.5</b> Estimasi Parameter-1: Interval Kepercayaan Rata-rata</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#mengambil-satu-sampel"><i class="fa fa-check"></i><b>4.5.1</b> Mengambil Satu Sampel</a></li>
<li class="chapter" data-level="4.5.2" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#menghasilkan-interval-kepercayaan"><i class="fa fa-check"></i><b>4.5.2</b> Menghasilkan Interval Kepercayaan</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#estimasi-parameter-2-interval-kepercayaan-proporsi"><i class="fa fa-check"></i><b>4.6</b> Estimasi Parameter-2: Interval Kepercayaan Proporsi</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#parameter-proporsi"><i class="fa fa-check"></i><b>4.6.1</b> Parameter Proporsi</a></li>
<li class="chapter" data-level="4.6.2" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#mengambil-satu-sampel-dan-menghitung-proporsinya"><i class="fa fa-check"></i><b>4.6.2</b> Mengambil Satu Sampel dan Menghitung Proporsinya</a></li>
<li class="chapter" data-level="4.6.3" data-path="modul-4-distribusi-sampling-dan-interval-kepercayaan.html"><a href="modul-4-distribusi-sampling-dan-interval-kepercayaan.html#menghasilkan-interval-kepercayaan-untuk-proporsi"><i class="fa fa-check"></i><b>4.6.3</b> Menghasilkan Interval Kepercayaan untuk Proporsi</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html"><i class="fa fa-check"></i><b>5</b> Modul-5: Uji Hipotesis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#pendahuluan-1"><i class="fa fa-check"></i><b>5.1</b> Pendahuluan</a></li>
<li class="chapter" data-level="5.2" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#perangkat-lunak-dan-pustaka-libraries-1"><i class="fa fa-check"></i><b>5.2</b> Perangkat Lunak dan Pustaka (Libraries)</a></li>
<li class="chapter" data-level="5.3" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#memuat-data"><i class="fa fa-check"></i><b>5.3</b> Memuat Data</a></li>
<li class="chapter" data-level="5.4" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#perkenalan-markdown-latex"><i class="fa fa-check"></i><b>5.4</b> Perkenalan Markdown: LaTeX</a></li>
<li class="chapter" data-level="5.5" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#uji-hipotesis-satu-populasi"><i class="fa fa-check"></i><b>5.5</b> Uji Hipotesis Satu Populasi</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#rata-rata"><i class="fa fa-check"></i><b>5.5.1</b> Rata-rata</a></li>
<li class="chapter" data-level="5.5.2" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#memahami-distribusi-normal-dan-area-kritis"><i class="fa fa-check"></i><b>5.5.2</b> Memahami Distribusi Normal dan Area Kritis</a></li>
<li class="chapter" data-level="5.5.3" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#proporsi"><i class="fa fa-check"></i><b>5.5.3</b> Proporsi</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#uji-hipotesis-2-populasi-independen"><i class="fa fa-check"></i><b>5.6</b> Uji Hipotesis 2 Populasi Independen</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#rata-rata-1"><i class="fa fa-check"></i><b>5.6.1</b> Rata-rata</a></li>
<li class="chapter" data-level="5.6.2" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#proporsi-1"><i class="fa fa-check"></i><b>5.6.2</b> Proporsi</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#uji-hipotesis-2-populasi-dependen"><i class="fa fa-check"></i><b>5.7</b> Uji Hipotesis 2 Populasi Dependen</a></li>
<li class="chapter" data-level="5.8" data-path="modul-5-uji-hipotesis.html"><a href="modul-5-uji-hipotesis.html#soal-latihan"><i class="fa fa-check"></i><b>5.8</b> Soal Latihan</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><i class="fa fa-check"></i><b>6</b> Modul-6: Analisis Hubungan Korelatif: Korelasi Variabel Nominal dan Ordinal</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html#pendahuluan-2"><i class="fa fa-check"></i><b>6.1</b> Pendahuluan</a></li>
<li class="chapter" data-level="6.2" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html#pustaka-libraries-yang-diperlukan-dan-memuat-data"><i class="fa fa-check"></i><b>6.2</b> Pustaka <em>(Libraries)</em> yang Diperlukan dan Memuat Data</a></li>
<li class="chapter" data-level="6.3" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html#pembuatan-tabel-silang"><i class="fa fa-check"></i><b>6.3</b> Pembuatan Tabel Silang</a></li>
<li class="chapter" data-level="6.4" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html#analisis-korelasi-antarvariabel-nominal"><i class="fa fa-check"></i><b>6.4</b> Analisis Korelasi Antarvariabel Nominal</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html#koefisien-korelasi-variabel-nominal-berbasis-chi2"><i class="fa fa-check"></i><b>6.4.1</b> Koefisien Korelasi Variabel Nominal Berbasis <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="6.4.2" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html#koefisien-korelasi-variabel-nominal-berbasis-error"><i class="fa fa-check"></i><b>6.4.2</b> Koefisien Korelasi Variabel Nominal Berbasis <em>Error</em></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html"><a href="modul-6-analisis-hubungan-korelatif-korelasi-variabel-nominal-dan-ordinal.html#analisis-korelasi-antarvariabel-ordinal"><i class="fa fa-check"></i><b>6.5</b> Analisis Korelasi Antarvariabel Ordinal</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><a href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><i class="fa fa-check"></i><b>7</b> Modul-7: Analisis Hubungan Korelatif: Korelasi Variabel Metrik</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><a href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html#pendahuluan-3"><i class="fa fa-check"></i><b>7.1</b> Pendahuluan</a></li>
<li class="chapter" data-level="7.2" data-path="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><a href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html#pustaka-libraries-yang-diperlukan-dan-memuat-data-1"><i class="fa fa-check"></i><b>7.2</b> Pustaka <em>(Libraries)</em> yang Diperlukan dan Memuat Data</a></li>
<li class="chapter" data-level="7.3" data-path="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><a href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html#pola-hubungan-data"><i class="fa fa-check"></i><b>7.3</b> Pola Hubungan Data</a></li>
<li class="chapter" data-level="7.4" data-path="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><a href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html#analisis-korelasi-spearmans-rho"><i class="fa fa-check"></i><b>7.4</b> Analisis Korelasi Spearman’s <span class="math inline">\(\rho\)</span></a></li>
<li class="chapter" data-level="7.5" data-path="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html"><a href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html#analisis-korelasi-pearsons-r"><i class="fa fa-check"></i><b>7.5</b> Analisis Korelasi Pearson’s <em>r</em></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><i class="fa fa-check"></i><b>8</b> Modul-8: Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda</a>
<ul>
<li class="chapter" data-level="8.1" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#pendahuluan-4"><i class="fa fa-check"></i><b>8.1</b> Pendahuluan</a></li>
<li class="chapter" data-level="8.2" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penjelasan-kasus"><i class="fa fa-check"></i><b>8.2</b> Penjelasan Kasus</a></li>
<li class="chapter" data-level="8.3" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#memuat-pustaka-libraries-yang-diperlukan"><i class="fa fa-check"></i><b>8.3</b> Memuat Pustaka <em>(Libraries)</em> yang Diperlukan</a></li>
<li class="chapter" data-level="8.4" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#memuat-dataset"><i class="fa fa-check"></i><b>8.4</b> Memuat Dataset</a></li>
<li class="chapter" data-level="8.5" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#pola-hubungan-data-1"><i class="fa fa-check"></i><b>8.5</b> Pola Hubungan Data</a></li>
<li class="chapter" data-level="8.6" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#model-regresi-linear-sederhana"><i class="fa fa-check"></i><b>8.6</b> Model Regresi Linear Sederhana</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penyusunan-model"><i class="fa fa-check"></i><b>8.6.1</b> Penyusunan Model</a></li>
<li class="chapter" data-level="8.6.2" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penampilan-model"><i class="fa fa-check"></i><b>8.6.2</b> Penampilan Model</a></li>
<li class="chapter" data-level="8.6.3" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penafsiraninterpretasi-model"><i class="fa fa-check"></i><b>8.6.3</b> Penafsiran/interpretasi Model</a></li>
<li class="chapter" data-level="8.6.4" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#melakukan-prediksi"><i class="fa fa-check"></i><b>8.6.4</b> Melakukan Prediksi</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#model-regresi-linear-berganda"><i class="fa fa-check"></i><b>8.7</b> Model Regresi Linear Berganda</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penjelasan-variabel-dummy"><i class="fa fa-check"></i><b>8.7.1</b> Penjelasan Variabel <em>Dummy</em></a></li>
<li class="chapter" data-level="8.7.2" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#interpretasi-variabel-dummy"><i class="fa fa-check"></i><b>8.7.2</b> Interpretasi Variabel <em>Dummy</em></a></li>
<li class="chapter" data-level="8.7.3" data-path="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html"><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#prediksi-model"><i class="fa fa-check"></i><b>8.7.3</b> Prediksi Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><i class="fa fa-check"></i><b>9</b> Modul-9: Analisis Hubungan Multivariat Interdependensi - Analisis Faktor dan PCA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#pendahuluan-5"><i class="fa fa-check"></i><b>9.1</b> Pendahuluan</a></li>
<li class="chapter" data-level="9.2" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#studi-kasus"><i class="fa fa-check"></i><b>9.2</b> Studi Kasus</a></li>
<li class="chapter" data-level="9.3" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#memuat-pustaka-libraries"><i class="fa fa-check"></i><b>9.3</b> Memuat Pustaka <em>(Libraries)</em></a></li>
<li class="chapter" data-level="9.4" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#asumsi-awal"><i class="fa fa-check"></i><b>9.4</b> Asumsi Awal</a></li>
<li class="chapter" data-level="9.5" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#mempersiapkan-data"><i class="fa fa-check"></i><b>9.5</b> Mempersiapkan Data</a></li>
<li class="chapter" data-level="9.6" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#uji-kelayakan-data-asumsi"><i class="fa fa-check"></i><b>9.6</b> Uji Kelayakan Data (Asumsi)</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#uji-bartlett-of-sphericity"><i class="fa fa-check"></i><b>9.6.1</b> Uji Bartlett of Sphericity</a></li>
<li class="chapter" data-level="9.6.2" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#uji-kmo-dan-msa"><i class="fa fa-check"></i><b>9.6.2</b> Uji KMO dan MSA</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#mengekstrak-dimensi-baru"><i class="fa fa-check"></i><b>9.7</b> Mengekstrak Dimensi Baru</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#nilai-eigen-dan-total-variansi"><i class="fa fa-check"></i><b>9.7.1</b> Nilai Eigen dan Total Variansi</a></li>
<li class="chapter" data-level="9.7.2" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#scree-plot"><i class="fa fa-check"></i><b>9.7.2</b> <em>Scree Plot</em></a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#melakukan-analisis-faktor-dan-rotasi"><i class="fa fa-check"></i><b>9.8</b> Melakukan Analisis Faktor dan Rotasi</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#analisis-faktor-common-factor-analysis"><i class="fa fa-check"></i><b>9.8.1</b> Analisis Faktor (Common Factor Analysis)</a></li>
<li class="chapter" data-level="9.8.2" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#analisis-komponen-prinsip-pca"><i class="fa fa-check"></i><b>9.8.2</b> Analisis Komponen Prinsip (PCA)</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html"><a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html#interpretasi-dan-penamaan-dimensi"><i class="fa fa-check"></i><b>9.9</b> Interpretasi dan Penamaan Dimensi</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="referensi.html"><a href="referensi.html"><i class="fa fa-check"></i><b>10</b> Referensi</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modul Praktik Statistika Untuk Perencanaan</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Modul-8: Analisis Hubungan Kausalitas: Regresi Linear Sederhana dan Berganda<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Setelah mempelajari modul ini, Anda diharapkan dapat:</p>
<ol style="list-style-type: decimal">
<li>mampu menghasilkan regresi linear sederhana dengan perangkat lunak komputer <span class="capaian">STP-13.3</span></li>
<li>mampu menghasilkan persamaan regresi linear berganda dengan perangkat lunak komputer <span class="capaian">STP-14.3</span></li>
</ol>
<hr />
<div id="pendahuluan-4" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Pendahuluan<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#pendahuluan-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Analisis regresi linear adalah analisis statistik untuk menyatakan hubungan sebab-akibat (kausalitas) antar minimal dua variabel. Analisis regresi linear yang melibatkan <em>dua variabel saja</em> (<em>satu variabel dependen</em> dan <em>satu variabel independen</em>), kita sebut sebagai <strong>regresi linear sederhana</strong>, sedangkan analisis regresi linar yang melibatkan lebih dari dua variabel (<em>satu variabel dependen</em> dan <em>lebih dari satu variabel independen</em>) kita sebut sebagai <strong>regresi linear berganda <em>(multiple linear regression)</em></strong></p>
<p>Analisis regresi linear mewajibkan tingkat pengukuran minimal untuk variabel dependennya adalah <strong>metrik</strong>. Sementara itu, variabel independennya dapat berupa metrik atau bukan (ordinal/nominal).</p>
<p>Analisis regresi linear menghasilkan persamaan yang disebut <strong>persamaan regresi linear</strong>. Bentuk umum persamaan regresi linear tersebut adalah sebagai berikut.</p>
<p><span class="math display">\[
y = β_0 + β_1x
\]</span></p>
<p>dengan</p>
<ul>
<li><span class="math inline">\(y\)</span> adalah variabel dependen (disebut juga <em>variabel respons</em> atau <em>predicted variable</em>)</li>
<li><span class="math inline">\(x\)</span> adalah variabel independen (disebut juga <em>variabel eksplanatory</em> atau <em>predictor variable</em>)</li>
<li><span class="math inline">\(\beta_0\)</span> adalah konstanta yang menjadi <em>intercept</em>, yaitu nilai <span class="math inline">\(y\)</span> ketika <span class="math inline">\(x=0\)</span></li>
<li><span class="math inline">\(\beta_1\)</span> adalah koefisien yang menyatakan seberapa besar perubahan <span class="math inline">\(y\)</span> ketika satu unit nilai <span class="math inline">\(x\)</span> berubah.</li>
</ul>
<p>Persamaan regresi linear di atas adalah untuk <strong>analisis regresi linear sederhana</strong>, yakni analisis regresi linear yang melibatkan dua variabel saja. Untuk <strong>regresi linear berganda</strong>, kita hanya perlu menambahkan pasangan <span class="math inline">\(\beta\)</span> dan <span class="math inline">\(x\)</span> lainnya, sehingga bentuk umum untuk persamaan regresi linear berganda adalah seperti berikut.</p>
<p><span class="math display">\[
y = β_0 + β_1x_1 + β_2x_2 + ... + β_kx_k
\]</span></p>
<p>dengan</p>
<ul>
<li><span class="math inline">\(x_k\)</span> adalah variabel independen ke-<span class="math inline">\(k\)</span></li>
<li><span class="math inline">\(\beta_k\)</span> adalah koefisien untuk variabel independen ke-<span class="math inline">\(k\)</span> tersebut</li>
</ul>
</div>
<div id="penjelasan-kasus" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Penjelasan Kasus<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penjelasan-kasus" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dalam praktikum kali ini, kita akan memodelkan hubungan kausal antara dua variabel metrik: <strong>jarak tempat tinggal ke kampus</strong> dan <strong>biaya perjalanan sepekan</strong> untuk mahasiswa-mahasiswi yang menggunakan <strong>kendaraan layanan online saja</strong>. Harga perjalanan menggunakan layanan <em>online</em> tentunya dipengaruhi oleh jarak tempuh kendaraan tersebut. Hubungan kausal ini menjadi kasus untuk <strong>regresi linear sederhana</strong>.</p>
<p>Untuk <strong>regresi linear berganda</strong>, kita akan melibatkan satu variabel tambahan sebagai variabel independen, yakni variabel berjenis kategoris , sehingga kita memiliki total variabel sejumlah 3 buah (1 variabel dependen, 2 variabel independen).</p>
</div>
<div id="memuat-pustaka-libraries-yang-diperlukan" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Memuat Pustaka <em>(Libraries)</em> yang Diperlukan<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#memuat-pustaka-libraries-yang-diperlukan" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Seperti biasa, kita perlu memuat pustaka <em>(libraries)</em> yang diperlukan dalam pengolahan data kita. Seperti halnya juga analisis korelasi variabel metrik, kita tidak lagi menggunakan tabel silang, tetapi kita langsung menganalisis kolom-kolom yang ada di dataset kita.</p>
</div>
<div id="memuat-dataset" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Memuat Dataset<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#memuat-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Kita akan menggunakan dataset keempat kampus di Kota Bandar Lampung dan sekitarnya sebagai bahan. Kemudian kita akan menyaring objek-objek yang memiliki nilai variabel <code>kendaraan utama</code> sama dengan <code>'Layanan online'</code>.</p>
</div>
<div id="pola-hubungan-data-1" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Pola Hubungan Data<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#pola-hubungan-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sebagai pendahuluan, kita akan mengidentifikasi kekuatan, arah, dan pola hubungan antara variabel dependen dan independen kita (biaya perjalanan sepekan dan jarak tempat tinggal-kampus). Untuk itu kita dapat menghitung koefisien korelasi untuk hubungan variabel metrik juga, yakni koefisien korelasi Pearson’s <span class="math inline">\(r\)</span>.</p>
<p>Pola hubungan akan kita analisis dengan membuat diagram pencar <em>(scatter plot)</em> antara variabel dependen dengan variabel independennya.</p>
<p><strong>Menghitung Koefisien Pearson’s</strong> <span class="math inline">\(r\)</span></p>
<p>Menghitung koefisien korelasi Pearson’s <span class="math inline">\(r\)</span> dapat kita lakukan dengan perintah <code>cor()</code> dengan atribut <code>method = "pearson"</code> setelah terlebih dahulu menyimpan nilai masing-masing variabel ke dalam suatu vektor.</p>
<pre><code>## [1] -0.1813941</code></pre>
<blockquote>
<p><strong>Jawablah:</strong> Tuliskan interpretasi kalian terhadap koefisien korelasi antara variabel jarak tempuh dengan biaya perjalanan sepekan.</p>
<p><em>Petunjuk: ulas kekuatan serta arah hubungannya serta maknai secara kontekstual ulasan tersebut</em></p>
</blockquote>
<p><strong>Membuat Diagram Pencar</strong></p>
<p>Membuat diagram pencar dapat dilakukan dengan menerapkan perintah <code>geom_point()</code> dari pustaka <code>ggplot2</code> yang dimuat bersama pustaka <code>tidyverse</code>.</p>
<p><img src="figures/mod08-create-initial-scatterplot-1.png" width="672" /></p>
<p>Setelah Anda melakukan pembuatan diagram pencar tersebut, Anda akan menyadari bahwa kita memiliki <em>outlier</em> (pencilan), yakni objek yang memiliki nilai jarak dari tempat tinggal ke kampus mencapai hampir 25 km.</p>
<p>Keberadaan pencilan ini akan mengganggu hasil analisis kita. Mari kita buktikan dengan menghilangkan data pencilan tersebut.</p>
<p>Di sini kita akan menghitung ulang nilai koefisien korelasi kita.</p>
<pre><code>## [1] -0.3086803</code></pre>
<blockquote>
<p><strong>Jawablah:</strong> Bagaimana perbedaan nilai koefisiennya?</p>
</blockquote>
<p>Kita pun dapat memeriksa hasil perbaikan dataset kita dari diagram pencar yang baru berikut.</p>
<p><img src="figures/mod08-create-clean-scatterplot-1.png" width="672" /></p>
</div>
<div id="model-regresi-linear-sederhana" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Model Regresi Linear Sederhana<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#model-regresi-linear-sederhana" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dalam bagian ini kita akan mempelajari cara menyusun, menampilkan, menafsirkan/menginterpretasi, dan memprediksi nilai variabel dependen berdasarkan model yang kita susun.</p>
<div id="penyusunan-model" class="section level3 hasAnchor" number="8.6.1">
<h3><span class="header-section-number">8.6.1</span> Penyusunan Model<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penyusunan-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Untuk membuat persamaan model regresi linear, kita akan menggunakan perintah <code>lm</code> yang sudah disediakan secara bawaan oleh R. Hasil dari perintah ini dapat kita simpan sebagai variabel tertentu.</p>
<p>Argumen yang kita gunakan adalah <code>var_dependen ~ var_independen</code> serta nama dataset yang kita gunakan. Tanda <code>~</code> (disebut <em>tilde</em>) dapat kita masukkan dengan menekan <code>Shift</code> + <code>`</code> yang ada di sebelah kiri tombol angka 1 di <em>keyboard</em> kita.</p>
<p>Sebelumnya kita sudah mendefinisikan <code>y</code> dan <code>x</code> sebagai variabel untuk vektor biaya transportasi sepekan dan vektor jarak, sehingga kita bisa langsung menggunakannya di atas. Dataset yang kita gunakan adalah dataset mahasiswa yang menggunakan layanan <em>online</em> sebagai moda transportasi utama yang kita simpan dalam <code>data_mahasiswa_online</code>.</p>
</div>
<div id="penampilan-model" class="section level3 hasAnchor" number="8.6.2">
<h3><span class="header-section-number">8.6.2</span> Penampilan Model<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penampilan-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Untuk menampilkan hasil penyusunan model regresi linear, kita akan menggunakan perintah <code>summary</code> yang juga sudah disediakan secara bawaan oleh R.</p>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = data_mahasiswa_online)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -79.255 -30.717  -3.562  26.758 120.787 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   92.557      4.598  20.129  &lt; 2e-16 ***
## x             -5.321      1.205  -4.414 1.72e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 38.11 on 185 degrees of freedom
## Multiple R-squared:  0.09528,    Adjusted R-squared:  0.09039 
## F-statistic: 19.48 on 1 and 185 DF,  p-value: 1.721e-05</code></pre>
<p>Yang ditampilkan dengan perintah tersebut antara lain adalah sebagai berikut. Penjelasan lebih lanjutnya akan diberikan di subbagian selanjutnya.</p>
<ul>
<li><p><code>Call</code> : bentuk persamaan model yang sudah kita input sebelumnya</p></li>
<li><p><code>Residuals</code> : informasi residual model</p></li>
<li><p><code>Coefficients</code> : tabel yang menunjukkan angka-angka dalam persamaan model yang dihasilkan</p></li>
<li><p>Nilai-nilai uji kualitas model seperti <code>Residual standard error</code> <em>(standard error</em> estimasi), <em>Multiple R-squared</em> dan <em>Adjusted R-squared</em> (koefisien determinasi), serta <em>F-statistic</em> (uji signifikansi model).</p></li>
</ul>
<p>Selain menggunakan <code>summary</code>, kita juga dapat menggunakan perintah <code>tbl_regression</code>, perintah yang disediakan oleh paket/<em>library</em> <code>gtsummary</code>. Hasil dari perintah ini adalah tabel yang sudah diformat sesuai dengan <em>templat</em> artikel ilmiah.</p>
<div id="gyzehufyvy" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#gyzehufyvy table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#gyzehufyvy thead, #gyzehufyvy tbody, #gyzehufyvy tfoot, #gyzehufyvy tr, #gyzehufyvy td, #gyzehufyvy th {
  border-style: none;
}

#gyzehufyvy p {
  margin: 0;
  padding: 0;
}

#gyzehufyvy .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#gyzehufyvy .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#gyzehufyvy .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#gyzehufyvy .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#gyzehufyvy .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gyzehufyvy .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gyzehufyvy .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gyzehufyvy .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#gyzehufyvy .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#gyzehufyvy .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#gyzehufyvy .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#gyzehufyvy .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#gyzehufyvy .gt_spanner_row {
  border-bottom-style: hidden;
}

#gyzehufyvy .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#gyzehufyvy .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#gyzehufyvy .gt_from_md > :first-child {
  margin-top: 0;
}

#gyzehufyvy .gt_from_md > :last-child {
  margin-bottom: 0;
}

#gyzehufyvy .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#gyzehufyvy .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#gyzehufyvy .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#gyzehufyvy .gt_row_group_first td {
  border-top-width: 2px;
}

#gyzehufyvy .gt_row_group_first th {
  border-top-width: 2px;
}

#gyzehufyvy .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gyzehufyvy .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#gyzehufyvy .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#gyzehufyvy .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gyzehufyvy .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gyzehufyvy .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#gyzehufyvy .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#gyzehufyvy .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#gyzehufyvy .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gyzehufyvy .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gyzehufyvy .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#gyzehufyvy .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gyzehufyvy .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#gyzehufyvy .gt_left {
  text-align: left;
}

#gyzehufyvy .gt_center {
  text-align: center;
}

#gyzehufyvy .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#gyzehufyvy .gt_font_normal {
  font-weight: normal;
}

#gyzehufyvy .gt_font_bold {
  font-weight: bold;
}

#gyzehufyvy .gt_font_italic {
  font-style: italic;
}

#gyzehufyvy .gt_super {
  font-size: 65%;
}

#gyzehufyvy .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#gyzehufyvy .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#gyzehufyvy .gt_indent_1 {
  text-indent: 5px;
}

#gyzehufyvy .gt_indent_2 {
  text-indent: 10px;
}

#gyzehufyvy .gt_indent_3 {
  text-indent: 15px;
}

#gyzehufyvy .gt_indent_4 {
  text-indent: 20px;
}

#gyzehufyvy .gt_indent_5 {
  text-indent: 25px;
}

#gyzehufyvy .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#gyzehufyvy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="estimate"><span class='gt_from_md'><strong>Beta</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="conf.low"><span class='gt_from_md'><strong>95% CI</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="p.value"><span class='gt_from_md'><strong>p-value</strong></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">x</td>
<td headers="estimate" class="gt_row gt_center">-5.3</td>
<td headers="conf.low" class="gt_row gt_center">-7.7, -2.9</td>
<td headers="p.value" class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  <tfoot>
    <tr class="gt_sourcenotes">
      <td class="gt_sourcenote" colspan="4"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></td>
    </tr>
  </tfoot>
</table>
</div>
<p>Jika kalian menemukan pertanyaan untuk menginstal sebuah paket di <em>console</em>, yakni <code>broom.helpers</code>, pilih saja “Yes” untuk mengunduh dan menginstalnya.</p>
<p>Secara bawaan, tabel tidak menampilkan nilai konstanta <em>(intercept)</em>, menampilkan nilai <em>confidence level</em> 95%, dan menampilkan nilai dari variabel independen sesuai variabel yang kita tetapkan sebelumnya, dalam hal ini adalah <code>x</code>. Untuk menggantinya, kita dapat melakukan penyesuaian perintah sebagai berikut.</p>
<div id="omohigndci" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#omohigndci table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#omohigndci thead, #omohigndci tbody, #omohigndci tfoot, #omohigndci tr, #omohigndci td, #omohigndci th {
  border-style: none;
}

#omohigndci p {
  margin: 0;
  padding: 0;
}

#omohigndci .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#omohigndci .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#omohigndci .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#omohigndci .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#omohigndci .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#omohigndci .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#omohigndci .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#omohigndci .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#omohigndci .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#omohigndci .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#omohigndci .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#omohigndci .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#omohigndci .gt_spanner_row {
  border-bottom-style: hidden;
}

#omohigndci .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#omohigndci .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#omohigndci .gt_from_md > :first-child {
  margin-top: 0;
}

#omohigndci .gt_from_md > :last-child {
  margin-bottom: 0;
}

#omohigndci .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#omohigndci .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#omohigndci .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#omohigndci .gt_row_group_first td {
  border-top-width: 2px;
}

#omohigndci .gt_row_group_first th {
  border-top-width: 2px;
}

#omohigndci .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#omohigndci .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#omohigndci .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#omohigndci .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#omohigndci .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#omohigndci .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#omohigndci .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#omohigndci .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#omohigndci .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#omohigndci .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#omohigndci .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#omohigndci .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#omohigndci .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#omohigndci .gt_left {
  text-align: left;
}

#omohigndci .gt_center {
  text-align: center;
}

#omohigndci .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#omohigndci .gt_font_normal {
  font-weight: normal;
}

#omohigndci .gt_font_bold {
  font-weight: bold;
}

#omohigndci .gt_font_italic {
  font-style: italic;
}

#omohigndci .gt_super {
  font-size: 65%;
}

#omohigndci .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#omohigndci .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#omohigndci .gt_indent_1 {
  text-indent: 5px;
}

#omohigndci .gt_indent_2 {
  text-indent: 10px;
}

#omohigndci .gt_indent_3 {
  text-indent: 15px;
}

#omohigndci .gt_indent_4 {
  text-indent: 20px;
}

#omohigndci .gt_indent_5 {
  text-indent: 25px;
}

#omohigndci .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#omohigndci div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="estimate"><span class='gt_from_md'><strong>Beta</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="conf.low"><span class='gt_from_md'><strong>99% CI</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="p.value"><span class='gt_from_md'><strong>p-value</strong></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">(Intercept)</td>
<td headers="estimate" class="gt_row gt_center">93</td>
<td headers="conf.low" class="gt_row gt_center">81, 105</td>
<td headers="p.value" class="gt_row gt_center"><0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Jarak tempuh ke kampus, km</td>
<td headers="estimate" class="gt_row gt_center">-5.3</td>
<td headers="conf.low" class="gt_row gt_center">-8.5, -2.2</td>
<td headers="p.value" class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  <tfoot>
    <tr class="gt_sourcenotes">
      <td class="gt_sourcenote" colspan="4"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="penafsiraninterpretasi-model" class="section level3 hasAnchor" number="8.6.3">
<h3><span class="header-section-number">8.6.3</span> Penafsiran/interpretasi Model<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penafsiraninterpretasi-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Yang kita akan tafsirkan dari model kita di antaranya adalah:</p>
<ul>
<li><p>persamaan model</p></li>
<li><p>makna nilai konstanta dan koefisien</p></li>
<li><p>uji kualitas model (ANOVA, <code>F-statistic</code>)</p></li>
<li><p>uji kualitas variabel (<code>Pr(&gt;|t|)</code>)</p></li>
</ul>
<div id="tafsiran-persamaan-model" class="section level4 hasAnchor" number="8.6.3.1">
<h4><span class="header-section-number">8.6.3.1</span> Tafsiran persamaan model<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#tafsiran-persamaan-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Persamaan model dapat kita tafsirkan berdasarkan keluaran dari <code>summary</code> berupa <code>Coefficients</code> atau hasil dari <code>tbl_regression</code> milik <code>gtsummary</code>.</p>
<p>Berdasarkan keluaran kedua perintah tersebut, kita dapat mengetahui bagaimana persamaan regresi linearnya dengan mengganti bentuk umum persamaan regresi linear dengan angka-angka yang dihasilkan di <code>model</code>.</p>
<p>Bentuk umum:</p>
<p><span class="math display">\[
y = β_0 + β_1x
\]</span></p>
<p>Dengan mengambil hasil dari <em>summary(model)</em>, kita dapat menuliskan persamaan regresi linear kita menjadi:</p>
<p><span class="math display">\[
y = 93 - 5,3x
\]</span></p>
<p>Dari persamaan model ini kita dapat menggambar garis yang melewati titik-titik data kita. Ini merupakan persamaan garis terbaik dari seluruh kemungkinan persamaan garis yang ada, yang kita tentukan dengan meminimalkan kuadrat terkecil.</p>
<p><img src="figures/mod08-visualize-regression-line-1-1.png" width="672" /></p>
<ul>
<li><p><code>coef(model)[1]</code> mengacu pada keluaran fungsi <code>coef</code> dari variabel <code>model</code> kita yang pertama (<code>[1]</code>), yakni angka <em>intercept</em>/konstantanya. Ini menjadi nilai dari atribut <code>intercept</code> yang terletak dalam fungsi <code>geom_abline</code></p></li>
<li><p><code>coef(model)[2]</code> mengacu pada keluaran fungsi <code>coef</code> dari variabel <code>model</code> kita yang kedua ([<code>2]</code>), yakni angka koefisien variabel independen kita. Ini menjadi nilai dari atribut <code>slope</code> yang terletak dalam fungsi <code>geom_abline</code> karena nilai koefisien variabel independen menunjukkan kemiringan garis persamaan regresi linear kita</p></li>
</ul>
<p>Persamaan model dapat kita tafsirkan berdasarkan keluaran dari <code>summary</code> berupa <code>Coefficients</code> atau hasil dari <code>tbl_regression</code> milik <code>gtsummary</code>.</p>
<p>Berdasarkan keluaran kedua perintah tersebut, kita dapat mengetahui bagaimana persamaan regresi linearnya dengan mengganti bentuk umum persamaan regresi linear dengan angka-angka yang dihasilkan di <code>model</code>.</p>
<p>Bentuk umum:</p>
<p><span class="math display">\[
y = β_0 + β_1x
\]</span></p>
<p>Dengan mengambil hasil dari <em>summary(model)</em>, kita dapat menuliskan persamaan regresi linear kita menjadi:</p>
<p><span class="math display">\[
y = 93 - 5,3x
\]</span></p>
<p>Dari persamaan model ini kita dapat menggambar garis yang melewati titik-titik data kita. Ini merupakan persamaan garis terbaik dari seluruh kemungkinan persamaan garis yang ada, yang kita tentukan dengan meminimalkan kuadrat terkecil.</p>
<p><img src="figures/mod08-visualize-regression-line-2-1.png" width="672" /></p>
<ul>
<li><p><code>coef(model)[1]</code> mengacu pada keluaran fungsi <code>coef</code> dari variabel <code>model</code> kita yang pertama (<code>[1]</code>), yakni angka <em>intercept</em>/konstantanya. Ini menjadi nilai dari atribut <code>intercept</code> yang terletak dalam fungsi <code>geom_abline</code></p></li>
<li><p><code>coef(model)[2]</code> mengacu pada keluaran fungsi <code>coef</code> dari variabel <code>model</code> kita yang kedua ([<code>2]</code>), yakni angka koefisien variabel independen kita. Ini menjadi nilai dari atribut <code>slope</code> yang terletak dalam fungsi <code>geom_abline</code> karena nilai koefisien variabel independen menunjukkan kemiringan garis persamaan regresi linear kita</p></li>
</ul>
</div>
<div id="tafsiran-nilai-konstanta-dan-koefisien" class="section level4 hasAnchor" number="8.6.3.2">
<h4><span class="header-section-number">8.6.3.2</span> Tafsiran nilai konstanta dan koefisien<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#tafsiran-nilai-konstanta-dan-koefisien" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Persamaan regresi linear ini bermakna nilai konstanta sebesar 93 berarti bahwa dengan tinggal di kampus (<span class="math inline">\(x=0\)</span>), mahasiswa masih akan mengeluarkan biaya sebesar 93.000 rupiah (ingat bahwa variabel <code>biaya sepekan</code> menggunakan satuan ribuan rupiah) untuk mengakses kampus selama sepekan. Kita bisa pahami hal tersebut sebagai perkiraan harga sewa penginapan di kampus.</p>
<p>Sementara itu, nilai koefisien sebesar <span class="math inline">\(-5,3\)</span> berarti bahwa penambahan jarak sebesar 1 km akan <strong>mengurangi</strong> biaya transportasi sepekan sebesar 5.300 rupiah. Artinya, makin jauh 1 km seorang mahasiswa tinggal dari kampus, makin kecil pula biaya transportasi sepekannya sebesar 5.300 rupiah.</p>
<blockquote>
<p><strong>Pertanyaan bonus:</strong> Mengapa mahasiswa yang tinggal lebih jauh dari kampus biaya perjalanan sepekannya lebih kecil? Bukankah biaya transportasi makin jauh malah makin mahal?</p>
</blockquote>
</div>
<div id="tafsiran-uji-kualitas-model" class="section level4 hasAnchor" number="8.6.3.3">
<h4><span class="header-section-number">8.6.3.3</span> Tafsiran uji kualitas model<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#tafsiran-uji-kualitas-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Uji kualitas model kita terdiri atas <em>standard error</em> dari residual, koefisien determinasi atau <span class="math inline">\(R^2\)</span>, dan uji signifikansi persamaan menggunakan statistik <span class="math inline">\(F\)</span> (<code>F-statistic</code>) yang merupakan hasil ANOVA <em>(analysis of variance)</em>.</p>
<ul>
<li><p><em>Standard error</em> dari residual mencerminkan rata-rata galat (residu), yaitu selisih nilai variabel dependen yang dihitung (biaya perjalanan sepekan hasil prediksi dari model) dengan nilai variabel dependen yang kita peroleh dari data.</p>
<ul>
<li>Hasil <code>summary</code> menunjukkan angka 38,11 yang artinya rata-rata kesalahan prediksi dari model kita adalah sebesar 38.110 rupiah.</li>
</ul></li>
<li><p>Koefisien determinasi atau <span class="math inline">\(R^2\)</span> menyatakan kesesuaian <em>(fit)</em> dari model kita, yakni seberapa banyak proporsi variansi data variabel dependen kita (biaya perjalanan sepekan) dijelaskan oleh variabel independennya (jarak dari kampus ke tempat tinggal).</p>
<p>Sisa dari angka <span class="math inline">\(R^2\)</span> ini adalah banyak variansi yang tidak dijelaskan oleh variabel independen, artinya dijelaskan oleh variabel lainnya yang tidak ada dalam model dan juga keacakan (misal dalam pengambilan data atau kejadian acak).</p>
<ul>
<li><p>Hasil <code>summary</code> menunjukkan angka 0,095 yang berarti hanya 9,5% variansi biaya perjalanan sepekan dijelaskan oleh variansi jarak perjalanan ke kampus.</p></li>
<li><p>Makin tinggi nilai <span class="math inline">\(R^2\)</span> dari model kita, makin besar proporsi variansi variabel dependen kita dijelaskan oleh variabel independennya.</p></li>
<li><p>Hal ini menunjukkan bahwa pengaruh dari variabel independen kita terhadap variabel dependennya kuat</p></li>
</ul></li>
<li><p>Koefisien uji signifikansi (<span class="math inline">\(F\)</span>) (<code>F-statistics</code>) adalah uji hipotesis ANOVA <em>(analysis of variance)</em> yang membuktikan hipotesis nol bahwa tidak ada hubungan antara variabel dependen dengan variabel independen yang kita modelkan. Penerimaan hipotesis nol ini ditandai dari nilai signifikansi (<code>p-value</code>) yang lebih kecil dari 5% (<code>0.05</code>).</p>
<ul>
<li><p>Hasil <code>summary</code> menunjukkan bahwa nilai <code>p-value</code> kita adalah <code>1,721e-05</code>. Angka tersebut menyatakan notasi ilmiah <span class="math inline">\(1,721\times10^{-5}\)</span> yang berarti bahwa nilai <code>p-value</code> kita sangat-sangat lebih kecil dari <code>0.05.</code></p></li>
<li><p>Ini artinya kita tidak dapat menerima hipotesis nol kita yang menyatakan tidak ada hubungan antara variabel biaya perjalanan sepekan (variabel dependen) dengan variabel jarak tempuh ke kampus (variabel independen).</p></li>
</ul></li>
</ul>
<p><strong>Simpulan tafsiran kualitas model</strong>: kita sudah melihat bahwa hubungan kausal antara variabel jarak ke kampus terhadap biaya perjalanan sepekan adalah terbalik dengan besar kemiringan 5,3. Hubungan kausal tersebut benar-benar ada berdasarkan hasil dari koefisien uji signifikansi (ANOVA) yang <em>p-value-</em>nya &lt;0,05. Akan tetapi, hubungan tersebut tidak cukup kuat karena nilai koefisien determinasi yang kecil, yakni hanya 9% saja.</p>
</div>
<div id="tafsiran-uji-kualitas-variabel" class="section level4 hasAnchor" number="8.6.3.4">
<h4><span class="header-section-number">8.6.3.4</span> Tafsiran uji kualitas variabel<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#tafsiran-uji-kualitas-variabel" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Uji kualitas variabel adalah pengujian terhadap signifikansi atau kepentingan variabel independen kita. Hasil pengujian ini diperlihatkan oleh angka <em>p-value</em> dari uji t (<code>t value</code>)-nya, yakni yang ada di kolom <code>Pr(&gt;|t|)</code>.</p>
<p>Apabila nilai <code>Pr(&gt;|t|)</code> kita &gt;0,05 maka variabel independen kita dianggap <strong>tidak signifikan</strong>, karena artinya nilai koefisien yang ada di kolom <code>Estimate</code> <strong>sebenarnya adalah nol</strong> sehingga <strong>bisa dikeluarkan dari persamaan regresi linear</strong>.</p>
<p>Sebaliknya, jika nilai <code>Pr(&gt;|t|)</code> kita &lt;0,05 maka variabel independen kita dianggap <strong>signifikan</strong>, artinya nilai koefisien yang ada di kolom <code>Estimate</code> <strong>sebenarnya adalah nilai koefisien tersebut.</strong></p>
<p>Nilai <code>Pr(&gt;|t|)</code> variabel <code>x</code> adalah <code>1,721e-05</code> yang berarti koefisien senilai <code>-5.321</code> adalah <strong>signifikan</strong>.</p>
</div>
</div>
<div id="melakukan-prediksi" class="section level3 hasAnchor" number="8.6.4">
<h3><span class="header-section-number">8.6.4</span> Melakukan Prediksi<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#melakukan-prediksi" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Kita melakukan prediksi dengan menggunakan perintah <code>predict</code>. Misalkan kita ingin melakukan prediksi biaya perjalanan sepekan untuk mahasiswa yang tinggal di jarak 90 dan 120 km dari kampus</p>
<pre><code>##         1         2 
## -386.3117 -545.9345</code></pre>
<ul>
<li><p>Perintah <code>tibble</code> adalah perintah untuk membuat dataset berisi kolom <code>x</code> yang terdiri atas 2 nilai: 90 km dan 120 km. Kita menyimpan dataset contoh tersebut ke dalam variabel bernama <code>bahan_pred</code></p></li>
<li><p>Dalam membuat dataset untuk prediksi kita harus memperhatikan nama variabel/nama kolom yang kita berikan dalam perintah <code>tibble</code>. Nama kolom yang akan kita prediksi harus <strong>sama persis</strong> dengan nama variabel yang kita nyatakan dalam perintah <code>lm</code>.</p></li>
</ul>
</div>
</div>
<div id="model-regresi-linear-berganda" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> Model Regresi Linear Berganda<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#model-regresi-linear-berganda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dalam bagian ini kita hanya akan mempelajari penggunaan variabel <em>dummy</em> untuk meningkatkan kekuatan prediksi kita. Di akhir, Anda akan menafsirkan hal-hal yang sudah Anda pelajari pada bagian regresi linear.</p>
<p>Kita akan menggunakan variabel <code>jenis tempat tinggal</code> untuk variabel <em>dummy</em>. Pertama, kita akan mengatur jenis nilai pada kolom <code>jenis tempat tinggal</code> menggunakan perintah <code>factor</code>.</p>
<p>Kedua, kita akan membuat model seperti halnya yang kita lakukan dalam analisis regresi linear sederhana. Kita akan menggunakan nama yang lebih representatif.</p>
<pre><code>## 
## Call:
## lm(formula = biaya ~ jarak + ling, data = data_mahasiswa_online)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -73.743 -23.421  -2.143  19.424 114.322 
## 
## Coefficients:
##                              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                    98.103      8.104  12.105  &lt; 2e-16 ***
## jarak                          -4.954      1.118  -4.431 1.63e-05 ***
## lingKos sendiri               -20.779      8.787  -2.365   0.0191 *  
## lingRumah mengontrak bersama  -17.198     10.409  -1.652   0.1002    
## lingRumah mengontrak pribadi   27.744     16.031   1.731   0.0852 .  
## lingRumah pribadi              20.348      9.866   2.062   0.0406 *  
## lingRumah saudara              10.365     12.689   0.817   0.4151    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 34.23 on 180 degrees of freedom
## Multiple R-squared:  0.2899, Adjusted R-squared:  0.2663 
## F-statistic: 12.25 on 6 and 180 DF,  p-value: 1.538e-11</code></pre>
<p>Selanjutnya, kita akan menafsirkan hasil dari summary model ini.</p>
<div id="penjelasan-variabel-dummy" class="section level3 hasAnchor" number="8.7.1">
<h3><span class="header-section-number">8.7.1</span> Penjelasan Variabel <em>Dummy</em><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#penjelasan-variabel-dummy" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dalam persamaan model kita tersebut, variabel <code>ling</code> atau <code>jenis tempat tinggal</code> diubah menjadi variabel <em>dummy</em> :</p>
<ol style="list-style-type: decimal">
<li><code>lingKos sendiri</code>,</li>
<li><code>lingRumah mengontrak bersama</code>,</li>
<li><code>lingRumah mengontrak pribadi</code>,</li>
<li><code>lingRumah pribadi</code>, dan</li>
<li><code>lingRumah saudara</code>.</li>
</ol>
<p>Nama variabel-variabel tersebut tak lain adalah gabungan kata <code>ling</code> dengan tiap-tiap kategori dalam variabel <code>jenis tempat tinggal</code>.</p>
<p>Perhatikan bahwa kita jadi memiliki 5 variabel <em>dummy</em> dari satu variabel kategoris <code>jenis tempat tinggal</code> yang terdiri atas 6 kategori nilai: “Kos bersama-sama”, “Kos sendiri”, “Rumah mengontrak bersama”, “Rumah mengontrak pribadi”, “Rumah pribadi”, dan “Rumah saudara.”</p>
<p>Variabel <em>dummy</em> adalah variabel yang bernilai 0 (nol) atau 1 (satu) saja. Nol artinya variabel <em>dummy</em> tersebut bernilai “salah” atau “tidak”, sedangkan satu artinya variabel <em>dummy</em> tersebut bernilai “benar” atau “ya.”</p>
<p>Variabel-variabel <em>dummy</em> yang 5 buah ini hanya akan bernilai 1 atau 0 sesuai dengan kategori dari variabel <code>jenis tempat tinggal</code> suatu objek. Perhatikan bahwa kita tidak punya “<code>lingKos sendiri</code>” dalam variabel <em>dummy</em> kita. Ini artinya apabila kategori <code>jenis tempat tinggal</code> suatu objek adalah “Kos sendiri”, <strong>kelima variabel <em>dummy</em> akan bernilai 0.</strong></p>
<p>Tabel berikut merangkum nilai-nilai variabel <em>dummy</em> untuk setiap kategori nilai variabel <code>jenis tempat tinggal</code>.</p>
<table>
<caption>Nilai variabel dummy untuk setiap kategori</caption>
<colgroup>
<col width="17%" />
<col width="12%" />
<col width="21%" />
<col width="21%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th>Kategori</th>
<th><code>lingKos sendiri</code></th>
<th><code>lingRumah mengontrak bersama</code></th>
<th><code>lingRumah mengontrak pribadi</code></th>
<th><code>lingRumah pribadi</code></th>
<th><code>lingRumah saudara</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kos sendiri</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Rumah mengontrak bersama</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Rumah mengontrak pribadi</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Rumah pribadi</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Rumah saudara</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>Kos bersama</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
<div id="interpretasi-variabel-dummy" class="section level3 hasAnchor" number="8.7.2">
<h3><span class="header-section-number">8.7.2</span> Interpretasi Variabel <em>Dummy</em><a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#interpretasi-variabel-dummy" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dalam menginterpretasi variable <em>dummy</em> kita tidak bisa menggunakan <code>Pr(&gt;|t|)</code> semata, karena variabel <em>dummy</em> pada hakikatnya sepaket. Jadi, walaupun nilai <code>Pr(&gt;|t|)</code> sebuah variabel <em>dummy</em> adalah &gt;0,05 ia akan tetap berada dalam persamaan regresi linear.</p>
<p>Interpretasi koefisien variabel <em>dummy</em> adalah dengan memahami bahwa nilai variabel dependen berubah sesuai nilai koefisien apabila variabel <em>dummy</em> tersebut bernilai <strong>benar</strong> atau <strong>1</strong>. Artinya, jika mahasiswa tinggal di kosan sendirian (<code>lingKos sendiri = 1</code>), maka biaya transportasi sepekan berkurang sebesar <code>20.779</code> yang juga berarti sebesar 20,7 ribu rupiah. Jika mahasiswa tinggal di rumah pribadi (<code>lingRumah pribadi = 1</code>) maka biaya transportasi sepekan bertambah sebesar <code>20.348</code> atau 20,3 ribu rupiah.</p>
</div>
<div id="prediksi-model" class="section level3 hasAnchor" number="8.7.3">
<h3><span class="header-section-number">8.7.3</span> Prediksi Model<a href="modul-8-analisis-hubungan-kausalitas-regresi-linear-sederhana-dan-berganda.html#prediksi-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dari persamaan model regresi linear kita, kita juga dapat memprediksi nilai biaya perjalanan sepekan untuk mahasiswa-mahasiswa dengan kondisi lain. Misalnya kita ingin memprediksi biaya sepekan transportasi mahasiswa yang tinggal di Rumah saudara berjarak 7,9 km dari kampus dan di Rumah kontrakan bersama yang berjarak 10 km dari kampus.</p>
<pre><code>##        1        2 
## 69.33008 31.36362</code></pre>
<blockquote>
<p><strong>Jawablah:</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Bagaimana persamaan model regresi linear berganda kita?</li>
<li>Tafsirlah kualitas model kita, mulai uji kualitas model (<span class="math inline">\(F\)</span>), <span class="math inline">\(R^2\)</span>, serta uji kualitas setiap variabel</li>
<li>Apa saja yang meningkatkan dan menurunkan biaya perjalanan sepekan mahasiswa?</li>
</ol>
</blockquote>
<div class="rmdexercise">
<p><strong>Aktivitas Mandiri 4: Analisis Regresi Komprehensif [STP-13.3, STP-14.3]</strong></p>
<p><strong>A. Regresi Linear Sederhana [STP-13.3]:</strong></p>
<p>Model: <code>jumlah perjalanan weekdays</code> vs <code>jarak</code>
1. Buat model sederhana
2. Tuliskan persamaan regresi
3. Interpretasikan intercept dan slope
4. Uji kualitas model (F-statistic, R²)</p>
<p><strong>B. Regresi Linear Berganda [STP-14.3]:</strong></p>
<p>Model: <code>jumlah perjalanan weekdays</code> ~ <code>jarak</code> + <code>umur</code> + <code>jenis tempat tinggal</code>
1. Buat model berganda
2. Tuliskan persamaan lengkap
3. Identifikasi variabel signifikan
4. Bandingkan R²</p>
<p><strong>C. Interpretasi:</strong>
- Faktor yang meningkatkan/menurunkan jumlah perjalanan?
- Proporsi variansi yang dijelaskan?</p>
</div>
<hr />

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modul-7-analisis-hubungan-korelatif-korelasi-variabel-metrik.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modul-9-analisis-hubungan-multivariat-interdependensi---analisis-faktor-dan-pca.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
